(step1) StringCalculator 구현
next-step/ddd-legacy pull request #112
Opened 2021-07-27 16:09 UTC by DongHyukki

이전 TDD 수업때 구현했던거라. 그때랑.. 조금 다르게 구현해 보았습니다.

commit 은 다음 step부터 잘 쪼개서 하도록 하겠습니다.

리뷰어님 앞으로 잘 부탁드려요.!!

2021-07-29 03:38 UTC, liquidjoo requested changes
안녕하세요. 
동혁님 이번 리뷰어를 맡은 김성주 입니다.
몇가지 코멘트 남겼어요! 확인하고 피드백 반영 후 리뷰 요청 주세요 :)

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/CalculateFunction.java
> +    }
객체의 역할을 나누고 원시 값을 포장하게 되면 해당 메서드는 다른 곳으로 옮겨볼 수 있을 것 같아요~

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/StringCalculatorTest.java
> +}
파일 마지막에 엔터(개행문자)를 넣어주세요!!
이유는 리뷰를 진행할 때 깃허브에서 경고메시지를 지우기 위함입니다.
좀 더 알고 싶으시면 재미삼아 아래의 링크를 보시는 것도 추천 드립니다.
https://minz.dev/19
Intellij 를 사용하실 경우엔
Preferences -> Editor -> General -> Ensure line feed at file end on save 를 체크해주시면
파일 저장 시 마지막에 개행문자를 자동으로 넣어줍니다!

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypes.java
> +public enum TextCalculateTypes implements CalculateFunction {
`TextCalculateTypes` 가 너무 많은 역할을 하는 것 같아요.
메소드 분리 등을 통해서 역할을 나누어 보는 것이 좋을 것이 어떨가요?

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypes.java
> +            return 0;
매직넘버
매직 넘버란 코드 안에 작성된 구체적인 숫자 혹은 문자열을 말합니다. 그리고 매직 넘버의 단점은 아래와 같습니다.

- 의미를 이해하기 어렵다.
- 복수의 장소에서 사용된다면 변경하기 힘들다.

그런 매직 넘버는 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여 보는 것은 어떨까요?

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypes.java
> +            int number = Integer.parseInt(text);
프로그래밍 요구사항 중에 `규칙 3: 모든 원시 값과 문자열을 포장한다.`
int 값을 포장하는 클래스를 만들어 사용해보는 것이 어떨까요?

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypes.java
> +                    .reduce(0, Integer::sum);
스트림으로 기능을 나누는 것도 좋은 방법이지만 객체 및 메서드 분리를 통해서 명확하게 표현해보는 것이 어떨까요?

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypes.java
> +        }
프로그래밍 요구사항에 있는 `규칙 2: else 예약어를 쓰지 않는다.` 와 다중 if 를 사용하는 것은 동일한 규칙입니다.
if 를 줄여볼 수 있을까요?

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypes.java
> +        return false;
```suggestion
        return m.find();
```

이렇게 표현도 가능할 것 같아요 :)

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypesTest.java
> +
💯 테스트코드 잘 짜주셨어요~

2021-07-29 03:38 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/TextCalculateTypesTest.java
> +}
파일 마지막에 엔터(개행문자)를 넣어주세요!!
이유는 리뷰를 진행할 때 깃허브에서 경고메시지를 지우기 위함입니다.
좀 더 알고 싶으시면 재미삼아 아래의 링크를 보시는 것도 추천 드립니다.
https://minz.dev/19
Intellij 를 사용하실 경우엔
Preferences -> Editor -> General -> Ensure line feed at file end on save 를 체크해주시면
파일 저장 시 마지막에 개행문자를 자동으로 넣어줍니다!

2021-07-29 15:19 UTC, DongHyukki commented on src/test/java/kitchenpos/stringcalculator/CalculateFunction.java
> +    }
넵 좋은 방법인것 같아요~

2021-07-30 13:31 UTC, liquidjoo approved these changes
깔끔한 코드 구현과 피드백 반영 너무 좋았습니다 💯 
다음 단계를 진행 해주세요. 😄

2021-07-30 13:31 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/NumberParser.java
> +        Matcher m = Pattern.compile(CUSTOM_DELIMITER_REGEX).matcher(text);
`Pattern` 의 `compile` 메서드는 내부 로직을 보면 매번 Pattern 객체를 생성합니다.
계산기를 한 번만 실행하는 것이 아니라 계속 해서 계산을 한다면 매번 객체를 생성하는 일이 발생 합니다.
어떻게 객체의 생성을 줄여볼 수 있을까요?

2021-07-30 13:31 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/OperationType.java
> +public enum OperationType {
enum 클래스 활용 👍

2021-07-30 13:31 UTC, liquidjoo commented on src/test/java/kitchenpos/stringcalculator/ParsedNumber.java
> +public class ParsedNumber {
원시 값을 포장해서 객체의 캡슐화와 응집도를 높인 것 같네요 👍

2021-07-30 13:31 UTC, merged