Step1 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #116
Opened 2021-07-28 09:01 UTC by loop-study

안녕하세요 박현철입니다.
제공해주는 테스트 코드 기반으로 진행했습니다.
커밋 내역은 [여기서](https://github.com/next-step/ddd-legacy/pull/115) 확인 부탁드리겠습니다.
컨벤션을 준수했는지 체크 부탁드립니다.
감사합니다!

2021-07-29 00:13 UTC, serverwizard requested changes
안녕하세요. 이번 미션 리뷰를 맡게된 홍종완이라고 해요! 😄 

요구사항까지 README.md 파일에 잘 작성해 주셨어요! 👏 
바로 다음 step으로 넘어갈 수도 있었지만, 조금 더 deep하게 생각해 볼만한 질문을 몇 개 드려봤어요.
참고해서 고민해보시면 좋겠어요.

궁금한점 있으시면 편하게 코멘트 또는 DM 남겨주세요

2021-07-29 00:13 UTC, serverwizard commented on src/main/java/stringcalculator/README.md
> +- 문자열 계산기에 숫자 이외의 값 또는 음수를 전달하는 경우 RuntimeException 예외를 throw 한다.
요구사항을 README.md에 작성해 주셨네요. 👏

2021-07-29 00:13 UTC, serverwizard commented on src/main/java/stringcalculator/StringCalculator.java
> +    private String[] textToTokens(String text) {
잘 구현해주셨는데요. 조금 더 deep하게 생각해 볼만한 질문을 드려볼게요. 😄 
textToTokens책임을 문자열 덧셈 계산기의 책임이라고 볼 수 있는 걸까요? 

만약, 좀 더 역할에 맞는 클래스가 있다면 그 곳에서 해당 책임을 가지게 할 수는 없는 걸까요?

2021-07-29 00:13 UTC, serverwizard commented on src/main/java/stringcalculator/StringCalculator.java
> +    private int stringToInt(String text) {
stringToInt책임 또한 좀 더 역할에 맞는 클래스가 있다면 그 곳에서 해당 책임을 가지게 할 수는 없는 걸까요?

2021-07-29 00:13 UTC, serverwizard commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +        assertThat(calculator.add(text)).isSameAs(Integer.parseInt(text));
assertj에는 isSameAs 메소드와 유사한 isEqualTo 메소드도 있는데요. 
이 둘에 대해 이번 기회에 학습해보시면 좋을 것 같아요.
참고로 실무에서는 isEqualTo를 많이 사용해요! 😄 

힌트: 동일성, 동등성

2021-07-30 12:04 UTC, loop-study commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +        assertThat(calculator.add(text)).isSameAs(Integer.parseInt(text));
isSameAs는 주소값 비교하고
isEqualTO는 값 비교!
확인했습니다!

2021-07-30 12:09 UTC, loop-study commented
안녕하세요 박현철입니다.
DDD 교육인데, 문자열 계산기에 모든 역할을 때려넣는 짓을 해버리고 제출해버렸네요🙈
StringCalculator는 루트 도메인으로 계산기를 제어하는 용도로 변경하고
문자열을 int[]로 변경을 담당하는 하위 도메인(Numbers)과 
변경된 int[]로 연산을 담당하는 하위 도메인(Operation)으로 변경해봤습니다.
추가된 하위 도메인에 맞게 테스트도 간단히 추가했습니다.
확인 부탁드립니다.

2021-08-01 11:36 UTC, serverwizard approved these changes
첫 번째 미션 잘 구현 해주셨어요 😄 
피드백 반영 너무 잘 해주셨네요 💯 

간단한 리뷰 몇 가지 남겨뒀으니 참고만 부탁드릴게요.
다음 미션도 화이팅 입니다 👍

2021-08-01 11:36 UTC, serverwizard commented on src/main/java/stringcalculator/Delimiter.java
> +        Matcher m = Pattern.compile(CUSTOM_PATTERN).matcher(text);
Pattern객체는 생성하는데 매우 비싼 객체인데요. 따라서 패턴 자체를 미리 생성해두고 재활용하면 좋아요.
주석에도 패턴이 반복해서 사용된다면 미리 만들어놓고 재사용하는것이 더 효율적이라고 나와 있구요.

```
아이템 6. 불필요한 객체 생성을 피하라

Pattern.compile()이 결국 Pattern 객체를 생성하는 정적 팩토리 메소드다.
따라서, Pattern을 상수로 정의하고 Matcher만 생성하여 검증하는 식으로 구현한다.
```

2021-08-01 11:36 UTC, serverwizard commented on src/main/java/stringcalculator/Delimiter.java
> +public class Delimiter {
역할에 따른 클래스 분리 👍

2021-08-01 11:36 UTC, serverwizard commented on src/main/java/stringcalculator/Numbers.java
> +public class Numbers {
역할에 따른 클래스 분리 👍

2021-08-01 11:36 UTC, serverwizard commented on src/main/java/stringcalculator/Operations.java
> +public class Operations {
역할에 따른 클래스 분리 👍

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/DelimiterTest.java
> +        assertArrayEquals(result, check);
참고로 테스트 검증시 AssertJ를 사용하면 조금 더 가독성이 좋아지는 것 같아요.
따라서, 실무에서도 많이 사용하고 있어요~ 
이번 기회에 사용해보시면 좋을 것 같아요 😄

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/OperationsTest.java
> +        assertThat(result).isSameAs(check);
테스트 의도가 값을 비교하는 것 같은데, 이럴 땐 isEqualTo를 사용해 보는건 어떨까요?

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/DelimiterTest.java
> +class DelimiterTest {
테스트 코드 작성 👍

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/NumbersTest.java
> +class NumbersTest {
테스트 코드 작성 👍

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/OperationsTest.java
> +class OperationsTest {
테스트 코드 작성 👍

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
테스트 코드 작성 👍

2021-08-01 11:36 UTC, serverwizard commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +        calculator = new StringCalculator();
현재 StringCalculator를 사용하기 위해선 객체를 생성해야만 하는데요.
메서드를 static method로 변경하면 굳이 객체를 생성하지 않고도 사용할 수 있을 것 같은데, 그렇게 하지 않은 이유가 있었을까요?

2021-08-01 11:37 UTC, merged

2021-08-02 08:21 UTC, loop-study commented on src/main/java/stringcalculator/Delimiter.java
> +        Matcher m = Pattern.compile(CUSTOM_PATTERN).matcher(text);
제공해주는 코드를 그대로 사용하다보니 꼼꼼하게 확인을 못했네요.🙈

2021-08-02 08:23 UTC, loop-study commented on src/test/java/stringcalculator/DelimiterTest.java
> +        assertArrayEquals(result, check);
배열을 비교하려고 찾다보니 사용하게 되었네요.
AssertJ 위주로 테스트 진행하도록 노력하겠습니다.

2021-08-02 08:30 UTC, loop-study commented on src/test/java/stringcalculator/OperationsTest.java
> +        assertThat(result).isSameAs(check);
값 비교에 isEqualTo로 진행하겠습니다!

2021-08-02 08:31 UTC, loop-study commented on src/test/java/stringcalculator/StringCalculatorTest.java
> +        calculator = new StringCalculator();
제공해주는 코드를 그대로 사용한다는 생각을 하다보니 부조화가 생겼네요...🙈🙈🙈🙈