Step3 테스트를 통한 코드보호
next-step/ddd-legacy pull request #169
Opened 2021-08-19 13:26 UTC by anjaemin

2021-08-23 03:37 UTC, serverwizard requested changes
안녕하세요 재민님
테스트 코드 너무 잘 작성 해주셨어요. 👍
몇가지 코멘트 남겼는데, 이 부분만 다시 한번 확인해주시면 좋을 것 같아요~

2021-08-23 03:37 UTC, serverwizard commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest {
Mock을 사용해서 단위테스트를 하셔도 됐을 것 같은데, 통합테스트(@SpringBootTest)를 하신 이유가 있으실까요?
참고로 mock 프레임워크를 사용하지 않고 fake 객체를 사용해서 테스트해 볼 수도 있을 것 같아요!
fake객체를 이용한 테스트는 나중에 기회되면 작성해보세요 :)

2021-08-23 03:37 UTC, serverwizard commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        menu.setMenuProducts(Collections.singletonList(menuProduct));
테스트 픽스처 역할을하는 클래스를 별도로 만들어보는 건 어떨까요?

2021-08-23 03:37 UTC, serverwizard commented on README.md
> +  - 상품 추가
요구사항 정리를 꼼꼼하게 잘 해주셨네요 👍
다만, 요구사항 정리는 이번 미션으로 끝났다라기 보다, 앞으로 미션을 진행해가면서 나름대로 수정/보완해나가시면 더 좋을 것 같아요. 😄

2021-08-23 03:37 UTC, serverwizard commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +                .isInstanceOf(IllegalArgumentException.class);
이건 개인적인 의견인데요. 
테스트 코드를 작성할 때 given, when, then을 기준으로 개행을 해준다면 좀 더 가독성이 좋아질 것 같아요!

2021-08-23 03:37 UTC, serverwizard commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        assertThat(actual.getStatus()).isEqualTo(OrderStatus.ACCEPTED);
참고로 테스트 검증 방법에는 상태검증 뿐만 아니라 행위검증도 있어요!
`ex. verify( ... )`

2021-08-23 14:40 UTC, anjaemin commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        menu.setMenuProducts(Collections.singletonList(menuProduct));
테스트 픽스처 역할을 하는 클래스 라는 말에 대해서 잘모르겠는데요 혹시 참고할만한 자료가 있을까요?;;;
저 위의 Menu를 대신해서 사용할 수 있는 클래스? 테스트 픽스처를 생성해주는 클래스? 잘모르겠습니다;;;

2021-08-23 14:44 UTC, anjaemin commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest {
Mock을 사용해서 단위테스트를 작성해본적이 거의 없어서 좀더 익숙한 @SpringBootTest를 사용했습니다.
mock을 사용한 테스트와 fake객체를 사용한 테스트도 작성해보아야 할것같네요

2021-08-25 12:29 UTC, anjaemin commented
피드백 내용을 참고해서 수정해봤는데요
MakeTexture는 테스트 픽스처 역할을 하는 클래스라고 하셔서 테스트픽스처를 생성해주는 클래스를 만들었는데 이게 맞는건가요? 
MockMenuServiceTest 를 추가했는데 Mockito를 사용한 테스트케이스를 이렇게 작성하는게 맞나요?

2021-08-28 02:46 UTC, serverwizard commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        menu.setMenuProducts(Collections.singletonList(menuProduct));
테스트에 사용될 데이터를 미리 준비한 클래스라고 보시면 될 것 같아요.
```
public class ProductFixture {
    public static Product createProduct() {
        Product product = new Product();
        product.setId(UUID.randomUUID());
        product.setName("간장치킨");
        product.setPrice(BigDecimal.valueOf(12000));
        return product;
    }

   ...
}
```

2021-08-28 03:07 UTC, serverwizard commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +class MenuGroupServiceTest {
@SpringBootTest 애노테이션을 사용하게 되면 실제 애플리케이션 실행될 때와 똑같이 등록된 빈들을 모두 load하기 때문에, 규모가 클수록 느려질 수가 있어요.

2021-08-28 03:12 UTC, serverwizard approved these changes
테스트를 통한 코드보호 잘 작성해주셨네요. 👍
질문 주신 부분에 대한 답변 남겨뒀으니 참고만 부탁드릴게요.

제가 드린 피드백이 정답은 아니지만 도움이 되셨음 좋겠네요.
그럼 마지막까지 화이팅하세요. 😄

2021-08-28 03:12 UTC, serverwizard commented on src/test/java/kitchenpos/application/MakeFixture.java
> +    public static Menu createMenuTestFixture() {
TestFixture 👍

2021-08-28 03:12 UTC, serverwizard commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        takeoutOrder.setType(OrderType.TAKEOUT);
추후 이런 것들도 TestFixture에서 선언해두시면 좋을 것 같아요!

2021-08-28 03:12 UTC, merged

2021-08-28 03:12 UTC, serverwizard commented
테스트 픽스처는 테스트에 사용될 데이터를 미리 준비해둔 클래스라고 보시면 될 것 같아요.
```
public class ProductFixtures {
    public static final Long FRIED_CHICKEN_ID = 1L;
    public static final Long SEASONED_CHICKEN_ID = 2L;

    public static Product friedChicken() {
        final Product product = new Product();
        product.setId(FRIED_CHICKEN_ID);
        product.setName("후라이드");
        product.setPrice(BigDecimal.valueOf(16_000L));
        return product;
    }

    public static Product seasonedChicken() {
        final Product product = new Product();
        product.setId(SEASONED_CHICKEN_ID);
        product.setName("양념치킨");
        product.setPrice(BigDecimal.valueOf(16_000L));
        return product;
    }
}
```
테스트 픽스처란 테스트를 반복적으로 수행 할 수 있게 도와주고 매번 동일한 결과르 얻을 수 있는 '기반이 되는 상태나 환경' 을 말해요.

참고 : https://zorba91.tistory.com/304