[Step1 문자열 계산기] mynameisdaun 1차 PR
next-step/ddd-legacy pull request #200
Opened 2022-03-01 15:51 UTC by mynameisdaun

설레는 마음으로 첫번째 PR 남깁니다😀

가장 고민했던 부분은 
기본 구분자가 사용되었는지 ,
커스텀 구분자가 사용되었는지 확인하는 로직 이었습니다.

`    private String[] getNumbersFromText(String text) {
        String[] numbers = text.split(DEFAULT_DELIMITER_REGEX);
        /* 커스텀 구분자가 지정된 경우*/
        Matcher matcher = Pattern.compile(CUSTOM_DELIMITER_REGEX).matcher(text);
        if (matcher.find()) {
            String delimiter = matcher.group(1);
            numbers = matcher.group(2).split(delimiter);
        }
        return numbers;
    }
`

어떻게 하면 더 깔끔하게 구현할 수 있었을까요?

감사합니다.

2022-03-02 00:08 UTC, seok-2-o commented on src/test/java/calculator/Calculator.java
> +        if (text.length() == 1 && isNumeric(text)) {
제 누추한 PR에 다녀가셨군요 :) 좋은 말씀 감사합니다.
저도 방문한김에 리뷰하나 남기면
입력값으로 두자리 이상의 숫자가 입력되게 되면 해당 로직을 회피할 수 있는데 의도하신 것인지 궁금하네요.
```java

new Calculator().add("10");

```
이번 수업 같이 힘내서 완주해봐요 👯

2022-03-02 12:31 UTC, liquidjoo requested changes
안녕하세요 다운님 이번 미션 리뷰어를 맡은 김성주 입니다 :)
미션 구현 잘 해주셨어요~
코멘트 남겼어요 확인하고 다시 요청주세요 🙇

2022-03-02 12:31 UTC, liquidjoo commented on src/test/java/calculator/Calculator.java
> +        if (text.length() == 1 && isNumeric(text)) {
해당 로직은 실행이 되나 두자리 이상의 숫자를 받을 땐 하위 로직을 통해서 결과 값이 도출이 됩니다 :)
만약 계산 하는 숫자가 하나 일 때를 의도 하신거면 로직을 수정해야 할 것 같아요~

2022-03-05 06:50 UTC, liquidjoo approved these changes
피드백 반영 잘해주셨어요 👍 
다음 단계 진행해주세요~ 🙇

2022-03-05 06:51 UTC, merged