[Step2 기능요구사항 정리] mynameisdaun 1차 PR
next-step/ddd-legacy pull request #231
Opened 2022-03-05 06:59 UTC by mynameisdaun

추후 커밋 메세지와 통일화를 위하여, 
명령문으로 작성 하였는데 현업에
Best Practice는 어떠한지 궁금합니다 !

2022-03-06 12:30 UTC, liquidjoo requested changes
2단계 미션 잘 구현해주셨어요
몇 가지 코멘트 남겼어요 확인하고 다시 요청주세요 🙇

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +- [ ] 상품을 등록 할 수 있다
도메인 내의 어노테이션 및 유효성 검사를 보면 필수값 여부도 확인 할 수 있을 것 같네요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +    - [ ] 메뉴는 하나 이상의 상품으로 구성되어야 한다
상품이 Product 를 뜻하는 것인지 MenuProduct 를 표현하는 것인지 확실하게 표현하면 더 좋을 것 같아요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +- [ ] 메뉴를 등록 할 수 있다
`src/main/resources/db/migration` 디렉터리의 .sql 파일을 보고 Menu 의 관계도 표현하면 좋을 것 같아요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +- [ ] 메뉴의 판매상태를 판매중단으로 변경할 수 있다
예외도 기능의 요구사항 중 하나일 것 같아요 :)
예외도 같이 표현해보면 어떨까요?

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +- [ ] 주문을 등록할 수 있다
유효성 검사를 좀 더 자세하게 적어보면 좋을 것 같아요~

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +### 주문 (Orders)
`Order` 와 다른 객체와의 관계도 같이 표현해보면 좋을 것 같네요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +    - [ ] 주문은 하나 이상의 메뉴를 포함하고 있어야 한다
`Menu` 인지 `OrderLineItem` 인지 표현을 명확하게 해보는것이 어떨까요?

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +    - [ ] 주문상태로 수락대기 -> 주문수락 -> 서빙완료 -> (배달중 -> 배달완료) -> 주문종결 중 하나를 선택 한다
주문을 등록할 때는 수락 대기 상태만 있는 것 같아요 :)
각 상태 값에 대한 표현은 주문을 등혹하는 부분 말고 각 행위마다 표현을 할 수 있을 것 같네요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +    - [ ] 변경 후 주문형태가 배달인 경우 배달 라이더를 요청한다
어떤 값들을 요청하는지 자세하게 표현하면 개발할 때 더 쉬울 것 같네요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
> +- [ ] 주문테이블을 등록할 수 있다
주문 테이블도 몇 번 테이블인지 이름을 지정할 수 있는데요
이를 위한 유효성 검사도 표현을 할 수 있으면 좋을 것 같네요

2022-03-06 12:30 UTC, liquidjoo commented on README.md
>  ## 용어 사전
용어 사전은 다음 수업때 진행을 하기 때문에 리뷰를 진행하지 않았습니다 :)

2022-03-07 09:13 UTC, mynameisdaun commented on README.md
> +    - [ ] 메뉴는 하나 이상의 상품으로 구성되어야 한다
@liquidjoo 
성주님 안녕하세요!
slack에서 테스트 방법론 관련해서 질문드린것과 유사한 것인데
한번 여쭙고자 합니다!

요구사항 문서를 현업도 함꼐 공유할 수 있을 만큼 비즈니스 친화적인 용어들로 작성하고 싶었고, 문서에 개발용어 사용이 얼만큼 용인될 수 있나 고민을 많이 하였습니다.

말씀해주신 MenuProduct 같은 경우
메뉴에 상품들을 맵핑 해놓은 테이블로서 실제 비즈니스에서는 거의
사용하지 않거나.. 메뉴상품구성(?)정도로 치환될 수 있겠다고 생각하였습니다.

요구사항 문서를 작성할때 아래 두문장을 상당히 많이 고민하다가
조금 더 비즈니스용어에 적합한 문장으로 표현하고 싶었던 것 같습니다..
(1) 주문은 하나 이상의 메뉴를 포함하고 있어야 한다.
(2) 주문은 하나 이상의 메뉴상품구성(?)을 포함하고 있어야 한다.

제가 년차가 오래 되지도 않았고, 같이 일하는 현업을 욕되이고 싶진 않으나 개발적인 용어로 요구사항 정의서를 받아본 경험이 없어서 이런 사고의 흐름으로 이어졌을 수도 있을것 같습니다..

요구사항 정의서에 개발용어를 사용하는 것에 대한 좋은 의견 부탁드려도 될까요?

2022-03-07 09:57 UTC, mynameisdaun commented
말씀해주신 요구사항들 반영하여 2차 PR 남깁니다!

감사합니다!

2022-03-08 13:18 UTC, liquidjoo approved these changes
2단계 미션 피드백 반영 잘하셨어요 👍 
몇 가지 코멘트 남겼어요 다음 단계에 같이 반영해보면 좋을 것 같아요
다음 단계 진행해 주세요~

2022-03-08 13:18 UTC, liquidjoo commented on README.md
> +    - [ ] 착석여부로 착석(sit), 공석(clear) 중 하나를 선택할 수 있다
착석일 때와 공석일 때를 구분해서 명세서를 더 나누어 볼 수 있을 것 같아요

2022-03-08 13:18 UTC, liquidjoo commented on README.md
> +- [ ] 주문상태를 주문수락 -> 서빙완료로 변경할 수 있다
조금 더 상세하게 주문수락인 경우만 서빙 완료로 변경할 수 있다
와 같이 표현해보는 것도 좋을 것 같아요~

2022-03-08 13:18 UTC, merged