[step2] 키친포스 요구사항 정리 입니다
next-step/ddd-legacy pull request #251
Opened 2022-03-09 17:56 UTC by YunNote

[step2] 키친포스 요구사항 정리 입니다

많이 늦었습니다 ㅠㅠ 

처음 작성해보다 보니 제 생각대로 작성하게된 부분들이 있을수 있을듯 합니다 .

항상 피드백 감사합니다!

2022-03-11 02:37 UTC, wotjd243 requested changes
꼼꼼하고 깔끔한 요구 사항 정리가 좋았습니다. 💯 
처음 보는 사람도 쉽게 읽을 수 있는 요구 사항으로 변경한다면 어떻게 변경할 수 있을까요?
그 외에도 몇 가지 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2022-03-11 02:37 UTC, wotjd243 commented on README.md
> +    - [ ] 메뉴 상품의 갯수와 상품의 갯수는 같아야한다.
"메뉴 상품의 개수와 상품의 개수는 같아야 한다."라는 요구 사항은 적절할까요?

2022-03-11 02:37 UTC, wotjd243 commented on README.md
> +    - [ ] 메뉴의 가격은 각 상품의 갯수의 합보다 크면 안된다.
"메뉴의 가격은 각 상품의 개수의 합보다 크면 안 된다."라는 요구 사항은 적절할까요?

2022-03-11 02:37 UTC, wotjd243 commented on README.md
> +    - [ ] 주문시 주문 메뉴에 포함되는 메뉴들을 조회 할 수 있어야 한다.
요구 사항의 초점이 구현 방식에 맞춰져 있어요. 처음 보는 사람도 쉽게 읽을 수 있는 요구 사항으로 변경한다면 어떻게 변경할 수 있을까요?

2022-03-12 07:27 UTC, YunNote commented on README.md
> +    - [ ] 메뉴 상품의 갯수와 상품의 갯수는 같아야한다.
`
if (products.size() != menuProductRequests.size()) {
    throw new IllegalArgumentException();
}
`
해당 내용에 대해서 수정하였습니다 . 

`요청한 상품정보가 존재하지 않으면 안된다.` 라고 표현 하였는데 해당  해당 요구사항은 적당할까요??

2022-03-13 09:48 UTC, wotjd243 approved these changes
피드백을 전부 잘 반영해 주셨습니다. 💯 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
원활한 3단계 진행을 위해 2단계는 빠르게 Merge 할게요.

2022-03-13 09:48 UTC, wotjd243 commented on README.md
> +    - [ ] 메뉴 상품의 갯수는 한개 이상이어야 한다.
"메뉴 상품의 갯수는 한개 이상이어야 한다."라는 요구 사항은 적절할까요? 아래의 코드를 참고해 주세요.

```java
final long quantity = menuProductRequest.getQuantity();
if (quantity < 0) {
    throw new IllegalArgumentException();
}
```

2022-03-13 09:48 UTC, wotjd243 commented on README.md
> +    - [ ] 메뉴 상품의 갯수는 한개 이상이어야 한다.
오타 발견!

```suggestion
    - [ ] 메뉴 상품의 개수는 한 개 이상이어야 한다.
```

2022-03-13 09:48 UTC, wotjd243 commented on README.md
> +        - [ ] 주문 테이블 ID를 기준으로 주문 테이블을 조회 가능.
아래 코멘트에 대해 고민해 봐요.
https://github.com/next-step/ddd-legacy/pull/251#discussion_r824339395

2022-03-13 09:48 UTC, wotjd243 commented on README.md
> +    - [ ] 주문 정보롤 전체 조회 할 수 있다.
오타 발견!

```suggestion
    - [ ] 주문 정보를 전체 조회할 수 있다.
```

2022-03-13 09:48 UTC, wotjd243 commented on README.md
> +- [ ] 주문 테이블이 공석아 아니라면 인원수의 변경이 가능하다.
오타 발견!

```suggestion
- [ ] 주문 테이블이 공석이 아니라면 인원수의 변경이 가능하다.
```

2022-03-13 09:48 UTC, wotjd243 commented on src/test/java/calculator/Number.java
> +        this.value = Integer.parseInt(value);
아래와 같은 주 생성자(primary constructor)를 만든 후에 자기 생성자 호출하는 `this()`를 사용하면 어떨까요?

```java
public Number(int value) {
    validate(value);
    this.value = value;
}
```

2022-03-13 09:48 UTC, merged

2022-03-13 11:49 UTC, YunNote commented on README.md
> +    - [ ] 메뉴 상품의 갯수는 한개 이상이어야 한다.
아 .. 메뉴 상품의 갯수라기보다는 , 요청한 메뉴상품의 갯수가 맞는것같습니다 ㅠ