[Step2] 2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #252
Opened 2022-03-10 12:57 UTC by hk0305

안녕하세요~!
늦어서 죄송합니다!
회사 업무가 바빠 어제도 출근을 하고... 이제야 올리네요ㅠㅠ
서비스 로직과 테이블을 보면서 최대한 요구 명세서를 작성했습니다!
잘 부탁드립니다! :)

2022-03-11 14:27 UTC, sihoony requested changes
미션 잘 수행하셨습니다. 👍 
몇가지 코멘트를 남겼으니 확인해주세요~ 😄 

즐거운 주말 되세요~ 😄 😸

2022-03-11 14:27 UTC, sihoony commented on README.md
>  ## 요구 사항
TIP

1. 요구 사항은 프로젝트의 참여자들이 함께한다의 관점에서 접근하면 좋을 것 같네요~^^ ( 개발, 기획, 사업, 디자이너 등등... )
2. 요구사항은 보다 자세하게, 다른 개발자가 요구사항에 적힌 내용으로만 개발을 할 수 있도록 적어주면 좋을 것 같아요

2022-03-11 14:27 UTC, sihoony commented on README.md
> +    - [ ] 메뉴명은 비속어를 사용할 수 없다.
비속어는 어떤 기능에 대한 조건일까요? 들여쓰기를 통해서 기능에 대한 조건으로 표시된다면, 가독성도 좋아질 것 같습니다 👍

2022-03-11 14:27 UTC, sihoony commented on README.md
> +    - [ ] 메뉴 가격은 상품목록으로 등록한 상품 가격의 총합보다 비싸다.
들여쓰기를 한다면~? 가독성이 좋아지겠죠~?
- [ ] xxxx xxxx
  - [ ]  xxxx xxxxxx

2022-03-11 14:27 UTC, sihoony commented on README.md
> +- 메뉴
기능에 따른 조건들이 있습니다. 확인 후 추가해봐요~^^
- 가격이나, 수량 정보도 있겠죠~?

2022-03-11 14:27 UTC, sihoony commented on README.md
> +- 상품
상품에는 기능별 조건들이 존재합니다.
자세히 적어봐요~

2022-03-11 14:27 UTC, sihoony commented on README.md
> +    - [ ] 등록한 상품의 가격을 변경할 수 있다.
어떤 가격으로 변경할 수 있을까요?

2022-03-11 14:27 UTC, sihoony commented on README.md
> +- 상품
상품명에는 어떤 조건으로 등록할 수 있을까요?

2022-03-11 14:27 UTC, sihoony commented on README.md
> +- 주문 테이블
들여쓰기를 통해 가독성을 높여봐요!!

2022-03-11 14:27 UTC, sihoony commented on README.md
> +    - [ ] 고객은 표시된 모든 메뉴를 주문할 수 있다.
주문에 필요한 조건들은 무엇이 있을까요?^^

2022-03-11 14:27 UTC, sihoony commented on README.md
>  ## 요구 사항
각 기능에 따른 조건들고 작성해보면 좋을 것 같습니다~^^

2022-03-12 10:24 UTC, hk0305 commented
피드백 감사합니다!

생각보다 프로젝트의 참여자들과 함께한다는 관점이 굉장히 어렵네요!
어떻게하면 쉬우면서 모두를 이해시키고 만족시킬 수 있을지 더 생각해보았습니다!
시훈님두 즐거운 주말 보내세요~: )
감사합니다😄

2022-03-15 08:44 UTC, sihoony approved these changes
피드백 반영 잘해주셨습니다. 👍 

다음 미션 진행해주세요. 💯 
오늘도 좋은 하루 되세요~^^

2022-03-15 08:44 UTC, merged

2022-03-15 08:45 UTC, sihoony commented
다음 미션을 진행하면서 부족한 부분이나 빠진부분이 있다면 조금씩 개선해 봐요!! 😄 
미션 잘 수행해 주셨고, 다음 미션 기대하겠습니다 👍