[Step3 테스트코드] mynameisdaun 3차 PR
next-step/ddd-legacy pull request #253
Opened 2022-03-10 14:33 UTC by mynameisdaun

테스트 코드 PR 남깁니다.

중점적으로 리뷰어 선생님께 코칭받고싶은점 

1. 테스트코드만 보고 얼마나 코드 흐름을 이해할 수 있는가?

2. given, when, then 단락에 맞게 mockito 메써드들이 사용되었는가?

3. 테스트코드 메써드 이름, 디스플레이 네임이 알맞게 명명되었는가?

4. 테스트 코드의 변수명이 적절한가?

리뷰어 선생님께 솔직한 의견 + 피드백 받고 싶습니다
감사합니다!

2022-03-11 09:31 UTC, liquidjoo requested changes
3단계 미션 잘 구현해주셨어요 👍 
몇 가지 코멘트 남겼어요
확인하고 다시 요청주세요 🙇

2022-03-11 09:31 UTC, liquidjoo commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +}
파일 마지막에 엔터(개행문자)를 넣어주세요!!
이유는 리뷰를 진행할 때 깃허브에서 경고메시지를 지우기 위함입니다.

좀 더 알고 싶으시면 재미삼아 아래의 링크를 보시는 것도 추천 드립니다.
[https://minz.dev/19](https://minz.dev/19)

Intellij 를 사용하실 경우엔
Preferences -> Editor -> General -> Ensure line feed at file end on save 를 체크해주시면
파일 저장 시 마지막에 개행문자를 자동으로 넣어줍니다!

2022-03-12 03:29 UTC, mynameisdaun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        verify(menuGroupRepository, times(1)).save(any(MenuGroup.class));
@liquidjoo 
성주님 
모킹한 클래스의 반환값이 아니어서,
assert로 확인 진행할 수 있는 것들은 전부 반영해보았습니다!

허나, 모킹한 클래스가 반환한 entity는 null로 반환되어 ㅠㅠ 
assert로 확인을 하지 못했습니다 ㅠㅠ 
혹시 어떻게 하면 반환값도 assert로 확인할 수 있을까요?

2022-03-12 03:29 UTC, mynameisdaun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +}
감사합니다 완료하였습니다!

2022-03-12 03:30 UTC, mynameisdaun commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        MenuGroup 등록할_메뉴그룹 = mock(MenuGroup.class);
@liquidjoo 
불필요하게 중복되는 given 코드가 사라지고..
테스트 코드 전체가 짧아져서 유지보수도 훨씬 좋은것 같습니다...

코드를 작성하면서 생각했던 고민들이 해결되는것같아서 정말 좋았습니다 감사합니다!
테스트 픽스쳐 코드를 작성한건 처음이라, ㅠㅠㅠ
컨벤션이 잘맞춰진건지 중점적으로 피드백 부탁드리고싶습니다! ㅎㅎ

2022-03-13 07:31 UTC, liquidjoo requested changes
피드백 반영 잘해주셨어요 😃 
코멘트 하나 남겼어요~ 확인하고 도전해 보아요!

2022-03-14 09:13 UTC, liquidjoo approved these changes
피드백 잘해주셨어요💯 
저의 많은 요구사항들을 다 적용해주셨네요
저의 리뷰가 도움이 되었으면 좋겠어요 🙏  
고생하셨습니다

2022-03-14 09:13 UTC, merged