1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #312
Opened 2022-08-24 16:57 UTC by bperhaps

안녕하세요 :)

이번 미션은 비즈니스적인 관점 보다는, 객체지향의 관점으로 코드를 작성해 봤습니다. (확장 가능성에 많은 의미를 두었습니다.)

평소에 생각하던, 객체지향 설계에 대해 완전히는 아니지만, 최대한 코드에 투영하기 위해 노력해 봤습니다.

좋은 이야기 많이 나눌 수 있으면 좋을 것 같습니다 잘 부탁 드립니다. !!!

2022-08-25 13:51 UTC, kyucumber requested changes
안녕하세요 🙇 

몇가지 코멘트 남겨두었으니 확인 부탁드려요.

2022-08-25 13:51 UTC, kyucumber commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.orElse(List.of(calculatorString));
이 메소드는 customDelimiter가 존재하는 경우 tokenize를 진행하고 없으면 `List<CalculatorString>`를 반환하는 것 같아요.

일단 제가 생각하는 이 메소드의 아쉬운 점은 아래와 같습니다.

- 메소드 이름에 커스텀 구분자가 없는 경우 `List<CalculatorString>`으로 변환된 결과가 반환되는 부분이 표현되지 않습니다.

물론 코드를 읽으면 개발자는 이해할 수 있지만 이름만으로 바로 이해할 수 없고 한번 더 코드를 보는 수고를 거쳐야 합니다.

- 커스텀 구분자가 없어 처리하지 못했는데 기존 타입과 다르게 List로 변환되면서 혼란을 주고 있습니다.

초기에 코드를 읽을 때 `List<CalculatorString>`은 토크나이징 결과라고 생각했는데 여기서 List로 변환되면서 `List<CalculatorString>`이 tokenizing 된 결과가 아니구나 하고 혼란을 느꼈던 것 같아요.

2022-08-25 13:51 UTC, kyucumber commented on src/main/java/calculator/src/CalculatorString.java
> +public class CalculatorString {
CalculatorString의 경우

- 토크나이징 전의 "1,2,3" 값도 담길 수 있음
- 토크나이징 된 결과인 "1", "2", "3"도 담길 수 있음

결과값을 담는다고 하면 PositiveNumber를 바로 쓰는게 복잡도가 더 적을 것 같다는 생각이 들어요.

그리고 토크나이징 된 결과가 담기는 경우 아래 메소드가 필요없어집니다.

- toEmptyStringIfNull
- createCustomDelimiter
- tokenizingBy

토크나이징 된 결과가 담기는 경우 불필요해지는 메소드가 많은데요, 이를 보았을 때 해당 클래스의 응집도가 떨어진다고 볼 수 있지 않을까요?

2022-08-25 13:51 UTC, kyucumber commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.collect(toUnmodifiableList());
만약 위에서 커스텀 구분자에 의해 토크나이징이 끝났다면 아래에서는 불필요한 연산을 한번 더 해주게 되겠네요.

극단적인 예시지만 초기 입력된 문자가 커스텀 구분자로 의해 100만개의 List로 구분된다고 하면 100만개의 문자에 대해 각각 tokenizingByTokenIndex이 수행되어 굉장히 비효율적인 처리가 일어났을 것 같아요.

2022-08-25 13:51 UTC, kyucumber commented on src/test/java/calculator/StringCalculatorTest.java
> +	@ValueSource(strings = {"1"})
ParameterizedTest를 잘 사용해서 꼼꼼하게 테스트를 작성해주셨네요 👍

2022-08-25 13:51 UTC, kyucumber commented on src/test/java/calculator/StringCalculatorTest.java
> +}
파일의 끝이 개행으로 끝나게 처리해주세요.

이는 협업 시 불필요한 file change를 야기하며, POSIX 표준에도 맞지 않습니다.

IDE에 파일 마지막에 개행을 추가하는 설정이 있을거에요~

2022-08-25 15:18 UTC, bperhaps commented on src/main/java/calculator/src/PositiveNumber.java
> +		if (this == o) {
포멧팅을 깜박했네요!! 감사합니다!

2022-08-25 15:18 UTC, bperhaps commented on src/main/java/calculator/src/PositiveNumber.java
> +			throw new RuntimeException();
아하..! 요구사항에서 RuntimeException을 발생하라고만 나와있어서 생각하지 못했네요..! 메시지를 넣어서 구현하도록 하겠습니다 감사합니다 :)

2022-08-25 15:57 UTC, bperhaps reviewed
안녕하세요 규님님 :) 리뷰 감사합니다!!
코드와 관련된 부분에 대해서, 단순히 리뷰를 반영하기 보다는 철학적 이야기를 나눠보고 싶어서 제 생각을 조금 더 자세히 적어봤습니다!

규남님의 생각을 조금 더 듣고싶습니다 이번 리뷰도 잘 부탁 드립니다  :)

2022-08-25 15:57 UTC, bperhaps commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.orElse(List.of(calculatorString));
메서드 이름으로 그 행위를 표현하는것에 대해서는 충분히 공감하는 편 입니다. 하지만 이런 로직의 경우는 저는 제너럴한 (예상할 수 있는) 로직이라 생각해여. 리스트를 반환하는 메서드에서, 반환 결과가 없다면 null대신 빈 배열을 반환하는 로직과 비슷한 결을 가지고 가는 로직이라 생각해요. 

개이적으로 이 메서드를 작성했을때는 String의 split()을 생각하면서 구현 했었어요. 
split()의 경우, 구분자가 "" 라도 결과값을 array로 반환하고 이정도는 어떤 값을 반환할 지 예상 가능하다고 생각하는데요,

이러한 부분에 대해서 리뷰어님은 어떻게 생각하는지 의견이 듣고싶어요!

2022-08-25 15:57 UTC, bperhaps commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.collect(toUnmodifiableList());
말씀해 주신대로 커스텀 구분자로 구분한 뒤, 기본 구분자를 이용해 한번 더 토크나이징을 해주는 로직이 존재합니다.

이 부분은 제가 생각한 요구사항을 만족하기 위함이기 때문에 성능상의 문제와는 별개라고 생각해요!

커스텀 구분자가 $ 라면 1$2,3 에 대한 토크나이징도 1 2 3 으로 이루어 져야 한다고 생각했거든요.
따라서, 커스텀으로 구분한 후에 토크나이징이 완료됐는지 알 수 없으므로 기본 구분자로 토크나이징 하는 로직을 진행하도록 로직을 작성했습니다.

2022-08-25 15:57 UTC, bperhaps commented on src/main/java/calculator/src/PositiveNumber.java
> +			throw new RuntimeException();
아하..! 요구사항에서 RuntimeException을 발생하라고만 나와있어서 생각하지 못했네요..! 메시지를 넣어서 구현하도록 하겠습니다 감사합니다 :)

2022-08-25 15:57 UTC, bperhaps commented on src/main/java/calculator/src/CalculatorString.java
> +public class CalculatorString {
>결과가 담길 때 불필요해지는 메소드가 많다면 해당 클래스의 응집도가 떨어진다고 볼 수 있지 않을까요?

응집도는 불필요한 메서드의 존재 여부 보다는, 상태를 컨트롤 하는 행위가 하나의 클래스에 얼마나 잘 모여있는가로 계산된다고 생각해요.
따라서 어느 시점의 상태(말씀하신 경우라면, 토크나이징이 더이상 필요하지 않은 상태)에서 사용되지 않는 메서드가 존재한다고 응집도가 떨어진다고 생각되진 않는데 어떻게 생각하시는지 궁금합니다!

>결과값을 담는다고 하면 PositiveNumber를 바로 쓰는게 복잡도가 더 적을 것 같다는 생각이 들어요.
이 클래스를 설계 했을때, calculator의 수행을 위해 사용되는 도메인 종속적인 String 과 관련된 책임을 줘야겠다고 생각했어요.

PositiveNumber를 바로 사용하기 위해서는, 결국 input으로 들어온 String에 대한, 여러 구분자를 통한 토크나이징이 어디선가 일어나고, 그 결과를 PositiveNumber로 만들어 주는 로직이 필요한데, 이런 로직이 존재한다면 그 로직이 존재하는 부분이 응집도를 떨어트리는 부분이라고 생각했어요. (비대한 서비스가 이런 로직이 존재함으로서 만들어진다고 생각하거든요. -> string이 split되는 순간, 서로 다른 책임을 가지는 N개의 객체가 생기는 건데 그들이 가져야 할 책임을 진행중인 로직이 가지고 감.)

그래서, String을 대표하는 vo를 생성하고, 스스로에게 책임을 부여해서 스스로가 스스로를 tokenizing하도록 하며 자신의 상태를 컨트롤 할 수 있도록 했습니다. 더이상 토크나이징 되지 않는 상태까지 쪼개는 로직은, 도메인의 영역이라기 보다는 로직의 흐름의 영역으로 봐서 그걸 관장할 수 있는 일급 컬렉션에 책임을 두었구요.

비즈니스적으로, 가시적으로 로직이 보이는게 중요한 경우라면 말씀하신대로 작성할 것 같은데, 객체지향의 관점에서는 잘 공감이 가지 않아서 리뷰어님의 의견을 한번 더 듣고 싶습니다!

> toEmptyStringIfNull
> createCustomDelimiter

상태를 컨트롤하는 ptivate 메서드인데 불필요한 메서드로 봐야하는지 잘 모르겠어요..!

2022-08-25 15:57 UTC, bperhaps commented on src/test/java/calculator/StringCalculatorTest.java
> +}
개인컴에다가 POSIX 설정 해놨는데 회사컴에 안해놨더니 이런 불상사가... ㅋㅋㅋㅋ 확인해주셔서 감사합니다~!

2022-08-26 09:49 UTC, kyucumber commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.orElse(List.of(calculatorString));
split을 예시로 들어주시니 어느정도 이해가 가네요 😄 

그러면 split 등의 키워드를 메소드에 포함시켜주셔도 좋을 것 같다는 생각이 드네요

2022-08-26 09:51 UTC, kyucumber reviewed
1

2022-08-26 09:51 UTC, kyucumber commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.orElse(List.of(calculatorString));
1

2022-08-26 10:08 UTC, kyucumber commented on src/main/java/calculator/src/CalculatorString.java
> +public class CalculatorString {
> 응집도는 불필요한 메서드의 존재 여부 보다는, 상태를 컨트롤 하는 행위가 하나의 클래스에 얼마나 잘 모여있는가로 계산된다고 생각해요.
> 따라서 어느 시점의 상태(말씀하신 경우라면, 토크나이징이 더이상 필요하지 않은 상태)에서 사용되지 않는 메서드가 존재한다고 응집> 도가 떨어진다고 생각되진 않는데 어떻게 생각하시는지 궁금합니다!

특정 상태에 따라 응집도가 낮다고 판단하긴 좀 무리가 있을수도 있겠네요.
저는 토크나이징 결과로 나온 데이터는 덧셈에만 활용되는데 불필요한 메소드가 존재하기 때문에 토크나이징 결과 데이터를 기준으로 응집도가 떨어진다는 생각이 들어서 코멘트를 남겼습니다.

응집도에 대한 부분을 별개로 치더라도 토크나이징 결과 데이터로 덧셈을 수행할 때 불필요한 정보가 많다고 생각했어요.
delimiter나 다른 메소드들은 단순 덧셈을 하는 행위를 할 떄는 필요가 없을 것 같거든요.

> PositiveNumber를 바로 사용하기 위해서는, 결국 input으로 들어온 String에 대한, 여러 구분자를 통한 토크나이징이 어디선가 일> 어나고, 그 결과를 PositiveNumber로 만들어 주는 로직이 필요한데, 이런 로직이 존재한다면 그 로직이 존재하는 부분이 응집도를 > 떨어트리는 부분이라고 생각했어요. (비대한 서비스가 이런 로직이 존재함으로서 만들어진다고 생각하거든요. -> string이 split되는 > 순간, 서로 다른 책임을 가지는 N개의 객체가 생기는 건데 그들이 가져야 할 책임을 진행중인 로직이 가지고 감.)

이 부분은 생각하시는 바를 제가 잘 이해하지 못했을 것 같은데요,
로직이 분리되었을 때 결합도가 올라가고 그에 따른 트레이드오프가 있을 것 같긴 하지만 로직이 분리됨으로 인해 응집도가 떨어진다고 말씀하신 부분은 제가 잘 이해하지 못한 것 같아요.

> toEmptyStringIfNull
> createCustomDelimiter
> 상태를 컨트롤하는 ptivate 메서드인데 불필요한 메서드로 봐야하는지 잘 모르겠어요..!

토크나이징 결과를 담는 경우 customDelimiter에 대한 부분을 가질 필요가 없다고 생각했습니다.
toEmptyStringIfNull은 구현에 따라 필요할수도 필요없을수도 있겠네요.

저랑 리뷰이분의 코딩 스타일이 좀 다를 수 있다고 생각해요, 정답이 있는 부분은 아니라서 참고만 해주시면 될 것 같습니다 😄

2022-08-26 10:09 UTC, kyucumber commented on src/main/java/calculator/src/delimiter/Delimiters.java
> +			.collect(toUnmodifiableList());
저는 커스텀 구분자랑 기본 구분자로 구분하는 부분을 별도로 보았어요~ 알겠습니다.

2022-08-26 10:10 UTC, kyucumber approved these changes
안녕하세요

남겨주신 코멘트에 대해 답변 남겨두었습니다~
다음 단계 진행을 위해 머지하도록 할게요!

추가로 궁금한 부분 있으시면 코멘트 혹은 메시지 남겨주세요.

2022-08-26 10:10 UTC, merged

2022-08-26 10:44 UTC, bperhaps commented on src/main/java/calculator/src/CalculatorString.java
> +public class CalculatorString {
저도 평소에 코딩할때는 규남님이 리뷰해주신 스타일로 코딩하곤 합니다, 아무래도 일이다 보니 제 철학을 그대로 코드에 투영시키기에는 무리가 있어서요 ㅎㅎ.
그러다 보니 이번 기회에 제 코딩 철학을 많이 투영해 보고, 리뷰어님과 이야기를 많이 나눠보고자 했던 부분이 컷습니다ㅎㅎ

제 의견을 좀 많이 주장 했음에도 상세히 답변주셔서 정말 감사합니다 !!! 많이 배워가요 ㅎㅎ!!

>로직이 분리됨으로 인해 응집도가 떨어진다고 말씀하신 부분은 제가 잘 이해하지 못한 것 같아요.

이 부분에 대해서 제 생각을 한번 말씀드려 보자면, 저는 입력으로 들어온 데이터(input)가 문제를 해결하기 위한 하나의 도메인으로 보였고, 이 도메인을 split으로 쪼개면 N의 또 다른 도메인들이 생기는거라고 보았어요.

그래서 `1, 2, 3` 이라는 인풋이 들어오면, 이 String을 하나의 도메인(CalculationString)으로 보고, 분리했을 때는 `1` `2` `3` 의 3개의 도메인으로 만들어진다는 생각을 가지고 있었습니다. 그리고 쪼개진 String들은 자기 자신의 책임을 가져가야 한다고 생각했구요.

그래서 만일 `1,2,3`을
```
// assume that using java17
var s1 = Arrays.stream("1,2:3".split(",")).toList() 
var s2 = splitString.stream().flatMap(v -> v.split(":").stream()).toList();
s2.stream().map(this::toPositiveNumber).toList()
....
```
이런식으로 처리한다면, 제가 도메인이라고 생각했던 데이터들에 대한 책임이 특정 클래스에 다 몰리게 된다고 생각했고, 이런 부분이 비대한 서비스와 비슷한 것 같다고 말씀드렸던 것이었습니다 :)