2단계 요구사항 정리
next-step/ddd-legacy pull request #319
Opened 2022-08-25 15:36 UTC by Ryu-JeongMoon

안녕하세요.
요구사항 정리 제출합니다.

2022-08-27 12:26 UTC, liquidjoo requested changes
2단계 요구사항 정말 정리 잘해주셨어요 👍 
몇 가지 코멘트 남겼어요~ 확인하고 다시 요청주세요 🙇

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +        - [ ] 이름은 비어있을 수 없다.
이름이 비어 있을 수 없다도 좋지만 조금은 어색한 문장이 될 수 도 있을 것 같아요!
이름이 빈 값이 될 수 없다. 아니면 이름의 값이 비어 있을 수 없다 정도로 표현해보면 더욱 좋을 것 같네요!

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +            - [ ] 비속어 검증은 무료 비속어 필터링 사이트인 `purgomalum.com`을 이용한다.
자세한 요구사항 정리 👍

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +        - [ ] 가격은 비어있을 수 없으며 `0원 이상`이어야 한다.
null 에 대한 정의를 요구사항으로 정리할 때 개발자가 아닌 다른 사람들도 이해하기 쉽게 표현해보는 것도 좋습니다!

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +- **메뉴**
`메뉴 이름을 변경할 수 있다` 처럼 메뉴 생성에 대한 정리도 해보면 좋을 것 같아요~

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +    - [ ] 진열 여부를 변경할 수 있다.
진열여부 (display, hide) 에서 예외가 발생할 수 있을 것 같은데요~ 좀 더 상세하게 요구사항을 적어보는 것은 어떨까요?

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +- **메뉴 그룹**
생성할 때에도 요구사항을 명확하게 적어보아요~

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +- **테이블**
생성할 때에도 요구사항을 명확하게 적어보아요~

2022-08-27 12:26 UTC, liquidjoo commented on README.md
> +- **주문**
생성할 때에도 요구사항을 명확하게 적어보아요~

2022-08-27 13:26 UTC, Ryu-JeongMoon commented on README.md
> +        - [ ] 이름은 비어있을 수 없다.
같은 의미를 갖더라도 더 명확한 표현을 할 수 있도록 신경 써야겠네요. 감사합니다.

2022-08-27 13:26 UTC, Ryu-JeongMoon commented on README.md
> +        - [ ] 가격은 비어있을 수 없으며 `0원 이상`이어야 한다.
제 기준으로 작성한 감이 없지 않아 있는 것 같습니다.
요구사항을 볼 다른 사람까지 꼭 고려해야 겠네요. 감사합니다.

2022-08-27 13:27 UTC, Ryu-JeongMoon commented on README.md
> +- **메뉴**
메뉴 생성 과정을 명확히 나타내지 않았네요.
수정하겠습니다. 감사합니다.

2022-08-27 13:29 UTC, Ryu-JeongMoon commented
피드백 반영하여 다시 제출합니다.
감사합니다.

2022-08-28 15:22 UTC, liquidjoo approved these changes
2단계 피드백 반영 너무 좋았어요 💯 
다음 단계 진행해 주세요 🙇

2022-08-28 15:22 UTC, liquidjoo commented on README.md
> +    - [ ] 메뉴를 등록할 수 있다.
무리한 요구사항 일 수도 있었는데 정말 잘 반영해주셔서 감사합니다 🙇

2022-08-28 15:22 UTC, liquidjoo commented on README.md
> +    - [ ] 주문을 등록할 수 있다.
자세한 요구사항 👍 
처음 보는 사람도 이해하기 편할 정도로 좋습니다!

2022-08-28 15:22 UTC, merged