🚀 1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #321
Opened 2022-08-25 17:39 UTC by benggrae

안녕하세요 민준님 😄 
본격적으로 진행하는 첫번째 미션이네요.

넥스트 스텝 다른 과정을 리마인드하면서 해당 미션을 진행했습니다.

거침없이 리뷰 부탁드립니다!

2022-08-26 11:42 UTC, starkim06 requested changes
안녕하세요!!

1단계 미션 요구사항에 맞게 잘 진행해주셧네요!!
간단한 코멘트 몇가지 남겨두었으니 확인 부탁드려요 =)

2022-08-26 11:42 UTC, starkim06 commented on src/test/java/calculator/CalculatorNumber.java
> +public class CalculatorNumber {
CalculatorNumber 라는 클래스명도 좋지만, 이 클래스는 양수를 표현하시기 위해서 만드신 클래스 같아요.
의도를 조금 더 잘 나타낼 수 있는 클래스명을 사용해보시는건 어떨까요?

2022-08-26 11:42 UTC, starkim06 commented on src/test/java/calculator/CalculatorNumber.java
> +public class CalculatorNumber {
이 클래스를 불변 객체로 만들어보시는건 어떨까요?
참고: https://tecoble.techcourse.co.kr/post/2020-05-18-immutable-object/

2022-08-26 11:42 UTC, starkim06 commented on src/test/java/calculator/CalculatorNumber.java
> +    private CalculatorNumber() {}
디폴트 생성자를 정의해주신 이유가 있을까요?

2022-08-26 11:42 UTC, starkim06 commented on src/test/java/calculator/StringTokenUtilsTest.java
> +    @ValueSource(strings = {"3,4", "3:4"})
파라미터가 사용되고 있지 않은것 같아요!

2022-08-27 09:54 UTC, benggrae commented on src/test/java/calculator/CalculatorNumberTest.java
> +    @DisplayName("계산할 숫자를 더한다")
테스트명의 의도를 들어내도록 지어보도록 하겠습니다.

2022-08-27 10:05 UTC, benggrae commented on src/test/java/calculator/CalculatorNumber.java
> +    private CalculatorNumber() {}
외부에서의 자체 생성을 안됨을 명시적으로 들어낼려고 작성했었는데 불필요한 생성자인것 같습니다

2022-08-27 10:30 UTC, benggrae commented on src/test/java/calculator/CalculatorNumber.java
> +public class CalculatorNumber {
합계를 담당하고 있어 불변객체로 만드는것 좋은 의견인것 같습니다!

2022-08-27 10:35 UTC, benggrae commented on src/test/java/calculator/StringTokenUtilsTest.java
> +    @ValueSource(strings = {"3,4", "3:4"})
이런..... 변경하겠습니다.

2022-08-27 11:32 UTC, starkim06 approved these changes
안녕하세요!!! 병희님!!

전체적으로 리팩토링 잘 진행해주셧네요!! 👍 
간단한 코멘트 몇가지 남겨두었어요!! 참고 부탁드려요!!

다음 단계 진행 부탁드립니다!!

2022-08-27 11:32 UTC, starkim06 commented on src/test/java/calculator/CalculatorNumberTest.java
> +    @DisplayName("계산할 숫자를 더한다")
`StringTokenUtilsTest` 의 테스트들도 비슷하게 변경해보셔도 좋을것 같아요 =)

2022-08-27 11:32 UTC, starkim06 commented on src/test/java/calculator/StringCalculator.java
> +        for (String stringNumber : StringTokenUtils.tokenizer(text)) {
for 문을 stream으로 변경해보시는것도 좋을것 같아요!

2022-08-27 11:33 UTC, merged