1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #325
Opened 2022-08-26 07:29 UTC by jeongjaeeom

안녕하세요!!
1단계 - 문자열 덧셈 계산기 구현 완료하여 PR 드립니다!

이번에도 리뷰 잘 부탁드릴께요 :)

조금 뜬금 없지만 궁금한 점이 있어 질문 남겨 보아요  😅 
DDD 엔티티와 JPA에서의 엔티티에 차이와 분리 이점 등에서 알 수 있을까요!

분리 하여 진행한다면,
DDD엔티티 <-> JPA엔티티 사이에 변환이 필요하여 JPA엔티티에 레이지 로딩 등에 장점을 활용하지 못 하지만
DDD엔티티 즉, 도메인 레이어는 순수한 POJO로 가져갈 수 있다는 장점이 있을거라고 생각됩니다.
그래서 레이어를 완전히 분리하는게 좋을지 아니면 도메인엔티티와 JPA엔티티를 혼합해서 사용해도 좋을지 질문 드립니다!

아니면 제가 이 과정을 통해서 배우게 되는 것일까요!!

현재 프로젝트를 설계하다보니 고민이 많이 되서 급하게 질문드려서 죄송합니다 😅

2022-08-26 10:14 UTC, sihoony requested changes
안녕하세요! 엄정재님.
이번 미션도 잘 수행해 주셨고, 몇가지 코멘트를 남겼으니 확인해주세요. 👍 

오늘도 좋은 하루 되세요! 😄 😄

2022-08-26 10:14 UTC, sihoony commented on src/test/java/calculate/StringCalculator.java
> +  private static final Pattern CUSTOM_DELIMITER_PATTERN = Pattern.compile("//(.)\n(.*)");
Pattern의 생성은 비용이 많이 들죠!
캐싱으로 진행은 👍 👍

2022-08-26 10:14 UTC, sihoony commented on src/test/java/calculate/StringCalculatorTest.java
> +}
파일 마지막에 newLine을 넣어보는건 어떨까요~?^^
설정도 추가할수 있습니다.

- https://jojoldu.tistory.com/673

2022-08-26 10:14 UTC, sihoony commented on src/test/java/calculate/StringCalculator.java
> +  }
숫자를 관리하는 일급객체가 있다면 어떨까요?
합산의 기능을 포함할 수 있겠네요. 

- https://jojoldu.tistory.com/412

2022-08-26 10:14 UTC, sihoony commented on src/test/java/calculate/PositiveNumber.java
> +    if (number < 1) {
매직넘버 보다는 의미를 부여하는건 어떨까요?

2022-08-26 10:15 UTC, sihoony commented
>

2022-08-26 10:15 UTC, closed without merging

2022-08-26 10:23 UTC, sihoony commented
> 안녕하세요!! 1단계 - 문자열 덧셈 계산기 구현 완료하여 PR 드립니다!
> 
> 이번에도 리뷰 잘 부탁드릴께요 :)
> 
> 조금 뜬금 없지만 궁금한 점이 있어 질문 남겨 보아요 😅 DDD 엔티티와 JPA에서의 엔티티에 차이와 분리 이점 등에서 알 수 있을까요!
> 
> 분리 하여 진행한다면, DDD엔티티 <-> JPA엔티티 사이에 변환이 필요하여 JPA엔티티에 레이지 로딩 등에 장점을 활용하지 못 하지만 DDD엔티티 즉, 도메인 레이어는 순수한 POJO로 가져갈 수 있다는 장점이 있을거라고 생각됩니다. 그래서 레이어를 완전히 분리하는게 좋을지 아니면 도메인엔티티와 JPA엔티티를 혼합해서 사용해도 좋을지 질문 드립니다!
> 
> 아니면 제가 이 과정을 통해서 배우게 되는 것일까요!!
> 
> 현재 프로젝트를 설계하다보니 고민이 많이 되서 급하게 질문드려서 죄송합니다 😅

안녕하세요! 문의 주신 내용에 대해서 답변 드립니다.
문의 주신 부분은 항상 고민하는 부분이고, 아키텍처에 따라서, 팀 스타일에 따라서 다를 것 같습니다.

- 우리는 Domain과 JPA Entity를 하나로 사용할꺼야.
- 우리는 Domain과 JPA Entity는 다르므로 분리할꺼야.

제 생각에는 이 모든 내용에 정답은 없지만 Trade-Off라고 생각합니다.
사용성의 편의냐? 추후 확장성에 대한 대비냐?로 보여집니다. ( 더 많은 의견이 있을 수 있습니다. )
또한, 진행되는 수업 내용 중에 위와 같은 내용이 언급될 것으로 예상합니다!^^

2022-08-27 05:53 UTC, jeongjaeeom commented on src/test/java/calculate/StringCalculatorTest.java
> +}
리뷰 감사합니다 이 부분 .editorconfig 추가하여 푸시하였습니다 :)

2022-08-27 05:53 UTC, jeongjaeeom commented on src/test/java/calculate/StringCalculator.java
> +  }
리뷰 감사합니다!
일급 컬렉션 공부했었는데 사용하지를 못 했네요 :)
개선해서 푸시 하였습니다!

2022-08-27 05:54 UTC, jeongjaeeom commented on src/test/java/calculate/PositiveNumber.java
> +    if (number < 1) {
리뷰 감사합니다 ㅎㅎ
제가 놓쳤네요 개선하여 푸시하였습니다!

2022-08-27 05:55 UTC, jeongjaeeom commented
안녕하세요!
2단계 가이드(https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step2.md)에 따라서
제 원격(origin) 브랜치에만 푸시 하였는데 변경내용 잘 받아보셨을까요~?
아니면 제가 따로 PR만든 후 리뷰요청해야할까요..?