🚀 1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #333
Opened 2022-08-27 12:46 UTC by lehdqlsl

안녕하세요 리뷰어님!

1단계 PR요청합니다. 잘부탁드려요!

2022-08-28 14:43 UTC, wkdchdaud123 requested changes
@lehdqlsl 안녕하세요
업무도 하시면서 미션 진행하시느라 정말 고생 하셨어요.

너무 깔끔한 구현과 작은 Commit 단위 덕분에 리뷰가 편했어요 👍 💯 
몇 가지 코멘트 남겼으니, 확인하고 다시 요청주시면 감사하겠습니다. 🙇

추가로 **커밋 메시지 컨벤션**은 **feat** 이외에도 **fix, refactor, bugfix**가 있으니 상황에 맞게 사용해주시면 좋을 것 같아요  🙇

2022-08-28 14:43 UTC, wkdchdaud123 commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
이쪽 접근제한자는 없어도 될 것 같아요 :)
![image](https://user-images.githubusercontent.com/26424535/187079202-74042b15-7412-4625-9646-5286858e4634.png)

2022-08-28 14:43 UTC, wkdchdaud123 commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
아래의 테스트 케이스가 필요할 것 같은데 의도하신 것이라면 이유를 알 수 있을까요?? :) 
**2. 숫자 하나를 문자열로 입력할 경우 해당 숫자를 반환한다.**

2022-08-28 14:43 UTC, wkdchdaud123 commented on src/test/java/calculator/CalculatorTest.java
> +}
파일 마지막은 개행문자를 넣어주세요 :)
리뷰를 진행할 때 깃허브에서 경고메시지를 지울 수 있습니다.
[참고](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

조금 더 궁금하시다면 [이쪽](https://velog.io/@doondoony/posix-eol)을 참고해주세요 :)

2022-08-28 14:43 UTC, wkdchdaud123 commented on src/test/java/calculator/Calculator.java
> +        Matcher matcher = Pattern.compile(CUSTOM_REGEX).matcher(input);
`Pattern.compile` 은 상수로 선언을 해두고 사용하는 것이 성능적인 측면으로 좋습니다. :)
[참고](https://velog.io/@minchoi/%EC%9E%90%EB%B0%94-%EC%A0%95%EA%B7%9C%EC%8B%9D-Pattern.matcher%EB%8A%94-%EC%83%81%EC%88%98%ED%99%94-%EC%8B%9C%ED%82%A4%EC%9E%90)

2022-08-28 14:43 UTC, wkdchdaud123 commented on src/test/java/calculator/Calculator.java
> +        int iValue = Integer.parseInt(value);
**iValue**라는  변수 보다는 독자 입장을 고려해서 유의미한 변수명으로 바꿔보는 것은 어떨까요?
(객체지향 생활 체조 원칙 규칙 5: 줄여 쓰지 않는다. (축약 금지))

2022-08-28 14:47 UTC, wkdchdaud123 commented on src/test/java/calculator/Calculator.java
> +public class Calculator {
이쪽 Class 이름을 보고 문자열 계산기라고 판단을 할 수가 있을까요? :) 
예를 들면, 처음 접하는 독자는 문자열 계산기, 숫자열 계산기 등 어떤 역할을 하는 Class인지 로직을 보고 판단해야 하거나 범용적인 Class라고 생각할 수 있지 않을 까 싶은데요.
어떻게 생각하시나요? :)

2022-08-29 12:51 UTC, lehdqlsl commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
아무래도 덧셈이다 보니, 해당 케이스에 대해서 고려하지 못한 것 같습니다!
input이 다양할 수 있으니, 해당 케이스도 추가해야될것 같네요!

2022-08-29 12:55 UTC, lehdqlsl commented on src/test/java/calculator/CalculatorTest.java
> +}
좋은 정보 감사합니다.

2022-08-29 13:00 UTC, lehdqlsl commented on src/test/java/calculator/Calculator.java
> +public class Calculator {
당연한 말씀입니다.  너무 생각없이 클래스명을 지었는데, 반성해야겠네요 ㅠㅠ

2022-08-29 14:19 UTC, wkdchdaud123 approved these changes
@lehdqlsl님

정말 빠르게 피드백 반영해주셨어요 👍 
말씀드리지 않은 부분까지 찾아서 리팩토링 하는 모습이 정말 멋지십니다. 💯 👍 

추가로 코멘트 드렸어요. 참고 부탁드릴게요 
고민해보고 다음 단계에서 적용해보시는 것도 좋을 것 같네요.🙇
다음 단계 진행 부탁 드립니다 :)

2022-08-29 14:19 UTC, wkdchdaud123 commented on src/test/java/calculator/StringCalculator.java
> +        String[] numbers = parseInput(input);
numbers는 객체지향 생활 체조 원칙의 일급 컬렉션으로 대체 해보시는 것도 다음에 적용해보시면 좋을 것 같아요.
[참고](https://jojoldu.tistory.com/412)

2022-08-29 14:19 UTC, merged