1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #344
Opened 2022-08-28 14:48 UTC by hyunju-seo

안녕하세요. 1단계 미션 바로 진행했습니다:)

2022-08-28 15:07 UTC, sihoony requested changes
이번 미션도 잘 진행해 주셨습니다. 👍 👍 
몇가지 코멘트를 남겼으니 확인 부탁드립니다.

즐거운 하루 되세요! 😄

2022-08-28 15:07 UTC, sihoony commented on src/test/java/calculator/source/StringCalculator.java
> +                .reduce(Number::plus)
일급객체를 활용해 보는건 어떨까요?
역할이 명확하게 분리될 것 같네요!!^^
- https://jojoldu.tistory.com/412

2022-08-28 15:07 UTC, sihoony commented on src/test/java/calculator/source/Number.java
> +    }
`StringCalculator`에서 코멘트드린 내용과 동일하게 일급객체를 활용한다면 합산의 기능이 분리가 되고, number와 일급객체의 역할이 명확해 지겠네요^^

2022-08-28 15:07 UTC, sihoony commented on src/test/java/calculator/test/NumberTest.java
> +    void 값은_음수가_아니다(String input) {
`@DisplayName` 사용해보는건 어떨까요~?^^

2022-08-30 13:08 UTC, hyunju-seo commented on src/test/java/calculator/source/splitter/RegexSplitter.java
> +        Matcher m = pattern.matcher(input);
네~ 그래서 생성자에서 Pattern.compile을 할당하도록 했는데요! 정규식을 외부에서 주입받을 수 있도록 이렇게 구현했습니다:)

2022-08-31 04:02 UTC, sihoony approved these changes
피드백 반영을 잘 해주셨습니다 👍 
다음 미션을 위해서 머지하겠습니다.

오늘도 좋은 하루 되세요! 😄

2022-08-31 04:02 UTC, merged