2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #346
Opened 2022-08-28 16:36 UTC by yunbchae

2단계 리뷰 요청드립니다~!

1단계 미션에서 꼼꼼하게 리뷰 주신 덕분에 더 많이 고민해 볼 수 있었던거 같아요 🙇🏻‍♂️ 

이번에도 잘 부탁드리겠습니다 😃

2022-08-29 01:36 UTC, seok-2-o requested changes
요구사항정리 잘 진행해주셨네요 :)

몇가지 생각할거리를 남겨드렸으니 확인해주시면 좋을 것 같아요.

일교차가 크네요. 건강 유의하시고 좋은하루 되시길 바라요.

2022-08-29 01:36 UTC, seok-2-o commented on README.md
> +      경우, `메뉴(Menu)` 노출 여부를 false 로 변경한다.
요구사항은 **어떤 이해 관계자**와 함께 보게 될까요?

2022-08-29 01:36 UTC, seok-2-o commented on README.md
> +#### Create
커맨드와 질의를 잘 분리해주셨네요 👍

2022-08-29 01:36 UTC, seok-2-o commented on README.md
> +### 주문 (Order)
주문의 상태전이는 해당 비지니스에서 매우 중요한 요소 일 것 같아요
각 주문별로 상태전이를 별도로 표현해주면 어떤가요?

2022-08-29 01:36 UTC, seok-2-o commented on README.md
> +        - [ ] `주문 아이템(OrderLineItem)`의 가격은 `메뉴(Menu)`의 가격과 동일하다.
`주문 아이템(OrderLineItem)`의 가격은 `메뉴(Menu)`의 가격과 동일하다. 
```
            if (menu.getPrice().compareTo(orderLineItemRequest.getPrice()) != 0) {
                throw new IllegalArgumentException();
            }
```
해당 코드로 나타내는 요구사항이 내용을 충분히 나타내고 있을까요?

2022-08-29 01:36 UTC, seok-2-o commented on README.md
> +- [ ] `주문(Order)`을 수락할 수 있다.
요구사항을 꼭 글로만 정리할 필요는 없다고 생각해요. 조금 더 명확하게 내용은 전달할 수 있는 방법은 없을까요?

2022-09-01 01:18 UTC, seok-2-o approved these changes
피드백 반영잘해주셨네요 :)
다음 미션진행중에도(테스트 작성) 변경되는 요구사항이 있다면 반영하는것을 잊지 않으면 좋을 것 같아요.
이어서 다음 미션진행해주세요.

2022-09-01 01:18 UTC, seok-2-o commented on README.md
> +<img src="order_state_diagram.png" width="50%"  alt="Order State Diagram"/>
이미지로 만들어서 훨씬 알아보기 좋아진것 같아요.

2022-09-01 01:18 UTC, merged

2022-09-01 02:40 UTC, seok-2-o commented on README.md
> +        - [ ] `주문 아이템(OrderLineItem)`의 가격은 `메뉴(Menu)`의 가격과 동일하다.
https://github.com/next-step/ddd-legacy/pull/346#discussion_r960140105
이거랑 유사한 피드백인데요. 요구사항은 사용자(엔드유저) 관점에서 작성한다고 생각하면
`등록된 메뉴의 가격가 주문시점의 가격이 다르면 주문할 수 없다.` 가 좋지 않을까요?

2022-09-01 02:57 UTC, yunbchae commented on README.md
> +        - [ ] `주문 아이템(OrderLineItem)`의 가격은 `메뉴(Menu)`의 가격과 동일하다.
아하! 좋은거 같아요 👍🏻 
사용자 관점에서 작성하니까 좀 더 잘 와닿는 느낌이네요 ㅎㅎ 감사합니다~!

2022-09-01 04:24 UTC, seok-2-o commented on README.md
> +      경우, `메뉴(Menu)` 노출 여부를 false 로 변경한다.
메뉴를 노출하지 않는다. 혹은 메뉴를 숨긴다는 어떤가요?