2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #355
Opened 2022-08-30 16:42 UTC by DominiQN

잘 부탁드립니다!

1단계에서 추가 리뷰해주신 피드백 반영해보았습니다!

2022-08-31 13:16 UTC, sah3122 requested changes
요구사항 정리 잘해주셨네요 👍 
요구사항은 프로젝트에 참여하는 모든 인원이 이해할수 있도록 정의하는것이 목표입니다.
몇가지 생각거리를 남겨두었는데, 확인 부탁드립니다 🙏

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +        - 할인은 인정하지만 할증은 인정하지 않는 모양
```suggestion
    - [ ] ***상품***의 가격을 바꿀 수 있다. 
        - ***상품***이 속한 ***메뉴***의 총 가격이 ***상품*** 가격의 합보다 커지면, 그 ***메뉴***는 보이지 않게 변경된다.
```
들여쓰기를 통하여 요구사항을 명시적으로 나타내보세요 😄 

`할인은 인정하지만 할증은 인정하지 않는 모양` 해당 문장은 어떤 대상을 위해 남겨두신것일까요 ? 
시스템 요구사항에 부합한지 고민해보세요 !

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +- ***상품***
상품 등록 요구사항이 빠져있는것 같아요 😄

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +- 모든 이름은 비어있으면 안 된다.
개인적으론 요구사항은 시스템의 기능을 정리해보는 과정이라고 생각해요. 
`모든 이름은 비어있으면 안 된다.` 라는 공통적인 요구사항은 추후에 용어사전이나, 모델링 과정에 포함되는것이 자연스러울거 같아요 😄

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +- ***메뉴그룹***
메뉴 그룹에 대한 모든 요구사항을 정리해보세요 😄

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +- ***메뉴***
상세한 요구사항 정리 👍 
개인적으론 하나의 큰 요구사항을 기준으로 세부적인 요구사항을 들여쓰기를 통해 나타내는것을 선호합니다 😄

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +(개별 엔티티를 조회하는 API가 없다...)
불필요한 문장인것 같아요 😄

2022-08-31 13:16 UTC, sah3122 commented on README.md
> +            - 즉, 아직 제공되지 않은 다른 `매장식사` 주문이 남아 있디면, 완료예정인 주문이 완료된다고 해서 해당 테이블을 비우지는 않는다.
몇몇 요구사항들이 직관적이지 않은것 같아요. 
```suggestion
        - [ ] `매장식사`***주문***일 때, ***매장테이블***을 비워짐 상태로 변경하고 손님 수를 0으로 설정한다.
            - 완료되지 않은 주문이 있는 경우 매장 테이블을 비워짐 상태로 변경하지 않는다.
```
위와 같이 직관적이고, 자연스러운 문장이 되도록 변경해보세요 😄

2022-08-31 13:46 UTC, DominiQN commented on README.md
> +        - https://www.purgomalum.com/service/containsprofanity
엇 비속어 목록 조회를 위 URL로 하길래 검색하다가 포함되었습니다 ㅠㅜ 삭제할게요!

2022-08-31 13:47 UTC, DominiQN commented on README.md
> +        - 할인은 인정하지만 할증은 인정하지 않는 모양
엇 ㅠㅜㅠㅜ 의식의 흐름대로 작성하던 것을 삭제하지 못했습니다 ㅠㅠ

2022-09-01 15:50 UTC, DominiQN commented on README.md
> +            - 즉, 아직 제공되지 않은 다른 `매장식사` 주문이 남아 있디면, 완료예정인 주문이 완료된다고 해서 해당 테이블을 비우지는 않는다.
저도 제안해주신 게 더 직관적으로 보여요! 감사합니다!

2022-09-01 16:32 UTC, DominiQN commented on README.md
> +- 모든 이름은 비어있으면 안 된다.
음 알겠습니다!

2022-09-01 16:32 UTC, DominiQN commented on README.md
> +- 모든 이름은 비어있으면 안 된다.
음 그렇군요! 이번 요구사항 정리에서는 제거하겠습니다!

2022-09-01 16:47 UTC, DominiQN commented on README.md
> +- ***메뉴***
다른 것들에 대한 요구사항도 이렇게 정리해보겠습니다!

2022-09-02 08:35 UTC, sah3122 commented on README.md
> +        - 종류별 특이사항
해당 정의는 제거해도 될것 같아요 😄

2022-09-02 08:37 UTC, merged