3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #358
Opened 2022-08-31 18:51 UTC by gmoon92

안녕하세요 동철님 😄
3단계 리뷰 요청드립니다!

Fixture 클래스를 생성해봤는데요.
처음엔 Immutable 클래스 상수를 고려했지만, 테스트 별로 Fixture 객체 상태가 변경되는 부분이 많아 불변 객체를 사용하는 건 아니라고 판단했습니다. @BeforeEach 메서드에서 인스턴스를 생성하도록 설계했습니다.

마지막으론 UnitTestCase 에선 자주 사용하는 단언문 메서드를 정의했는데 리뷰어님은 어떻게 생각하시는지 궁금합니다. 🤔

이번에도 잘 부탁드립니다!  😄

2022-09-01 13:59 UTC, sah3122 requested changes
테스트 코드 꼼꼼히 작성해주셨네요 👍 
깔끔한 구현이 인상적입니다 ㅎㅎ 
몇가지 생각거리 남겨두었는데 확인 부탁드려요 😄

2022-09-01 13:59 UTC, sah3122 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        @DisplayName("메뉴의 가격이 갖고 있는 상품 목록 가격의 합보다 크면 수정되지 않는다.")
```suggestion
        @DisplayName("메뉴의 가격이 갖고 있는 상품 목록 가격의 합보다 크면 노출할수 없다.")
```
테스트의도가 잘못된것 같아요 😄

2022-09-01 13:59 UTC, sah3122 commented on src/test/java/kitchenpos/test/UnitTestCase.java
> +public abstract class UnitTestCase {
개인적으로는 이와 같이 사용하는걸 선호하지는 않아요 ! 
얻을수 있는 장점이 크지 않다고 생각하기 때문이에요 ㅎㅎ 
만약 단언문 앞 뒤로 공통 로직이 들어간다면 의미가 있을것 같아요.

2022-09-01 13:59 UTC, sah3122 commented on src/test/java/kitchenpos/test/constant/MethodSource.java
> +    static Stream<Arguments> emptyList() {
@EmptySource 로 표현할수 있지 않을까요 ㅎㅎ

2022-09-01 13:59 UTC, sah3122 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        @Test
마찬가지로 조금더 다양한 케이스를 정의해보세요 😄

2022-09-01 15:03 UTC, gmoon92 commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            @NullSource
현재 빈 문자열은 Menu 생성 로직에서 검증하고 있지 않아서
`NullAndEmptySource` 대신 `NullSource` 를 사용했습니다 ! 😁

``` java
public class MenuService {
        @Transactional
        public Menu create(final Menu request) {
                 // ....
                if (Objects.isNull(name) || purgomalumClient.containsProfanity(name)) {
                   throw 예외       
                }
        }
}
```

2022-09-01 16:15 UTC, gmoon92 commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +        @Test
꼼꼼한 피드백 감사합니다!

-1 , 0, 1 임계 값 테스트 케이스 추가하겠습니다!😁

2022-09-01 16:30 UTC, gmoon92 commented on src/test/java/kitchenpos/test/UnitTestCase.java
> +public abstract class UnitTestCase {
제가 UnitTestCase 를 구성한 이유는 다음과 같습니다.

애플리케이션의 존재하는 모든 테스트 클래스에서 자바 테스트 라이브러리 (AssertJ 와 같은) 의존 관계를 제거하는 목적이었습니다.

가령 AssertJ 라이브러리를 제거하고 다른 테스트 라이브러리로 교체하는 경우 모든 애플리케이션에 테스트 클래스를 수정해주는 상황을 고려하여 앞서 상황이 일어날 경우 코드 수정을 최소화하기 위해 Wrapper 클래스를 정의했습니다.

또한 단언문 메서드를 제약하여 일관성 있는 테스트 코드 스타일로 작성될 수 있도록 의도했습니다.😀

혹시 이 부분에 대해 리뷰어님은 어떻게 생각하시나요 ??~🤔

2022-09-01 16:32 UTC, gmoon92 commented
동철님 늘 꼼꼼하게 피드백 해주셔서 감사합니다 !😊

피드백 주신 내용에 대해 재 생각을 나름대로 정리해서 작성했는데 
이부분들에 대해 어떻게 생각하시는지 피드백 부탁드리겠습니다!.

2022-09-03 08:09 UTC, sah3122 approved these changes
피드백 반영 잘해주셨네요 👍 
그동안 적지 않은 피드백 반영해주신다고 고생많으셨습니다 🙏 
남은 미션들도 끝까지 파이팅 하세요 !

2022-09-03 08:09 UTC, sah3122 commented on src/test/java/kitchenpos/test/testdouble/FakePurgomalumClient.java
> +public class FakePurgomalumClient extends PurgomalumClient {
Fake 객체 사용 좋네요 😄

2022-09-03 08:10 UTC, merged

2022-09-03 09:00 UTC, sah3122 commented on src/test/java/kitchenpos/test/UnitTestCase.java
> +public abstract class UnitTestCase {
Wrapper 클래스를 구현해주신 이유가 너무 좋네요 👍 
몇가지 제 생각을 남겨드리면 저는 현시점에 필요하지 않은 기능을 깊게 아이데이션 하는것을 즐겨하지 않아요. 특히 중요한 도메인이 아니라면 더욱 그러한거 같아요. 어느 순간 필요한 시점이 오더라도, 그 시점에 변경하는것을 즐겨합니다. 
https://github.com/codeanddonuts/hacker-laws-kr#yagni
관련된 내용이 있네요 ㅎㅎ 

`모든 테스트 클래스에서 자바 테스트 라이브러리 (AssertJ 와 같은) 의존 관계를 제거하는 목적` 일반적으로 사용하는 라이브러리와의 의존 관계를 없애는것이 반드시 필요한 작업인지 고민해보세요 ㅎㅎ 

`단언문 메서드를 제약하여 일관성 있는 테스트 코드 스타일로 작성` 이러한 결정은 개인이 하는것 보단 팀 또는 조직의 가이드를 따라야할것 같아요 😄