2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #365
Opened 2022-09-03 03:11 UTC by willing1026

재석님 안녕하세요!
코드를 보고 요구사항을 작성하다보니까 디테일한 부분까지 작성하게 되는것 같습니다.
어떻게보면 여러가지 구현방식 중 하나일 수 있는 부분까지 요구사항으로 작성하게 된 건 아닌가 싶습니다.
( validation 순서라던가, request validation 방식 등 )

어느정도까지 구체적으로 요구사항으로 작성하는게 좋을지 궁금합니다.
피드백 부탁드립니다. 감사합니다!

2022-09-03 05:55 UTC, seok-2-o requested changes
요구사항 정리 잘해주셨네요. 
요구사항의 독자를 생각해서 작성한다면 어떤 수준으로 작성하는 것이 좋을지 보일 것 같아요.
개인적으로 요구사항은 사용자 혹은 기획자가 이해할 수 있도록 작성하고 있어요.

관련하여 몇가지 코멘트 남겨놓았어요. 확인 부탁드릴게요.

2022-09-03 05:55 UTC, seok-2-o commented on README.md
> +  - 상품 : 식당에서 판매하는 요리 및 음료들을 의미한다. 상품이름과 가격정보로 나타낸다. (e.g. 후라이드치킨)
예시 표시해주는 것 너무 좋네요 👍

2022-09-03 05:55 UTC, seok-2-o commented on README.md
> +    - [ ] 상품ID는 고유한 UUID를 생성해서 사용한다.
요구사항이 엔드유저(사용자, 기획자) 관점에서 도출하는 것이라면
아이디 정책을 자세하게 알 필요가 있을까요?

2022-09-03 05:55 UTC, seok-2-o commented on README.md
> +    - [ ] 계산한 메뉴구성상품들의 총 합 금액과 사용자가 입력한 금액(Price)가 일치해야한다.
```java
       if (price.compareTo(sum) > 0) {
            throw new IllegalArgumentException();
        }
```

메뉴의 가격은 상품의 합의 가격보다 같거나 작아야 한다입니다.

예를들어 햄버거(2,000원) + 콜라 (1,000원) 을 세트로 메뉴를 구성한다면 3,000원 보다 할인된 가격으로 판매되어야 해요.

2022-09-03 05:55 UTC, seok-2-o commented on README.md
> +    - [ ] 계산한 메뉴구성상품들의 총 합 금액과 메뉴에 등록된 금액(price)가 같으면 노출처리한다.
상품의 가격이 인하되어 메뉴의 가격이 커질경우 메뉴를 미노출하는것이 아닌가요?

2022-09-03 05:55 UTC, seok-2-o commented on README.md
> +### 주문
각 주문별 흐름을 더 잘나타낼 수 있는 방법은 없을까요?
또한 각 주문별로 흐름이 다른데 각각 표현하는것은 어떤가요?

2022-09-03 05:55 UTC, seok-2-o commented on README.md
> +    - [ ] 사용중 여부는 false로 자동 등록한다.
요구사항이 엔드유저(사용자, 기획자) 관점에서 도출하는 것이라면 조금 더 범용적인 언어를 사용하는것은 어떤가요?

2022-09-05 13:24 UTC, willing1026 commented
피드백주신 내용 반영해봤습니다.
엔드유저 관점으로 변경했습니다.

2022-09-06 10:05 UTC, seok-2-o approved these changes
피드백 반영 잘해주셨네요 👍 
추가로 소소한 고민거리 하나 남겨놓았으니 확인부탁드릴께요.
이어서 다음 미션 진행해주세요.

2022-09-06 10:05 UTC, seok-2-o commented on README.md
> +    - [ ] 상품정보는 `상품명`, `가격`으로 구성한다.
`가격` 과 같이 반복적으로 사용되는 정의를 재사용하는것 좋네요 👍

2022-09-06 10:05 UTC, seok-2-o commented on README.md
> +### 주문
각 주문 상태의 흐름을 그림으로 나타내보는것은 어떤가요?

2022-09-06 10:05 UTC, merged