1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #367
Opened 2022-09-03 12:48 UTC by newvelop

문자열 덧셈 계산기 기능을 구현했습니다

1. input을 받고 빈문자열 체크
2. 빈문자열이 아닐경우 custom delimiter 추출후 기본 delimiter와 병합
3. 앞의 prefix 제거 후 올바른 input인지 체크
4. 더하기

2022-09-04 08:37 UTC, hyunssooo commented on src/test/java/calculator/StringCalculator.java
> +
계속 재사용할 목적이라면 필드에 존재하는 게 아니라 상수로 선언하는 것은 어떨까요?

```suggestion

public class StringCalculator {
    private static final List<String> delimiterList = List.of(",", ":");

```

또한, 네이밍을 복수형으로 변경해 보는 것은 어떨까요? 어떤 장점이 있을까요?? 
만약 List에서 Set으로 변경된다면 내부에서 사용하고 있는 부분을 모두 변경해야 하지 않을까요?

```suggestion

public class StringCalculator {
    private List<String> delimiters = List.of(",", ":");

```

2022-09-05 02:50 UTC, hyunssooo requested changes
안녕하세요, 현오님~ 
몇 가지 코멘트 남겼습니다. 확인 부탁드릴게요! 
언제든 편하게 코멘트나 DM 남겨주세요! 함께 고민해 보면 좋을 것 같아요!

2022-09-09 05:07 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +
넵 계속 재사용할 목적이라면 상수로 구현하는게 좋다고 판단되어 상수로 변경하였습니다.

변수명 관련해서는 조금 다른 의견이 있는데 list와 set 둘다 구분자를 중복으로 관리할 수 있다는 공통점은 있지만, set은 중복 허용을 하지 않고 list는 중복 허용을 하지 않습니다. 즉 delimiters로 이름을 변경하면 list로 변경하든 set으로 변경하든 이름을 변경하지 않아도 될거같지만, 애초에 컬렉션을 변경하는게 비즈니스 로직에 영향을 미칠 수 있기 때문에 함부로 변경을 해서는 안되고, 변경을 한다면 이름을 바꾸는것도 코드 전반적으로 확인해보며 쉽게 할 수 있을 거같습니다.

저는 복수를 변수명으로 가져가는 방향보다는, 변수명부터 set인지 list인지 명확히 가져가는 네이밍이 좋을거같습니다.

2022-09-09 05:09 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
해당 코드가 확실히 간단해지는거같습니다! 저는 풀어서 쓰는게 좀더 다른 사람이 보기 쉬운 코드라고 생각을 했는데 이와 같은방법은 생각하지 못했네요 ㄷㄷ 차후에 참고해서 해보겠습니다

2022-09-09 05:11 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +        List<String> customDelimiters = extractCustomDelimiter(text);
넵 확실히 복수형과 리스트를 혼합해서 사용하는 것보다는 통일해서 가져가는게 좋아보입니다. 해당부분 수정했고 이름도 풀어서 만들었습니다!

2022-09-09 05:13 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
넵 pattern 객체를 변수로 만들고, 없을때 초기화하게 했으며, 빈 컬렉션을 반환하게 수정했습니다.

2022-09-09 05:14 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
해당 부분은 사실 메소드 하나를 위해 클래스를 생성하는 부분이 과하다고 판단되어서 추가하지 않았는데 혹시 어떤 부분때문에 클래스로 빼는게 좋다고 판단되는지 말씀해주실수있을까요?

2022-09-10 02:28 UTC, hyunssooo requested changes
안녕하세요, 현오님! 
추가로 몇 가지 코멘트 남겼습니다 :) 
함께 고민해 보면 좋을 것 같아요! 
언제든 코멘트나 디엠으로 연락 주셔도 좋습니다! 
즐거운 추석 보내시길 바랄게요!

2022-09-10 02:28 UTC, hyunssooo commented on src/test/java/calculator/StringCalculator.java
> +        }
empty를 검사할 필요가 있을까요??

2022-09-10 02:40 UTC, hyunssooo commented on src/test/java/calculator/StringCalculator.java
> +    private static Pattern extractCustomDelimiterPattern;
추가적으로 네이밍 컨벤션을 확인해보시면 좋을 것 같아요 :) 
이번 과정에서는 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html) 를 원칙으로 하고 있습니다 :) 
https://edu.nextstep.camp/s/esIIFotx/ls/CZsmE37M

2022-09-10 03:36 UTC, hyunssooo commented on src/test/java/calculator/StringCalculator.java
> +        }
이 부분 때문에 테스트가 실패하는 것 같아요 :) 
기존 코드는 `null` 이 아닌 경우에만 두 컬렉션을 합쳐줬는데 현재는 비어있는 경우에만 합치고 있네요.

2022-09-10 03:41 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
굉장히 좋은 의견주신거같습니다. stream과 allMatch를 써서 해당 부분 수정했습니다

2022-09-10 03:41 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +        }
네네 저도 확인해봤는데 이부분때문에 실패했습니다. 제거하는 것으로 수정완료했습니다

2022-09-10 03:45 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
List.of가 성능상에 이점이 있다는걸 이번에 첨알았네요. 해당부분으로 수정했습니다~

2022-09-10 03:46 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
첫줄에 비어있을 경우 stream 자체가 실행되지 않을것으로 보이는데요 혹시 문제되는 부분이 있을까요?

2022-09-10 03:46 UTC, newvelop commented on src/test/java/calculator/StringCalculatorTest.java
> +
넵 언급하신대로 delimiter empty 체크하는 부분때문에 일어나고있습니다. 수정완료했습니다.

2022-09-10 03:50 UTC, hyunssooo commented on src/test/java/calculator/StringCalculator.java
> +    }
문제 되는 부분은 없습니다! 리스트가 비어있을 경우 `sum()` 한다면 0을 리턴 받을 수 있으니 if 문이 필요 없을 수도 있을 것 같아서요.
이 부분은 참고만 해주세요~

2022-09-10 03:52 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    private static Pattern extractCustomDelimiterPattern;
우선 private static final 로 delimiterSet을 만든 이유는 Set.of를 통해 만들었기 때문에 set의 원소 수정도 불가능하겠지만, set객체를 새로 할당하지 못하게 한 의도도 있습니다. 즉 수정이 필요한 경우는 스펙이 변경되어 기본 delimiter가 변경되었을 경우밖에 없으며 재배포하는 거말고는 수정하지 못하게 한다 라는 개념으로 사용하였고, private static으로 string을 설정한 이유는 현재 setter를 열어두지는 않았으나, custom 추출하는 부분이 변경될수도 있을 것이다 라는 판단하에 final을 달지 않긴했었습니다.

하지만 setter 를 열어두지 않았기 때문에 패턴 문자열도 final로 가는편이좋을거같아 해당부분 수정했습니다.

2022-09-10 03:57 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +            return customDelimiterList;
넵 최대한 주석을 사용하지 않게 방향을 잡도록하겠습니다. 다만 "커스텀 delimiter가 +나 *이 들어올경우 그대로 split을 안되게 작업을 해줘야하나 생략함" 이부분은 차후 놓칠수있는 스펙이라 판단되어 TODO 주석으로 변경하였습니다.

2022-09-10 03:59 UTC, newvelop commented on src/test/java/calculator/StringCalculator.java
> +    }
어떤 느낌인지 대강 감은 잡힙니다만, 아직 값객체라는 개념을 학습하지 않은시점이라 익숙하지 않은거같습니다 ㅎㅎ 해당부분은 학습후에 한번 다시 이 pr을 돌아보는 시간을 가져보겠습니다 :)

2022-09-10 06:53 UTC, hyunssooo approved these changes
안녕하세요, 현오님 :) 
다음 step 진행 부탁드릴게요~
명절 잘 보내세요!

2022-09-10 06:53 UTC, hyunssooo commented on src/test/java/calculator/StringCalculator.java
> +    }
`extractCustomDelimiterPattern` 은 static 으로 모든 인스턴스에서 공유하게 될 것 같아요. 
이 부분이 final이 없으니 재할당도 가능할 것 같은데 이 부분이 의도된 부분인지 확인해 보시면 좋을 것 같습니다 :)

2022-09-10 06:53 UTC, merged