3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #375
Opened 2022-09-05 15:07 UTC by Hyeon9mak

안녕하세요 시훈님~
3단계 미션 뼈빠지게 진행해보았습니다 😭 

도메인 엔티티들이 단순하게 구성되어 있어 단위 테스트는 생략하고,
요구사항에 맞춰 기대한 대로 동작하는지 확인하기 위한 통합 테스트로만 구성해보았습니다.
테스트를 작성하는 과정에서 '이건 비즈니스 적으로 정말 말이 안되는데?' 싶은 부분들은 조금 리팩터링하였고,
더 큰 규모의 리팩터링이 필요하거나, 기술적인 이슈로 리팩터링이 필요한 경우는 테스트 코드 작성을 생략하거나
검증을 다른 방법으로 우회했습니다.
(해당 내용들은 요구상에 체크박스를 체크하지 않았거나, TODO 주석을 남겨두었습니다.)

이번 리뷰도 잘 부탁드립니다 🙇‍♂️

2022-09-06 15:20 UTC, sihoony requested changes
이번 미션도 👍 👍 
몇가지 코멘트를 남겼으며, todo로 남기신 부분은 같이 이야기해보면 좋을 것 같습니다!

즐거운 하루 되세요 😄

2022-09-06 15:20 UTC, sihoony commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        }
어떤부분이 문제가 될까요~? DM을 남겨주시면 같이 고민해볼 수 있을것 같네요!

2022-09-06 15:20 UTC, sihoony commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        }
DM 주세요~^^

2022-09-11 03:11 UTC, Hyeon9mak commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +            MenuGroup request = MenuGroup("한마리");
아하, 픽스쳐를 가능하면 일반 객체의 생성자와 비슷하게 사용하고 싶었던 욕심인데요..
Method 로 묶어서 중복되는 내용을 회피한다면 중복코드는 줄어들겠지만,
결국 테스트 코드를 읽는 사람이 메서드 내부 동작까지 이해한 후 테스트를 읽어야한다는 단점이 생길거 같아 중복을 감수하고 노출시켰습니다.

2022-09-11 03:13 UTC, Hyeon9mak commented on src/main/java/kitchenpos/application/OrderService.java
>              }
공유주신 요구사항이 어떤 것인지요?!
우선 매장 주문은 수량이 음수가 되더라도 문제가 없다고 생각하고 원복하겠습니다. 🙇‍♂️

2022-09-11 06:27 UTC, Hyeon9mak commented
시훈님!

3단계 미션을 진행하면서 통합 테스트 코드 작성시, orderService.findAll 과 같은 부분에서 lazy-loading 관련 설정 문제를 마주칠 수 있었습니다.
위 설정을 변경하는건 큰 어려움이 아니지만, 가능하면 프로덕션 코드를 기술적으로 변경하지 않고 테스트 코드를 작성하는게 이번 미션의 주 목적이라고 생각해서 우선 테스트 코드를 작성하지 않고 다음 미션에서 리팩터링과 함꼐 테스트 코드 보완을 진행할 수 있도록 todo 를 남겼습니다.

혹시 이것 또한 수정해야되는 사항일까요?!

2022-09-12 12:34 UTC, sihoony commented on src/main/java/kitchenpos/application/OrderService.java
>              }
미션 설계시의 요구사항이라 리뷰이들에게는 공개되지 않는 내용이나, 미션 과정에서 왜 원복을 해야하는지에 대해 궁금해 하실까봐 남겼습니다~^^

2022-09-13 02:45 UTC, Hyeon9mak commented on src/main/java/kitchenpos/application/OrderService.java
>              }
아하! '공유주셨다' 멘트를 '기존에 공유주셨었다'로 이해했는데, 다시 읽어보니 방금 공유주신 내용에 대한 말씀이셨군요! 이해했습니다 👍

2022-09-13 03:38 UTC, sihoony approved these changes
3단계 미션도 잘 수행하셨습니다. 👍 
테스트코드 작성에 대해서 현구님이 생각하시는 바가 무엇인지 알 수 있어서 좋은 시간이 된 것 같습니다.
다음 미션을 위해서 머지 하겠습니다.

좋은 하루 되세요! 😄

2022-09-13 03:38 UTC, merged