1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #378
Opened 2022-09-05 17:21 UTC by chr0m3

1단계 문자열 덧셈 계산기 구현하였습니다.
감사합니다 👍

2022-09-06 14:38 UTC, kyucumber requested changes
안녕하세요

몇가지 코멘트 남겨두었으니 확인 부탁드립니다~

2022-09-06 14:38 UTC, kyucumber commented on src/main/java/string_calculator/string_parser/CustomDelimiterStringParser.java
> +        assert matcher.matches();
AssertionError가 날 것 같은데 어떤 사유로 예외가 발생한건지 알기 어려울 것 같아요.
조금 코드가 길어지겠지만 해당 경우가 어떤 케이스인지 조금 더 구체적으로 메시지를 아래처럼 남기면 어떨까요?

```java
if (!matcher.matches()) throw new IllegalArgumentException("~~");
```

2022-09-06 14:38 UTC, kyucumber commented on src/main/java/string_calculator/string_parser/SimpleStringParser.java
> +        return result;
Custom, Simple 두개의 구현체 모두 예외처리 부분이나 token을 List로 만드는 부분이 중복되고 있어요.

템플릿 메소드 패턴이나 혹은 다른 디자인 패턴을 사용해 이 부분을 개선해볼 수 있지 않을까요?

2022-09-06 14:38 UTC, kyucumber commented on src/main/java/string_calculator/string_parser/SimpleStringParser.java
> +        return result;
Stream의 map을 활용해볼 순 없을까요?

2022-09-06 14:38 UTC, kyucumber commented on src/test/java/string_calculator/string_parser/SimpleStringParserTest.java
> +        final List<Character> result = new ArrayList<>();
혹시 String이 아니라 Character를 사용하신 이유가 있을까요?

2022-09-06 14:38 UTC, kyucumber commented on src/test/java/string_calculator/string_parser/SimpleStringParserTest.java
> +    private static LongStream randomNonNegativeLong() {
methodSource에 활용되는 이 메소드들 보다는 테스트 내용이 더 중요할 것 같은데 static 메소드들을 아래로 내리는건 어떨까요?

2022-09-06 14:38 UTC, kyucumber commented on src/test/java/string_calculator/string_parser/SimpleStringParserTest.java
> +    }
ParameterizedTest를 잘 활용해주셨네요 👍

2022-09-06 14:38 UTC, kyucumber commented on src/main/java/string_calculator/ListCalculator.java
> +        return result;
Stream과 mapToDouble, sum이나 reduce를 활용해보면 어떨까요?

2022-09-06 14:42 UTC, chr0m3 commented on src/test/java/string_calculator/string_parser/SimpleStringParserTest.java
> +    private static LongStream randomNonNegativeLong() {
이 부분은 저도 평소 업무에서는 static method(또는 companion object)를 아래에 선언하는데 IntelliJ에서 reformat을 하는 경우 이렇게 정리해주어서 그대로 따랐습니다.

2022-09-06 14:50 UTC, chr0m3 commented on src/main/java/string_calculator/ListCalculator.java
> +        return result;
d5f06fdf229974a568e47f86724f280a9ea4e147
반영되었습니다

2022-09-06 14:50 UTC, chr0m3 commented on src/main/java/string_calculator/string_parser/SimpleStringParser.java
> +        return result;
d5f06fdf229974a568e47f86724f280a9ea4e147
반영되었습니다

2022-09-06 14:58 UTC, chr0m3 commented on src/test/java/string_calculator/string_parser/SimpleStringParserTest.java
> +    private static LongStream randomNonNegativeLong() {
제 경험상 대체로 static method를 아래에 두었던 것 같고, 그렇게 하는 것을 선호해서 코드 스타일 정렬 순서를 변경한 후 다시 reformat했습니다 3654218551d6eb9bee159af7a5a8be4a8aeb16eb

2022-09-06 15:00 UTC, chr0m3 commented on src/test/java/string_calculator/string_parser/SimpleStringParserTest.java
> +        final List<Character> result = new ArrayList<>();
각각의 원소가 "하나"의 문자라는 점을 타입으로 강제하고자 했습니다.

2022-09-07 22:25 UTC, chr0m3 commented on src/main/java/string_calculator/string_parser/SimpleStringParser.java
> +        return result;
9d292c041408dd4cd050adbbdacad57a76a9a758
반영되었습니다

2022-09-09 04:53 UTC, chr0m3 commented on src/main/java/string_calculator/string_parser/CustomDelimiterStringParser.java
> +        assert matcher.matches();
e779fc51a719c5a2767fc2de9d9858989c5281b7
반영되었습니다

2022-09-09 11:18 UTC, kyucumber approved these changes
피드백 잘 반영해주셨습니다.

다음 단계 진행을 위해 머지할게요

2022-09-09 11:18 UTC, kyucumber commented on src/main/java/string_calculator/string_parser/StringParser.java
> +    protected abstract String[] tokens(final String string);
중복이 잘 제거되었네요 👍

2022-09-09 11:18 UTC, merged