2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #383
Opened 2022-09-10 08:23 UTC by newvelop

요구사항 정리입니다.

즐거운 추석 보내시고 시간 되실때 봐주시면 감사하겠습니다 :)

2022-09-11 06:28 UTC, hyunssooo requested changes
안녕하세요, 현오님 🙂
요구 사항 잘 정리해 주셨어요! 몇 가지 코멘트 남겼습니다. 
궁금하시거나 함께 고민해 보고 싶은 부분이 있으시면 언제든 편하게 코멘트 혹은 DM 주세요! 
함께 고민해 보는 시간이 되었으면 해요!

2022-09-11 06:28 UTC, hyunssooo commented on README.md
> +- 주문 테이블 착석 : 주문 테이블이 존재할 경우, 주문 테이블 상태를 점유로 변경
`기능`이라는 단어는 어떤 기준으로 붙이나요?? 해당 단어가 필요할까라는 생각이 들었어요. :) 
사용하신다면 전체적으로 통일은 필요해 보입니다. 어떤 경우에는 기능이라는 단어가 붙고 어떤 경우는 안 붙어서요.

2022-09-11 06:28 UTC, hyunssooo commented on README.md
> +- 주문 테이블 조회 : 전체 테이블 정보 조회
전체적으로 depth 로 조건을 설명해주셨는데 `주문 테이블` 은 depth로 표현하지 않으셨네요?? 
다른 이유가 있을까요? 개인적으로 depth로 표현하는 것이 좀 더 명확해 보이긴 합니다!

2022-09-11 12:50 UTC, newvelop commented on README.md
> +  - 메뉴가 존재해야함
아무래도 코드 -> 요구사항 작성으로 역으로 하다보니 개발쪽인 측면이 좀더 가까워진거같습니다 + 요구사항은 아무래도 기획쪽의 영역이다보니 익숙하지가 않네요 ㅎㅎ true false 같은 부분은 제거해서 다듬어보겠습니다 ~

2022-09-11 12:55 UTC, newvelop commented on README.md
> +- 메뉴 그룹 조회 : 모든 메뉴 그룹을 조회하는 기능
해당 부분은 요구사항 정리하는 문장이라기보다는, 코드보다가 헷갈린 부분을 정리한거같습니다. 해당 부분을 요구사항으로 정리하고 맞게 구현하는 방향으로 수정하겠습니다.

2022-09-11 12:58 UTC, newvelop commented on README.md
> +- 상품 추가 : 새로운 상품을 추가하는 기능으로 상품의 이름이 없거나, 이미 존재하는 이름일 경우 추가 불가
비속어 체크하는 부분인줄 몰랐네요~ 요구사항에 포함하도록 수정하겠습니다

2022-09-11 13:02 UTC, newvelop commented on README.md
> +  - 메뉴의 가격이 항상 메뉴의 포함 상품 가격의 합보다 변경으로 인해 클 경우 메뉴를 표기하지 않는다.
용어 통일하고 해당 개념은 '전시'라는 단어로 변경해보겠습니다. 표시도 문맥에 맞는 단어라고 생각하나, 전시라는 단어도 나쁘지 않다고 생각해서 채택해봤습니다. 해당 부분은 의견주시면 감사하겠습니다 ㅎㅎ

2022-09-11 13:06 UTC, newvelop commented on README.md
> +  - 먹고 가기일 경우 테이블 정보가 존재해야하며, 테이블에 사람이 없어야함
문장을 조금 수정해서 주문의 타입이라는 점을 명시해보았습니다

ps. 먹고 가기라는 유형을 한단어로 처리하면 좋을거같은데 마땅한 단어가 떠오르지않네요...
혹시 생각나는 단어가 있으시면 추천 부탁드립니다

2022-09-11 13:10 UTC, newvelop commented on README.md
> +- 주문 테이블 조회 : 전체 테이블 정보 조회
주문 테이블을 작성할때 조건이 복잡하지 않아서 단순하게 작성을 해보았는데요, 통일성을 위해서 맞추는것도 좋아보입니다. 해당 부분 반영했습니다.

2022-09-11 13:11 UTC, newvelop commented on README.md
> +- 주문 테이블 착석 : 주문 테이블이 존재할 경우, 주문 테이블 상태를 점유로 변경
기능을 명세한다는 느낌으로 기능으로 문장을 끝냈는데 요구사항 명세다보니 그렇게 안해도 될거같네요. 기능으로 끝나는 요구사항을 전반적으로 서술어로 풀어보았습니다 ㅎㅎ

2022-09-11 13:12 UTC, newvelop commented on README.md
> +  - 주문 타입 정보 존재
주문 타입에 대한 명세 추가했습니다 :)

2022-09-11 13:17 UTC, newvelop commented on README.md
> +  - 같은 이름의 메뉴가 존재하지 않음
가격에 대한 명세 추가했고, 단순 숫자 보다는 단위를 추가했습니다~

2022-09-11 14:07 UTC, hyunssooo commented on README.md
> +  - 먹고 가기일 경우 테이블 정보가 존재해야하며, 테이블에 사람이 없어야함
저는 `배달`, `테이크아웃`, `매장 내 식사` 라고 했었네요!

2022-09-12 13:19 UTC, hyunssooo commented on README.md
> +  - 메뉴의 가격과 메뉴상품가격이 동일해야함
`메뉴 주문` 과 `메뉴`, `메뉴 상품` 은 어떤 점이 다른가요?? 
`메뉴에 대한 주문들` 이라는 설명이 조금 어색한 것 같아요. 코드로 보았을 때 `OrderLineItem` 일까요? 
`OrderLineItem`에 대한 명확한 설명이 있으면 좋을 것 같아요. `OrderLineItem` 은 여러 개의 `Menu` 로 구성되어 있습니다.

2022-09-12 13:30 UTC, hyunssooo commented on README.md
> +  - 메뉴의 가격이 항상 메뉴의 포함 상품 가격의 합보다 변경으로 인해 클 경우 메뉴를 전시하지 않는다.
전체적으로 마크다운 문법 중 체크 박스를 사용해 보는 것은 어떨까요?
다음 step인 테스트 코드를 작성할 때 유용할 것 같아요 :)

2022-09-17 11:02 UTC, newvelop commented on README.md
> +  - 주문의 타입이 '베딜'이어야 함
헉 이런 오타가 있었군요 전반적으로 확인한번하겠습니다.

2022-09-17 11:05 UTC, newvelop commented on README.md
> +  - 주문 테이블이 존재
넵 좀더 디테일하게 변경했습니다.

2022-09-17 11:07 UTC, newvelop commented on README.md
> +  - 주문 타입 정보 존재
매장 내 식사 란 단어가 정말 깔끔한 단어인거같습니다. 저도 사용을 해보겠습니다 :)

ps. 먹고 가 -> 먹고 가기 에서 커서 밑으로 내렸을때 글자가 짤리는 현상이 있어서 여기도 오타가... 수정하겠습니다

2022-09-17 11:35 UTC, newvelop commented on README.md
> +  - 메뉴 그룹의 이름은 중복될 수 없다.
넵 맞지 않는 요구사항 제거했습니다!

2022-09-17 11:41 UTC, newvelop commented on README.md
> +  - 메뉴의 가격과 메뉴상품가격이 동일해야함
앗 이경우는 메뉴 상품이 아니라 메뉴 주문이 맞습니다. 용어를 잘못사용했네요

메뉴 상품 같은 경우는 '메뉴를 구성하는 상품' 을 의미하고
메뉴 주문은 '주문에 포함된 메뉴' 를 의미합니다.

2022-09-17 11:52 UTC, newvelop commented on README.md
> +  - 메뉴의 가격이 항상 메뉴의 포함 상품 가격의 합보다 변경으로 인해 클 경우 메뉴를 전시하지 않는다.
넵 매우 좋은 의견 감사합니다!

기능별로 체크박스를 유지할까 고민했지만. tc에 검증 로직을 테스트했는지도 체크하고자 전체 라인 체크박스 추가해서 step3에 반영하겠습니다.

2022-09-18 14:29 UTC, hyunssooo approved these changes
안녕하세요, 현오님 :) 
요구 사항 정리하신다고 고생 많으셨습니다! 👍 
몇 가지 코멘트 남겼어요! 
다음 step 진행하시면서 확인 부탁드립니다!

2022-09-18 14:29 UTC, hyunssooo commented on README.md
> +  - [ ] 메뉴의 가격이 항상 메뉴의 포함 상품 가격의 합보다 변경으로 인해 클 경우 메뉴를 전시하지 않는다.
`메뉴의 가격이 항상 메뉴의 포함 상품 가격의 합보다 변경으로 인해 클 경우 메뉴를 전시하지 않는다.` 
이 문장은 읽기에 조금 어색하지 않나요? 🤔 한 문장이 맞을까요?  

```
메뉴의 가격이 항상 메뉴의 포함.
상품 가격의 합보다 변경으로 인해 클 경우 메뉴를 전시하지 않는다.
```
으로 보았는데 맞을까요? 각 문장도 조금 어색한 것 같아요.

요구 사항을 읽는 사람이 이해하지 못 한한다면 프로젝트를 시작하기 어려울 것이라고 생각해요.

2022-09-18 14:29 UTC, hyunssooo commented on README.md
> +  - [ ] 주문이 대기상태여야함
주문 유형은 `배송`이 아니라 `배달`으로 정의하셨네요! 전체적으로 확인해 보면 좋을 것 같습니다.
`주문 유형이 배달인 경우 배송 요청을 함` 이건 조건이니 depth로 표현되면 좋을 것 같아요 :)

2022-09-18 14:29 UTC, hyunssooo commented on README.md
> +  - [ ] 주문의 타입이 '배달'이어야함
`배송 완료`와 `배달` 두 용어를 사용하니 헷갈리는 것 같아요. 완료인 경우도 `배달 완료`로 통일해 보는 것은 어떨까요?

2022-09-18 14:29 UTC, hyunssooo commented on README.md
> +- [ ] 주문 조회 : 모든 주문을 조회할 수 있다.
이젠 `먹고가기`가 아니지 않을까요??

2022-09-18 14:29 UTC, hyunssooo commented on README.md
> +- [ ] 주문 조회 : 모든 주문을 조회할 수 있다.
`매장내 식사`인 경우 주문 테이블에 대한 변경이 있습니다. 이 경우도 depth로 표현해 보면 좋을 것 같아요 :)

2022-09-18 14:30 UTC, merged