Step1 : 문자열 덧셈 계산기
next-step/ddd-legacy pull request #433
Opened 2023-08-16 13:21 UTC by ryuhistory

안녕하세요. 이번 단계 리뷰이 유제형입니다.
앞으로 잘부탁드리겠습니다.
가감없이 많은 지도편달(?) 부탁드립니다. 😄 👍 

# Feature Request
- 기능 설명
  - 도메인구조  
    - StringCalculator - NumberForCalculator
    - StringCalculator - CalculatorDelimiter
  -  number, delimiter 도메인분리
  - delimiter를 기본 델리미터와, 커스텀 델리미터로 구분 
- 특이사항 
  -  StringCalculator 도메인을 생성자를 통한 text 할당 방식으로 변경
  -  기존 테스트코드에서 음수(-1) 검증 코드를, 생성자를 통한 방식으로 변경

2023-08-16 14:09 UTC, hyunssooo requested changes
안녕하세요, 제형님 :) 
몇 가지 코멘트 남겼어요. 시간 되실 때 확인 부탁드려요.
궁금하신 부분 있으면 DM이나 코멘트 남겨주세요!

2023-08-16 14:09 UTC, hyunssooo commented on src/main/java/calculator/NumberForCalculator.java
> +
CalculatorDelimiter, NumberForCalculator 클래스는 테스트가 필요해 보여요.

2023-08-17 09:47 UTC, ryuhistory commented on src/main/java/calculator/NumberForCalculator.java
> +
원시값을 포장함으로써 객체에게 역할을 일임할 수 있어서 책임의 분리가 확실해지겠네용!

2023-08-17 09:48 UTC, ryuhistory commented on src/main/java/calculator/Number.java
> +public class Number {
java.lang에 있는 Number와 동일해서 고민이 좀 되었지만
더 마땅한 대안이 떠오르진 않습니다ㅠㅠ

2023-08-17 09:52 UTC, ryuhistory reviewed
코멘트 주신 내용 많은 도움이 되었어용!

몇군대에 코멘트를 달아두었는데

수정하며 고민이 되었던사항이나 이유 등을 적어뒀습니당!

2023-08-17 09:52 UTC, ryuhistory commented on src/main/java/calculator/Number.java
> +    private final BigInteger value;
기존에는 int로 선언했었지만
값이 범위의 확장성을 위해서 BigInteger로 변경 하였습니다

2023-08-17 09:52 UTC, ryuhistory commented on src/main/java/calculator/Number.java
> +    }
기존 테스트 코드에서 int 값으로 검증하는 로직이 있어서
우선 두었지만
테스트코드에서 Number 객체로 변경하는 로직으로 변경하면 더 좋지 않을까 싶은 생각이 있어요

2023-08-17 09:52 UTC, ryuhistory commented on src/main/java/calculator/Splitter.java
> +public class Splitter {
기존에 StringDelimiter 라는 이름이었지만
실제 클래스의 역할을 보면 문자열을 분리하는게 주된 역할로 보여
Splitter로 변경하였습니당

2023-08-17 12:38 UTC, hyunssooo approved these changes
안녕하세요. 
가벼운 몇 가지 코멘트 남겼습니다.
다음 step 진행하시면서 참고 부탁드려요!

2023-08-17 12:38 UTC, hyunssooo commented on src/main/java/calculator/Number.java
> +public class Number {
저는 `PositiveNumber` 라고 작성했네요. :)

2023-08-17 12:38 UTC, hyunssooo commented on src/main/java/calculator/Number.java
> +    }
StringCalculatorTest 말씀이시죠? 
테스트코드에서 객체끼리 비교해도 좋을 것 같네요. 

```java
    @DisplayName(value = "빈 문자열 또는 null 값을 입력할 경우 0을 반환해야 한다.")
    @ParameterizedTest
    @NullAndEmptySource
    void emptyOrNull(final String text) {
        assertThat(calculator.add(text)).isEqualTo(PositiveNumber.ZERO);
    }
```

2023-08-17 12:38 UTC, hyunssooo commented on src/main/java/calculator/Number.java
> +    }
💯

2023-08-17 12:38 UTC, merged