요구 사항 정리
next-step/ddd-legacy pull request #439
Opened 2023-08-17 05:02 UTC by mytechnic

앞서 코드 리뷰에서 빠진 일급 컬렉션 적용 및 요구사항 정리 코드 리뷰 요청 드립니다.

2023-08-17 12:17 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 확인 부탁드려요. 
궁금하시거나 함께 고민하고 싶은 부분은 언제든 편하게 DM이나 코멘트 남겨주세요!  🙂

2023-08-17 12:18 UTC, hyunssooo commented on README.md
> +    - [ ] 방문식사(EAT_IN)의 경우 테이블 정보를 필수로 저장해야 합니다.
방문식사인 경우 테이블 상태에 대한 조건이 있는데요. 이 부분도 요구 사항에 포함되어야 하지 않을까요?

2023-08-17 14:33 UTC, mytechnic commented on src/main/java/calculator/PositiveNumber.java
> +
리뷰 의견 반영 하겠습니다.

2023-08-17 14:33 UTC, mytechnic commented on src/main/java/calculator/PositiveNumbers.java
> +public class PositiveNumbers {
리뷰 의견 반영 하겠습니다.

2023-08-17 14:35 UTC, mytechnic commented on src/main/java/calculator/PositiveNumbers.java
> +    }
제가 고민한 방식은 어떻게든 리턴 값을 돌려 주게 되는 것 같습니다.
조언 부탁 드립니다.

2023-08-17 14:35 UTC, mytechnic commented on src/main/java/calculator/PositiveNumbers.java
> +        }
리뷰 의견 반영 하겠습니다.

2023-08-17 14:41 UTC, hyunssooo commented on src/main/java/calculator/PositiveNumbers.java
> +    }
```java
    public PositiveNumber plus(PositiveNumber other) {
        return new PositiveNumber(this.number + other.number);
    }
```

이런 메서드가 존재하면 어떨까요?

2023-08-17 15:05 UTC, mytechnic commented on src/main/java/calculator/PositiveNumbers.java
> +    }
리턴 값을 PositiveNumber 타입으로 할 생각을 못 했네요. 좋은 방법인 것 같습니다.

2023-08-18 09:00 UTC, hyunssooo requested changes
안녕하세요.
추가로 몇 가지 코멘트 남겼습니다. 확인 부탁드려요.
궁금하시거나 함께 고민하고 싶은 부분은 언제든 편하게 DM이나 코멘트 남겨주세요! 🙂
그리고 정답이 있는 부분은 아니라서 봉운님 의견도 적극적으로 남겨주시면 더 좋을 것 같아요!

2023-08-18 09:00 UTC, hyunssooo commented on src/main/java/calculator/PositiveNumbers.java
> +public class PositiveNumbers {
PositiveNumbers 의 테스트는 없네요 ㅠㅠ

2023-08-18 09:00 UTC, hyunssooo commented on src/main/java/calculator/PositiveNumber.java
> +    }
이 메서드에 대한 테스트도 필요하지 않을까요? 

또한, 아래 테스트는 모두 통과해야 해요. 왜 모두 통과해야 할까요? 
https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/ 
이 글이 도움이 되면 좋을 것 같아요. 

```java
    @Test
    void test() {
        assertThat(new PositiveNumber(1)).isEqualTo(new PositiveNumber(1));
    }

    @Test
    void test1() {
        assertThat(new PositiveNumber(1).plus(new PositiveNumber(2))).isEqualTo(new PositiveNumber(3));
    }

    @Test
    void test2() {
        assertThatIllegalArgumentException().isThrownBy(() -> new PositiveNumber(-1));
    }
```

2023-08-18 09:00 UTC, hyunssooo commented on README.md
> +    - [ ] 등록된 상품을 조회할 수 있어야 합니다.
`가격` 이 `단가`로 변경되었네요! 
메뉴에서 사용하고 있는 `가격` 이랑 상품의 `단가`는 어떻게 다른가요?? 
나누신 이유도 궁금해요. 🙂
정답이 있는 것은 아니라 편하게 의견 말씀해 주시면 좋을 것 같습니다! ☺️

2023-08-18 09:00 UTC, hyunssooo commented on README.md
> +    - [ ] 등록된 상품을 조회할 수 있어야 합니다.
`메뉴에 등록 된 단가보다 낮게 변경하면, 전시 된 메뉴를 숨길 수 있어야 합니다.`

이 부분은 `숨길 수 있다` 선택적인 느낌을 받았아요. `숨겨진다.` 라는 표현은 어떨까요?

2023-08-18 09:00 UTC, hyunssooo commented on README.md
> +        - [ ] 메뉴 이름은 필수 항목이며, 비속어를 포함하지 않아야 합니다.
메뉴 등록에 전시 여부에 대한 조건이 누락된 것 같아요!

2023-08-18 09:00 UTC, hyunssooo commented on README.md
> +        - [ ] 메뉴 이름은 필수 항목이며, 비속어를 포함하지 않아야 합니다.
`MenuProduct` 에 대한 설명도 작성해 보는 것은 어떨까요? 
실제로 `Menu`는  n개의 `MenuProduct`로 이루어져있고 `Product`는 `Menu`가 아닌 `MenuProduct`에 속하는 것 같아서요. :) 

작성해주신 요구 사항을 보면 `Menu`에 `Product` 가 속하는 것 같은 설명이라고 느꼈어요.

2023-08-18 09:00 UTC, hyunssooo commented on README.md
> +        - [ ] 매장 내 식사일 경우 테이블을 이용 할 수 있는지 확인해야 합니다.
`매장 내에서 취식`, `매장 내 식사` 는 동일한 주문의 종류인데 다르게 표현되고 있어요. 
이 부분은 통일하는 것이 어떨까요?

2023-08-18 09:00 UTC, hyunssooo commented on README.md
> +    - [ ] 주문 정보 및 진행 상태를 조회할 수 있어야 합니다.
`상태를 확인 할 수 있어야 한다.`, `상태를 조회할 수 있어야 합니다.`
이건 모두 현재 상태를 확인(조회) 의 느낌을 받았는데요. 실제로 코드는 상태를 변경하고 있습니다. 
이 부분은 조금 더 명확하게 작성해 보는 것은 어떨까요?

2023-08-21 04:51 UTC, mytechnic commented on README.md
> +    - [ ] 등록된 상품을 조회할 수 있어야 합니다.
@hyunssooo 
1. 단가는 상품의 단위당 가격, 가격은 거래되는 메뉴의 가격을 의미로 사용했습니다.
2. 요구 사항의 전달 주체를 실무자로 생각했는데, "숨겨진다"라고 표현할려니 문장이 조금 어색해지는 측면이 있네요. 조금 더 고민해 보겠습니다.

2023-08-21 05:15 UTC, mytechnic commented on README.md
> +        - [ ] 메뉴 이름은 필수 항목이며, 비속어를 포함하지 않아야 합니다.
기획자와 개발자 중 어떤 시각으로 요구사항을 작성해야 할 지 고민이 생깁니다.
MenuProduct는 개발자가 구현의 목적으로 관계를 표현하기 위한 데이터라는 생각이 들어서요.

2023-08-21 05:17 UTC, mytechnic commented on README.md
> +        - [ ] 매장 내 식사일 경우 테이블을 이용 할 수 있는지 확인해야 합니다.
식사 하나로 통일하겠습니다.

2023-08-21 05:23 UTC, mytechnic commented on README.md
> +    - [ ] 주문 정보 및 진행 상태를 조회할 수 있어야 합니다.
위에서 "저장"이라는 단어가 개발자 관점이라는 의견이 있었는데, "변경" 또한 개발자 관점의 언어가 아닌가 의심했었습니다.
"~ 상태를 확인 할 수 있어야 한다." 를 "~ 상태로 변경 할 수 있어야 한다."로 변경하겠습니다.

2023-08-21 13:24 UTC, hyunssooo approved these changes
안녕하세요.
몇 가지 코멘트 남겼습니다. 다음 step 진행하시면서 참고 부탁드려요!
함께 고민하고 싶은 부분은 언제든 편하게 DM이나 코멘트 남겨주세요!

2023-08-21 13:24 UTC, hyunssooo commented on src/test/java/calculator/PositiveNumbersTest.java
> +    }
어떤 의도의 테스트일까요? 
`PositiveNumbers#size` 의 경우 테스트에서만 사용하고 있어서요.

2023-08-21 13:24 UTC, hyunssooo commented on src/main/java/calculator/PositiveNumber.java
> +    }
음수를 판단하는 것이 중복 아닐까요? String인 경우와 int 인 경우를 나눠야 할까요? 
부 생성자가 주 생성자를 이용하는 방향으로 변경해 보는 것은 어떨까요?

2023-08-21 13:24 UTC, hyunssooo commented on README.md
> +        - [ ] 상품의 이름은 필수 항목이며, 비속어를 포함하지 않아야 합니다.
https://github.com/next-step/ddd-legacy/pull/439#discussion_r1299596884

상품 등록은 하나만 등록하는 거라 가격이라고 작성해도 괜찮을 것 같아서요! 용어가 늘어나니 읽는 사람들에게 혼란을 주는게 아닐까 라는 생각이 드네요!

2023-08-21 13:24 UTC, hyunssooo commented on README.md
> +        - [ ] 메뉴에 등록 된 단가보다 낮게 변경하면, 전시 된 메뉴를 숨겨야 합니다.
```java
for (final Menu menu : menus) {
    BigDecimal sum = BigDecimal.ZERO;
    for (final MenuProduct menuProduct : menu.getMenuProducts()) {
        sum = menuProduct.getProduct()
            .getPrice()
            .multiply(BigDecimal.valueOf(menuProduct.getQuantity()));
    }
    if (menu.getPrice().compareTo(sum) > 0) {
        menu.setDisplayed(false);
    }
}
```

이 부분인데요. `메뉴에 등록 된 단가보다 낮게 변경` 라는 설명은 `메뉴는 등록된 상품 1개의 가격보다 낮다` 라는 의미 같아요. 하지만 코드는 `product.price * quantity` 로 보여요.

2023-08-21 13:24 UTC, hyunssooo commented on README.md
> +    - [ ] 테이블 정보를 조회할 수 있어야 합니다.
`테이블에 앉을 수 있다.` 요구 사항이 누락 된 것 같아요! 

`테이블이 사용 중인지 확인 할 수 있어야 합니다.` 이 부분은 코드상 어디일까요? 

`테이블의 상태를 초기화 할 수 있어야 합니다.` 
`초기화`라는 단어 조금 애매한 것 같은데요. 다른 직군이 조금 더 쉽게 받아들일 수 있는 단어는 없을까요?

2023-08-21 13:24 UTC, merged

2023-08-23 04:05 UTC, mytechnic commented on src/test/java/calculator/PositiveNumbersTest.java
> +    }
PositiveNumbers 클래스의 filter가 잘 동작하는지 확인하는 테스트에서 size 메소드가 필요했습니다.

2023-08-23 05:53 UTC, mytechnic commented on README.md
> +        - [ ] 메뉴에 등록 된 단가보다 낮게 변경하면, 전시 된 메뉴를 숨겨야 합니다.
product.price * quantity 로 계산되기는 하나,
메뉴의 상품 수량은 변하지 않으므로 상품 1개의 가격만 비교하더라도 동일한 목적을 가진 로직으로 생각했는데,
코드의 의도에 따르도록 요구 사항을 수정하겠습니다.

2023-08-23 05:55 UTC, mytechnic commented on README.md
> +    - [ ] 테이블 정보를 조회할 수 있어야 합니다.
"테이블이 사용 중인지 확인 할 수 있어야 합니다."가 "테이블에 앉을 수 있다"로 설명했는데 조금 더 직관적으로 수정하겠습니다.

2023-08-23 05:56 UTC, mytechnic commented on src/main/java/calculator/PositiveNumber.java
> +    }
PositiveNumber 클래스는 number 타입만 받도록 수정하겠습니다.