1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #446
Opened 2023-08-17 14:19 UTC by gzgzg2

안녕하세요 시훈님 ~! 1단계 미션 완료하여 PR 요청드립니다 :)

변수명, 클래스명, 코드 스타일을 중점으로 리뷰를 받고싶어요 😝
감사합니다 :)

2023-08-18 10:05 UTC, sihoony requested changes
안녕하세요!
미션 잘 진행해주셨습니다. 👍 
요청주신 내용은 특별히 코멘트가 필요 없을 정도로 잘 작성해주셨고, 그외 몇가지 내용에 대해서 남겼으니 확인해주세요~!^^

즐거운 주말되세요! 😄

2023-08-19 04:54 UTC, gzgzg2 commented on src/main/java/calculator/OperandParser.java
> +        Matcher matcher = Pattern.compile(CUSTOM_PATTERN).matcher(value);
의견 감사합니다 :) 객체를 미리 캐싱해두는 방안으로 수정해봐야겠군요!

2023-08-19 04:54 UTC, gzgzg2 commented on src/main/java/calculator/Operands.java
> +public class Operands {
값을 래핑해서 검증하는 책임을 부여하면 좋을 것 같네요 ! 감사합니다 :)

2023-08-19 04:56 UTC, gzgzg2 commented on src/main/java/calculator/OperandParser.java
> +    CUSTOM_PARSER(OperandParser::parseCustomPattern);
Class 활용해서 불필요한 접근을 막는 다는 것이 잘 떠오르지 않는데요.. 제가 이해한 것이 맞을까요?

- 파싱하는 행위를 문자열 계산기에 캡슐화하여 외부에서 메소드를 직접적으로 호출하지 못하게 하는 것

2023-08-19 06:43 UTC, gzgzg2 commented
> 안녕하세요! 미션 잘 진행해주셨습니다. 👍 요청주신 내용은 특별히 코멘트가 필요 없을 정도로 잘 작성해주셨고, 그외 몇가지 내용에 대해서 남겼으니 확인해주세요~!^^
> 
> 즐거운 주말되세요! 😄

의견 주신 내용 반영해서 푸쉬 하였어요 ~! 변경사항이 리뷰어님이 제시해주신 의견과 일치하는 지 궁금합니다 😝
좋은 주말 되세요 :)

2023-08-19 11:23 UTC, sihoony commented on src/main/java/calculator/OperandParser.java
> +    CUSTOM_PARSER(OperandParser::parseCustomPattern);
현재 OperandParser에서 외부에 오픈되어 사용되는 Method는 OperandParser.extractOperands 단일로 보여지는데, Enum을 사용하는 경우 OperandParser.BASIC_PARSER, OperandParser.CUSTOM_PARSER에 접근이 가능해서 불필요한 접근을 막고자 하는 의미로 리뷰를 드렸습니다. ^^

2023-08-19 11:32 UTC, sihoony approved these changes
피드백 잘 반영해 주셨습니다! 💯 
부족한 설명에 찰떡같이 반영해주셨네요 👍 👍 
다음 미션을 위해서 Merge하겠습니다. 즐거운 주말되세요~! 😄

2023-08-19 11:32 UTC, sihoony commented on src/main/java/calculator/OperandParser.java
> +    private static final String BASIC_PATTERN = "[,:]";
저의 부족한 설명을 찰떡같이 이해 하셨군요!!ㅎㅎ 👍 👍

2023-08-19 11:32 UTC, sihoony commented on src/main/java/calculator/Operand.java
> +public class Operand {
책임이 분리되면 이해하기 쉬운 코드가 만들어지고 테스트코드 작성이 쉬워지죠~! 👍 👍

2023-08-19 11:32 UTC, sihoony commented on src/main/java/calculator/Operand.java
> +        if (0 > value) {
매직넘버도 의미를 부여한다면 읽기 좋은 코드가 될 것 같네요~! 😄

2023-08-19 11:32 UTC, merged