2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #457
Opened 2023-08-18 09:18 UTC by sang5c

안녕하세요 리뷰어님!  

1단계에 남겨주신 리뷰를 포함해서 2단계를 진행했습니다.   
미션 진행하면서, 이전에 경험해봤던 이력과 요구사항을 알 수 없어 힘들게 수정한 코드들이 새록새록 떠오르네요 ㅎㅎ  

2단계도 리뷰 잘 부탁드립니다 🙇‍♂️

2023-08-18 17:12 UTC, wlroh requested changes
상오님 안녕하세요 :)
2단계 미션 고생하셨습니다.
몇가지 코멘트 남겼는데요~ 확인부탁드려요!

2023-08-21 04:51 UTC, sang5c commented on README.md
> +    - [ ] 메뉴 가격은 상품 가격 * 수량의 총합보다 작거나 같지 않으면 메뉴를 숨긴다(노출 중지)
아! 감사합니다 compareTo를 반대로 해석했군요 🥲

2023-08-21 06:58 UTC, sang5c commented
리뷰 주신내용 수정 완료했습니다. 감사합니다 구멍이 엄청많았네요 😱  
접수상태에서 서빙(매장 식사)과 배달이 갈린다고 오해하고 있었네요.  

현재 메뉴 등록 이외에, 가격 수정시 메뉴 가격 검사에는 메뉴에 포함된 상품*재고의 전체 합이 아닌 단일 상품*재고 가격과 비교를 하는 형태로 확인했습니다. (add를 하고있지 않습니다)
- 의도된 함정(?) 일까요? 아니면 별도의 요구사항이 존재하는걸까요?
이부분 같이 수정했는데 제대로 파악했는지 확인 부탁드립니다 🙏

2023-08-21 17:22 UTC, wlroh commented
상오님 안녕하세요 :)
> 의도된 함정(?) 일까요? 아니면 별도의 요구사항이 존재하는걸까요?    
> 이부분 같이 수정했는데 제대로 파악했는지 확인 부탁드립니다 🙏

이부분은 다음 미션을 진행하시면서 테스트 코드로 확인하신 뒤 작성한 요구사항에 맞게 수정해주시면 될 것 같아요 👍 

요구사항은 정리해주신
> - 상품 가격을 변경할 수 있다.   
>    - 메뉴 가격이 상품 가격 * 수량의 총합보다 크면 메뉴를 숨긴다(노출 중지, 클 수 없다)

가 맞아요 💯

2023-08-21 17:29 UTC, wlroh approved these changes
상오님 안녕하세요 :)
피드백 잘 반영해주셨습니다 👍 
간단한 코멘트 추가해놓은 것이 있는데요, 다음 미션 진행하시면서 확인 부탁드리고
다음 미션도 화이팅입니다 🔥

2023-08-21 17:29 UTC, merged