feat: step1 StringCalculator
next-step/ddd-legacy pull request #461
Opened 2023-08-18 18:09 UTC by jaejeong1

문자열 덧셈 계산기를 프로그래밍 규칙에 맞춰 구현하고, 테스트 통과를 확인했습니다.
리뷰부탁드립니다.

2023-08-19 10:36 UTC, oy-sihlee commented
커밋을 작은 단위로 나눈다면 구현한 기능이 무엇인지 명확하게 전달하고 진행할 수 있을 것 같아요. ( 실무에서는 어떤 기능을 만들었는지, 어떤 내용이였는지 쉽게 파악이 가능합니다. )

커밋 메시지도 지켜본다면 좋을 것 같아요. 이 커밋이 어떤 작업으로 인한 커밋인지 메시지만으로도 명확하게 알 수 있습니다! 😄 

- https://edu.nextstep.camp/s/HlFBeSln/ls/B1SwQCT0

2023-08-19 10:36 UTC, oy-sihlee requested changes
안녕하세요! 재정님,
1단계 미션 잘 수행해 주셨습니다. 👍 
코멘트를 남겼으니 확인 해주세요~!

2023-08-19 10:36 UTC, oy-sihlee commented on src/main/java/calculator/StringCalculator.java
> +public class StringCalculator {
역할을 나눠 보는건 어떨까요~!?
문자열에 대한 파싱을 담당하는 Parser와 숫자를 관리하는 VO 등등 역할과 책임을 분리해보면 더 좋은 설계가 될 것 같요~! 😄

2023-08-19 10:36 UTC, oy-sihlee commented on src/main/java/calculator/StringCalculator.java
> +        if (text.isEmpty()) {return 0;}
```suggestion
        if (text == null || text.isEmpty()) {return 0;}
```
간단하게 변경해 볼 수 있겠네요!

2023-08-19 10:36 UTC, oy-sihlee commented on src/main/java/calculator/StringCalculator.java
> +        if (text.isEmpty()) {return 0;}
0이라는 매직넘버에 의미를 부여해보면 좋을 것 같아요.

2023-08-19 10:36 UTC, oy-sihlee commented on src/main/java/calculator/StringCalculator.java
> +    }
패턴이 변경되지 않는 다면, 정적 멤버로 선언해 보는건 어떨까요~!?
생성자에서 초기화를 한다면, 객체가 생성될때마다 패턴 생성 비용이 발생이 됩니다.

2023-08-19 10:36 UTC, oy-sihlee commented on src/main/java/calculator/StringCalculator.java
> +        return sum;
일급컬렉션을 활용한다면 숫자 합산의 기능을 위임할 수 있겠네요~!
- https://jojoldu.tistory.com/412

2023-08-19 10:36 UTC, oy-sihlee commented on src/test/java/calculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
👍 👍

2023-08-19 14:57 UTC, jaejeong1 reviewed
피드백 반영

2023-08-19 14:58 UTC, jaejeong1 commented on src/main/java/calculator/StringCalculator.java
> +public class StringCalculator {
파싱 로직은 Parser로, 파싱 관련 상수는 MatcherGroup이라는 Enum 클래스로 역할과 책임을 분리했습니다!

2023-08-19 14:59 UTC, jaejeong1 commented on src/main/java/calculator/StringCalculator.java
> +        if (text.isEmpty()) {return 0;}
네, 말씀주신 대로 null, isEmpty 비교를 한줄로 합친 뒤, 해당 로직(기본값 0을 반환해야하는)을 메서드로 별도 분리하였습니다. 
0도 기본 반환값으로 상수 선언하였습니다.

2023-08-19 15:00 UTC, jaejeong1 commented on src/main/java/calculator/StringCalculator.java
> +    }
네, 해당 패턴은 StringCalculator 도메인 핵심이라 변경될 일이 드물 것으로 보여 정적 멤버로 선언하였습니다.

2023-08-19 15:06 UTC, jaejeong1 commented on src/main/java/calculator/StringCalculator.java
> +        return sum;
네, NumberTokens라는 일급컬렉션으로 tokens를 관리하고, 합이 필요할때 메서드 호출로 얻어올 수 있도록 변경했습니다!

2023-08-19 15:06 UTC, jaejeong1 reviewed
NumberTokens 일급컬렉션 분리

2023-08-20 13:20 UTC, sihoony requested changes
피드백 잘 반영해주셨습니다. 👍 
아쉬운 부분이 있어서 코멘트 추가 했으니 확인해주시고, 궁금하신 점은 DM으로 문의해주셔도 됩니다!
즐거운 하루 되세요~! 😄

2023-08-20 13:20 UTC, sihoony commented on src/main/java/calculator/NumberTokens.java
> +    }
Value Object를 만들어서 숫자에 대한 책임을 분리해보면 어떨까요~!?
일급 컬렉션은 vo에 대한 Collection으로 서로 다른 책임을 갖을 수 있을 것 같습니다~!^^

2023-08-20 13:20 UTC, sihoony commented on src/test/java/calculator/StringCalculatorTest.java
> +public class StringCalculatorTest {
책임을 분리하면서 만들어진 Parser, 일급 컬렉션에 대한 테스트코드도 추가해보는 건 어떨까요~!?

2023-08-21 12:26 UTC, jaejeong1 commented on src/main/java/calculator/NumberTokens.java
> +    }
PositiveNumber라는 VO를 만들고, PositiveNumbers라는 일급 컬렉션을 만들어 숫자에 대한 책임(음수 허용하지 않음, 합 계산)을 분리했습니다!

2023-08-22 03:37 UTC, sihoony approved these changes
피드백 잘 반영해주셨습니다. 👍 
다음 미션을 위해서 Merge하겠습니다
즐거운 하루 되세요~! 😄

2023-08-22 03:37 UTC, sihoony commented on src/test/java/calculator/PositiveNumbersTest.java
> +}
마지막 라인은 newLine으로 진행해봐요~!^^

- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
- https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2023-08-22 03:37 UTC, merged