2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #472
Opened 2023-08-19 14:53 UTC by cocahack

2단계 미션 진행하여 PR 생성했습니다! 

---

### 1 단계 미션 리팩토링

지난 1 단계 미션 (#434) 에서 제안해주신 두 가지 사항 적용했습니다!

1. 커스텀 문자열 매칭에 사용한 매직 넘버를 상수로 변경
2. `StringCalculatorParser` 테스트 케이스 추가

---

### 2 단계 미션 진행

2단계 미션은 구현된 내용을 기반으로 작성하였습니다.

엔티티가 가진 필드와 서비스 클래스에 노출된 인터페이스를 기반으로 각각 '속성' 과 'use-case' 로 나누어서 정리해봤습니다.
엔티티의 제약 조건을 (네이밍 규칙, 상품의 최소 가격 등등) 속성에 적어서, 'use-case' 에서 엔티티를 변경할 때 각 제약 조건을 또 다시 명시할 필요가 없도록 하기 위해 두 개의 분류를 사용했습니다.
리뷰하실 때 참고 부탁드립니다..! 🙇🏻‍♂️

2023-08-19 15:01 UTC, cocahack commented on src/test/java/calculator/StringCalculatorParserTest.java
> +}
파서의 테스트 케이스도 간단하게 추가했습니다.

---

테스트 성공 여부를 확인하려면 `PositiveIntegers` 의 내부를 살펴봐야 할 필요가 있었는데, 이전 커밋까진 이 클래스에 그런 기능이 없었습니다.

그래서 특정 위치의 값을 가져오는 `get()` 이라는 메소드를 만들어 테스트에 활용했습니다. 지금 당장은 테스트에 사용하기 위해 만들지만 나중에도 쓸 수 있는 범용적인 기능이라 나쁘지 않다고 생각했습니다. 😅

2023-08-20 23:20 UTC, serverwizard requested changes
2단계 미션 구현 잘해주셨습니다 👍

요구사항 정리 미션은 기존 레거시 시스템을 분석하는 과정이라고 생각해 주시고
간단한 코멘트 남겨 드렸으니, 이를 기반으로 다시 한번 정리해 보시면 좋을 것 같아요!

2023-08-20 23:20 UTC, serverwizard commented on README.md
> +    - [ ] 상품 가격이 변경되면 그 상품을 포함한 메뉴의 가격도 변경해야 한다.
아래와 같이 표현해 볼 수도 있을 것 같아요.
```
상품 가격이 변경되면 상품이 포함된 메뉴의 가격이 메뉴에 포함된 상품들의 총가격(단가 * 수량)보다 크다면 
해당 메뉴를 노출시키지 않는다.
```

2023-08-20 23:20 UTC, serverwizard commented on README.md
> +      - 메뉴 가격은 각 상품의 (상품 가격 * 수량) 의 합이어야 한다.
아래와 같이 표현해 볼 수도 있을 것 같아요! :)
```
- [ ] 메뉴 가격은 메뉴에 포함된 상품들의 총가격(단가 * 수량) 보다 작아야 한다.
```

2023-08-20 23:20 UTC, serverwizard commented on README.md
> +    - [ ] 주문은 타입, 상태, 주문 시간을 항상 가지고 있다.
아래와 같이 표현해 볼 수도 있을 것 같아요~
```
- [ ] 주문은 주문 유형, 상태, 주문 시간, 주문 품목들, 배송 주소, 주문 테이블 정보를 가진다.
    - [ ] 주문 유형은 총 세 가지다.
        - DELIVERY: 배달
        - TAKEOUT: 포장
        - EAT_IN: 매장 식사
    - [ ] 주문 상태는 총 여섯 가지다.
        - WAITING: 대기 중
        - ACCEPTED: 접수 완료
        - SERVED: 서빙 중
        - DELIVERING: 배달 중
        - DELIVERED: 배달 완료
        - COMPLETED: 완료됨
```

2023-08-20 23:20 UTC, serverwizard commented on README.md
> +      - [ ] 식당이 제공하지 않는 메뉴가 주문에 포함되어있지 않은지 확인한다.
아래와 같이 표현해 볼 수도 있을 것 같아요~
```
- [ ] 메뉴에 없는 항목은 주문할 수 없다.
```

2023-08-21 12:21 UTC, cocahack reviewed
리뷰해주신 내용 반영하고, 놓친 부분도 추가했습니다!

```
- 상품, 메뉴에서 잘못 이해한 가격 관련 정책 수정
- 주문 속성에 주문 타입과 주문 상태 기입
- 용어 변경
  - '홀' 용어를 '매장 식사' 로 대체
  - '서빙됨' 용어를 '서빙 중' 으로 변경
  - '수락됨' 용어를 '접수 완료' 로 변경
- 주문 생성에서 배달 포장 주문의 조건 추가
```

2023-08-21 12:21 UTC, cocahack commented on README.md
> +      해당 메뉴를 노출시키지 않는다.
제안해주신 내용 적용했습니다. 제가 상품과 메뉴 쪽 코드를 잘못 이해했었네요. 😭

2023-08-21 12:21 UTC, cocahack commented on README.md
> +      - [ ] 메뉴 가격은 메뉴에 포함된 상품들의 총가격(단가 * 수량) 보다 작아야 한다.
이 부분도 변경했습니다. 사실 버그라고 착각했었습니다... 리뷰해주신 내용을 보고 그제서야 비즈니스 로직을 이해할 수 있었네요.

2023-08-21 12:21 UTC, cocahack commented on README.md
> +        - 완료
유형과 상태도 추가했습니다. 👍 ENUM 값은 구현 상세라고 생각해서 적지 않았습니다.

2023-08-21 12:21 UTC, cocahack commented on README.md
> +      - [ ] 배달, 포장 주문은 메뉴의 수량이 0 이상이어야 한다.
이 조건도 제가 놓쳤길래 추가했습니다.
사실 보면서 어떤 요구 사항을 구현한 건지는 잘 와닿지 않네요.

2023-08-21 12:21 UTC, cocahack commented on README.md
> +      - [ ] 식당이 제공하지 않는 메뉴가 주문에 포함되어있지 않은지 확인한다.
훨씬 좋은 표현이네요! 감사합니다 🙇🏻‍♂️

2023-08-22 03:29 UTC, serverwizard approved these changes
안녕하세요 명철님, 피드백 빠르게 잘 반영해주셨네요! 
머지하도록 하겠습니다.

참고로, 간단한 코멘트 몇 개 남겨뒀으니, 다음 단계 진행하시기 전에 확인 한 번 부탁 드릴게요~
다음 단계에서 뵐게요.

2023-08-22 03:29 UTC, serverwizard commented on README.md
> +      - [ ] 배달, 포장 주문은 메뉴의 수량이 0 이상이어야 한다.
아래와 같이 표현해 보면 어떠신가요?
```
배달 또는 포장 주문인 경우에는, 주문한 품목의 수량이 반드시 0개 이상이어야 한다.
```

2023-08-22 03:29 UTC, serverwizard commented on src/test/java/calculator/StringCalculatorParserTest.java
> +class StringCalculatorParserTest {
테스트 코드 작성 👍

2023-08-22 03:29 UTC, serverwizard commented on README.md
> +- 주문
주문 내에서 `배달 주문`, `포장 주문`, `매장 주문`을 나눠서 요구사항을 정리해도 좋을 것 같아요! :)

2023-08-22 03:29 UTC, serverwizard commented on README.md
> +- 메뉴
MenuProduct(메뉴 구성 상품, 메뉴 포함 상품)에 대한 요구사항도 추가해주시면 좋을 것 같아요!

2023-08-22 03:29 UTC, merged

2023-08-22 12:28 UTC, cocahack commented on README.md
> +- 주문
요구사항을 나눠서 정리하면 제가 작성하고자 한 형식에서 벗어날 것 같습니다. 🥺

저는 추후에 모델링 단계에서 DB 테이블 다이어그램과 함께 상태 전이를 나타내는 다이어그램도 함께 그려서 
이 부분을 정리하려고 했었습니다..!

아직 구현을 하지 않은 상태에서 요구사항을 정리하는 중이라고 생각하면서 진행했기 때문이예요.

2023-08-22 12:31 UTC, cocahack commented on README.md
> +- 메뉴
`MenuProduct` , `OrderLineItem` 등은 두 개의 엔티티 간의 관계를 나타내는 엔티티로 해석했고, 이는 구현 상세라고 생각하여 일부러 적지 않았습니다!