Step3 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #481
Opened 2023-08-20 12:01 UTC by hiblue02

현구님! 리뷰 요청드립니다. 😄 

### 구현내용
 - 어플리케이션 레이어 테스트 코드 작성 (Mock(stub) 활용) 
 - 프레젠테이션 레이어 테스트 코드 작성 (RestAssured 활용) - 인수테스트 작성

### 질문
메뉴를 생성할 때는, 모든 메뉴구성상품 수량x가격의 합계보다 메뉴 가격이 작아야 하는데,
```java
for (final MenuProduct menuProductRequest : menuProductRequests) {
            final long quantity = menuProductRequest.getQuantity();
            if (quantity < 0) {
                throw new IllegalArgumentException();
            }
            final Product product = productRepository.findById(menuProductRequest.getProductId())
                .orElseThrow(NoSuchElementException::new);
            sum = sum.add(
                product.getPrice()
                    .multiply(BigDecimal.valueOf(quantity))
            );
            final MenuProduct menuProduct = new MenuProduct();
            menuProduct.setProduct(product);
            menuProduct.setQuantity(quantity);
            menuProducts.add(menuProduct);
        }
        if (price.compareTo(sum) > 0) {
            throw new IllegalArgumentException();
        }
``` 
반면에, 메뉴의 가격을 바꾸거나 메뉴를 보이도록 하는 부분에서는 가격이 메뉴구성상품별 수량x가격보다 클 수 없다는 검증 로직이 보입니다.
```java
        for (final MenuProduct menuProduct : menu.getMenuProducts()) {
            final BigDecimal sum = menuProduct.getProduct()
                .getPrice()
                .multiply(BigDecimal.valueOf(menuProduct.getQuantity()));
            if (menu.getPrice().compareTo(sum) > 0) {
                throw new IllegalStateException();
            }
        }
``` 

메뉴 가격을 검증하는 기준이 다른데, 가격을 바꿀때(메뉴 보이도록 할때) '메뉴구성상품별 수량x가격'과 비교해야 하는 이유가 있나요?
가격을 바꿀 때도 메뉴를 생성할 때처럼  '모든 메뉴구성상품 수량x가격의 합계'와 비교하는 것이 맞지 않을까해, 질문드려요. 😭

2023-08-22 01:42 UTC, Hyeon9mak requested changes
안녕하세요 혜영님, 3단계 고생하셨습니다.
탄탄한 인수테스트 + mock 테스트 작성이 인상적이에요.
몇 가지 사소한 코멘트와 함께, mock 테스트에 관한 질문을 남겼습니다.

질문주신 내용에 대해서 저도 헷갈려서 한참 쳐다봤네요 🤣 
레거시 프로젝트기 때문에 프로덕션 코드에 문제가 있을 수 있을 것이고,
단순히 기능에 맞춰진 테스트 코드가 아닌, 정책에 맞춰진 테스트 코드 작성으로
프로덕션 코드의 문제를 인지하고 올바르게 고쳐잡는 것까지가 미션의 일부인거 같습니다.

현재는 모든 테스트가 성공하는걸로 보이는데요, 
혜영님이 생각하시기에 올바른 방향으로 "테스트가 실패하도록" 변경하는 것도 좋아보입니다! 👍

2023-08-22 01:42 UTC, Hyeon9mak commented on README.md
> +- [x] 주문은 주문종류, 주문상태, 주문시각, 주문메뉴, 배달주소, 주문테이을 관리한다.
오타발견!
꼼꼼한 체크 좋습니다~

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/MenuAcceptanceTest.java
> +    private BigDecimal PRICE_2000= BigDecimal.valueOf(2000);
사용되지 않는 값이 보이네요!
상수처럼 활용되므로 static final 키워드를 붙여줄 수 있겠어요.

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/MenuAcceptanceTest.java
> +    }
테스트 코드 작성시에 반복되는 객체들에 넘버링을 붙이기 보다 개별로 이름을 붙이는걸 선호하는데요,
넘버링된 객체들이 반복되면 해당 테스트의 가독성이 쉽게 떨어진다고 생각하기 때문이에요.
혜영님은 어떻게 생각하시나요?

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/MenuAcceptanceTest.java
> +     */
주석으로 정리해주신 내용에 따라 private 메서드로 분리해봐도 좋을 것 같아요 😄 👍

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/OrderAcceptanceTest.java
> +    }
꼼꼼한 인수 테스트 검증 👍 
인수 테스트와 E2E 테스트의 차이는 무엇일까요? 🤔

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/steps/OrderSteps.java
> +    }
호출부를 별개로 분리해주셨기 때문에 테스트의 가독성이 올라갔군요 👍 
전체 API 들이 어떤 것들이 있는지 파악하기에도 용이한 것 같아요 👍 👍

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
mock 테스트는 의존을 없애기 여러운 대상 객체를 mocking 하고, 본래 테스트 하려는 객체의 '행위'를 테스트하는 기법이라고 생각해요.
`nameTest1` 과 같은 테스트는 경우 이름 검증이라는 '행위'를 테스트하고 있으므로 충분히 의미 있는 테스트지만,
`findAllTest1` 과 같은 테스트는 어떤 값이 주어질지 given 절에서 결정해주므로 큰 의미가 없는 테스트로 보여요. 🤔

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/fixture/MenuGroupFixture.java
> +    }
👍 👍 
공들여 만들어주신 픽스쳐 덕분에 추후 프로덕션 코드 리팩터링 시에도 테스트 코드 리팩터링이 용이하겠네요 👍 👍

2023-08-22 01:42 UTC, Hyeon9mak commented on src/test/java/kitchenpos/utils/DatabaseCleanup.java
> +
오! `InitializingBean` 빈을 이렇게 활용할 수도 있군요 👍 👍 
`@Service` 어노테이션을 사용하신 이유(기준)도 궁금합니다!

2023-08-22 12:44 UTC, hiblue02 commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +    }
서비스에 있는 기능은 모두 테스트해야 된다고 생각해서 만들었는데요. 
생각해보니... 큰 의미 없는 테스트네요! MenuAcceptanceTest에서 검증하고 있으니 삭제하겠습니다. 😄

2023-08-22 14:38 UTC, hiblue02 commented on src/test/java/kitchenpos/utils/DatabaseCleanup.java
> +
네! InitializingBean을 사용해서 인수테스트가 생성될 때마다 DB가 초기화되도록 했어요! 
`@Service`은 DatabseCleanUp 빈이 생성되어야 afterPropertiesSet 메소드가 실행되기 때문에, Bean으로 등록해주기 위해 붙였습니다. 서비스 레이어의 객체가 아니니, `@Component`가 나을 것 같네요. 💭 💭 💭

2023-08-23 09:54 UTC, Hyeon9mak approved these changes
안녕하세요 혜영님! 3단계 마지막까지 고생 많으셨습니다.
방대한 분량의 테스트 코드를 고퀄리티로 빠르게 작성해주셔서... 어떤 코멘트를 남길지 고민되네요 😵 
우선 approve 하고, 추가로 궁금하시거나 더 리팩터링하고 싶은 부분 있으시면 리뷰 진행하도록 하겠습니다.

2023-08-23 09:54 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/OrderAcceptanceTest.java
> +        return 매장주문을_생성한다(orderTableId, List.of(orderLineItem)).as(Order.class).getId();
테스트에 필요한 값을 만드는 과정이 하나의 문장으로 읽히는군요.. 👍 👍

2023-08-23 09:54 UTC, Hyeon9mak commented on src/test/java/kitchenpos/acceptance/OrderAcceptanceTest.java
> +    }
> 인수테스트는 비즈니스(시나리오)에 중점을 두고, E2E 테스트는 애플리케이션 통신 흐름(프론트엔드>백엔드>외부API)에 중점을 두는 방식인 것 같아요. 인수테스트가 기획자(?) 스타일이라면, E2E 테스트는 개발자 스타일(?) 이랄까요. 😄
>
> RestAssured로 작성한 인수테스트는 E2E 테스트 방식을 이용했다고 볼 수 있을 것 같아요. (controller>service>DB)
>
> 잘 이해했는지 모르겠네요. 😅
>
>
>참고문서 :
>[Unit vs Integration vs System vs E2E Testing - microsoft.github.io](https://microsoft.github.io/code-with-engineering-playbook/automated-testing/e2e-testing/testing-comparison/)

오 ms 에서 저런 정리를 해둔 문서도 있군요! 공유 감사합니다 🙇‍♂️ 

저도 비슷한 기준으로 범위가 객체 하나이건 시스템 전체이건 클라이언트가 원하는 시나리오대로 동작하는 테스트라면 인수 테스트,
범위가 객체 하나이건 시스템 전체이건 종단부터 종단까지 모든 기능을 통과하는 테스트를 E2E 테스트라고 생각하고 있습니다. 👍 
https://hyeon9mak.github.io/acceptance-test-vs-e2e-test/

2023-08-23 09:54 UTC, Hyeon9mak commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +
너무 당연한 것들에 대한 테스트가 사라지는 만큼, 다른 테스트들의 중요도가 부각된다는 장점도 있을 것 같아요.
테스트를 읽고 실행해보는 것 또한 리소스니까요!

2023-08-23 16:46 UTC, merged