step2
next-step/ddd-legacy pull request #487
Opened 2023-08-21 12:03 UTC by jordy-torvalds

2023-08-22 08:50 UTC, Hyeon9mak requested changes
안녕하세요 원식님! 2단계 요구사항 정리 잘 진행해주셨습니다!
용어사전 정의까지 미리 진행해주셨군요 😮 👍 
간단한 코멘트 남겼으니 확인해주세요.

2023-08-22 08:50 UTC, Hyeon9mak commented on README.md
> +  - [ ] 개수는 0 이하 일 수 없다.
적절한 용어로 대체해주신 덕분에 비개발직군도 충분히 읽고 요구사항을 파악할 수 있겠네요 👍

2023-08-22 08:50 UTC, Hyeon9mak commented on README.md
> +| 가격              | price           | 물건을 판매할 때 고객에게 요구하는 금액을 말합니다.                          |
용어사전 정의까지 함께 진행해주셨군요 😮 👍

2023-08-22 08:50 UTC, Hyeon9mak commented on README.md
> +      - [ ] 주문 테이블은 점유 여부에 따라 점유/비정유 상태를 가집니다.
코드에서 확인할 수 있는 몇 가지 제약사항이 누락된 것 같아요.
ex) 상품의 가격은 n원 이상이어야 한다.
다시 한번 API 와 코드를 확인해서 요구사항을 정리해보면 좋겠네요!

2023-08-22 08:52 UTC, jordy-torvalds commented on README.md
> +      - [ ] 주문 테이블은 점유 여부에 따라 점유/비정유 상태를 가집니다.
넵 다시 하나하나 찬찬히 읽고 보완해보겠습니다!

2023-08-22 08:53 UTC, jordy-torvalds commented on README.md
> +      - [ ] 주문 테이블은 점유 여부에 따라 점유/비정유 상태를 가집니다.
저 혹시 모델링 부분도 확인해주셨을까요?! 모델링에 요구사항의 일부 내용을 담아 놨는데, 해당 내용을 요구사항에도 동일하게 명시해야할까요?!

2023-08-22 08:53 UTC, jordy-torvalds commented on README.md
> +      - [ ] 주문 테이블은 점유 여부에 따라 점유/비정유 상태를 가집니다.
@Hyeon9mak

2023-08-26 18:46 UTC, Hyeon9mak requested changes
안녕하세요 원식님, 요구사항 정리 진행 고생하셨습니다! 👍 
이번 단계는 개발자 뿐만 아니라 비개발직군도 함께 보고 이해하고 대화할 수 있는 문서를 작성하는 과정으로 생각하고 있습니다. 작성해주신 모델링은 개발자를 위한 영역인 것 같아요. 
조금만 더 살펴보면 좋을 부분들이 보여서 코멘트 남겼습니다.

2023-08-26 18:46 UTC, Hyeon9mak commented on README.md
> +    - [ ] 이름은 null 일 수 없다.
비개발 직군은 null 이라는 표현을 알지 못할 가능성이 높을거 같아요 😱

2023-08-26 18:46 UTC, Hyeon9mak commented on README.md
> +  - [ ] 이름은 욕설과 비속어가 될 수 없다.
'~한다.' 와 '~합니다.' 라는 표현이 뒤섞여있는 것 같아요 😱

2023-08-26 18:46 UTC, Hyeon9mak commented on README.md
> +    - [ ] 이름은 욕설과 비속어가 될 수 없다.
메뉴 그룹이라는 표현보다 메뉴가 먼저 등장하기 때문에, 메뉴에 대한 설명을 읽다가 발견한 메뉴 그룹에 대해서 궁금증이 생길 수 있을 것 같아요. 대상을 설명하는 순서 또한 중요하게 고민해봐야할 포인트 같아요.

2023-08-26 18:46 UTC, Hyeon9mak commented on README.md
> +    - [ ] 주문의 상태는 다음과 같으며, 상태의 라이프사이클은 [주문 상태 다이어그램](#### 주문 상태 다이어그램)을 참조한다.
주문 종류 배달 / 매장식사 / 포장에 따라 각 상태들의 해석이 달라지는 것 같아요.
주문 종류별로 정리를 해보는 건 어떨까요?

2023-09-03 07:54 UTC, Hyeon9mak approved these changes
안녕하세요 원식님! 피드백 반영 잘 해주셨습니다.
요구사항을 정리하시면서 이상하다고 이야기 남겨주신 부분에 대해 답변 드렸으니 확인해주세요 😄 👍 
다음 단계에서 뵙겠습니다.

2023-09-03 07:54 UTC, Hyeon9mak commented on README.md
> +- 메뉴의 전시는 메뉴의 가격이 각각의 구성 상품에 가격 * 개수 보다 작거나 같을 때만 가능하다.("메뉴의 전시는 메뉴의 가격이 `sum(메뉴를 구성하는 상품의 가격 * 갯수)` 보다 작거나 같아야 한다."가 맞는거 같은데 좀 이상합니다..;)
> 주문이 매장 식사(EAT_IN)일 때만 주문품목이 0개 이하일 수 없다는게 좀 이상하다.

관례적으로 매장주문을 취소하거나 환불할 때는 기존 주문내역을 삭제하는게 아니라 음수 수량을 등록한다고 하네요.
기존 주문 기록을 한눈에 이해하기 위함 같습니다.
개발자가 단순히 개발만 하지 않고 비즈니스에 대해서도 공부해야하는 이유기도 하겠네요. 👍 

> 변경되는 가격은 각각의 구성 상품에 가격 * 개수 보다 작거나 같아야 한다.("변경되는 가격은 `sum(메뉴를 구성하는 상품의 가격 * 갯수)` 보다 작거나 같아야 한다."가 맞는거 같은데 좀 이상합니다..;)
> 메뉴의 전시는 메뉴의 가격이 각각의 구성 상품에 가격 * 개수 보다 작거나 같을 때만 가능하다.("메뉴의 전시는 메뉴의 가격이 `sum(메뉴를 구성하는 상품의 가격 * 갯수)` 보다 작거나 같아야 한다."가 맞는거 같은데 좀 이상합니다..;)

레거시 프로젝트기 때문에 요구사항과 다르게 코드가 잘못 작성되어있을 가능성이 존재합니다.
요구사항을 기준으로 잘못된 로직들을 파악하는 것도 레거시 개선의 과정이겠네요 👍

2023-09-03 07:54 UTC, merged