🚀 3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #496
Opened 2023-08-22 23:44 UTC by ryuhistory

안녕하세요. 기존 코드를 최대한 수정하지 않고
모든 Business Object에 대한 테스트 코드를 작성하려고 했습니다.

테스트코드만을 위한 비지니스코드를 추가하는것을  `지양` 하고자 했으나,
추후 도메인의 생성자 추가를 고려하기도 했으며, 어느정도 테스트코드의 깔끔함(?)을 위해 
몇몇 도메인은 생성자 코드를 추가 했습니다. 🙏 

리뷰 단위를 좀 최대한 작게 유지하는게 옳은 방법이긴하나...비지니스 오브젝트 테스트코드 라인커버리지 100%를 채우다보니
코드 양자체가 좀 많아지네요ㅠㅜ

원래는 인수테스트도 추가하여 리뷰요청을 할 계획이었으나, 한번에 리뷰하는 양이 많아지기도 하고
리뷰주기가 너무 늘어지는감이 있어 우선 1차 리뷰 먼저 올리겠습니다.

23,24일 이내로 인수테스트 추가하여 추가 리뷰 요청 올리도록 하겠습니다.
감사합니다.
<img width="716" alt="스크린샷 2023-08-23 오전 8 36 33" src="https://github.com/next-step/ddd-legacy/assets/52658495/c823e84e-8ecd-4ccc-8d47-9bb3c6238a6a">

2023-08-23 16:30 UTC, hyunssooo requested changes
안녕하세요. 
전체적으로 코드 잘 작성해 주셨어요! 
몇 가지 가벼운 코멘트 남겼습니다. 확인 부탁드려요! 
인수 테스트까지 작성하신다니 기대하고 있겠습니다. 🙂

2023-08-23 16:32 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        void negativeOfOrderLineQuantity(OrderType orderType) {
enum 도 ValueSource 로 바로 가능하네요! 
`@EnumSource` 도 존재하는데요. 같이 학습해 보아도 좋을 것 같아요!

2023-08-25 09:42 UTC, ryuhistory commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +                .isThrownBy(() -> menuService.create(돈가스_세트));
네 저도 그렇게 생각합니다. 테스트 코드양이 많아지다 보니 
테스트코드의 네이밍 컨벤션도 일정하지 않고 제각각이 되어서..이부분도 수저하겠습니다ㅠ

2023-08-25 13:06 UTC, ryuhistory commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        }
오 덕분에 jupiter params 좀 찾아봤습니다. 감사합니당

2023-08-25 13:23 UTC, ryuhistory commented on src/main/java/kitchenpos/domain/Menu.java
> +    }
🤔 오.. 
그러네요 entity의 id가 있다면 다른 값들을 비교 하는게 
큰 의미를 가지긴 어렵겠네요. 거기까지 미처 생각을 못했었는데 감사합니다

2023-08-26 12:34 UTC, hyunssooo approved these changes
안녕하세요. 🙂
이번 미션 진행하신다고 고생 많으셨어요! 
인수 테스트, `@Nested` 와 `@DisplayName` 테스트의 의미를 잘 나타내주신 부분이 인상 깊었어요. 
남은 미션도 잘 진행하시길 바랄게요!

2023-08-26 12:34 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +class OrderServiceTest {
전체적으로 코드 중복이 꽤 보이는 것 같아요. 
특히나 given 절이 꽤 길다고 느껴져요. 각 테스트마다 중복도 꽤 보이는 것 같습니다. 
Test Fixture를 사용해 중복을 제거하고 테스트 데이터를 만들기 위한 메서드를 만드는 등 다양한 시도를 해볼 수 있을 것 같아요. 
테스트 코드 또한 유지 보수 대상이기 때문에 깔끔하게 유지하는 것일 좋을 것 같아요.

이 부분을 좀 더 깔끔하게 정리해 볼 수 는 없을까요?

2023-08-26 12:34 UTC, merged