2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #497
Opened 2023-08-23 01:12 UTC by gzgzg2

시훈님 안녕하세요 ! 치킨포스 요구사항과 용어사전을 정리해보았습니다.

많이 어렵네요 😫 .. 그 중에서 테이블에 관련된 요구사항이 가장 어려웠던 것 같습니다. 
정리한 요구사항과 용어사전이 풍부하지 않다는 생각이 드는데요.. ! 어떤 점을 더 보완하면 좋을지 궁금해요 ~

이번에도 잘 부탁 드립니다. :)

2023-08-23 14:32 UTC, sihoony commented
요구사항만을 보고 개발을 해야된다고 생각하면 어떨까요~!?
불친절한 요구사항에는 여러번의 커뮤니케이션을 진행해야 되지만, 명확한 정책과 요구사항이 작성되어 있다면 커뮤니케이션 비용을 줄일 수 있겠죠~!?
코드와 Http파일을 보고 기능별로 어떤 요구사항이 존재하고 있는지 작성해보면 어떨까요~!?^^

2023-08-23 14:33 UTC, sihoony requested changes
안녕하세요~!
몇가지 코멘트와 궁금하신점에 대해서 답변을 남겼으니 확인해주세요~! 😄
즐거운 하루 되세요! 👍

2023-08-23 14:33 UTC, sihoony commented on README.md
>  ## 요구 사항
기능별로 그룹을 만들어보면 요구사항을 쉽게 파악할 수 있을 것 같아요~!
ex) 상품 등록, 수정, 조회, 주문 등록 ...

2023-08-26 07:35 UTC, gzgzg2 commented
[테이블/주문/상품/메뉴]의 요구사항을 더 추가해보았어요 ! 주문은 다른 도메인보다 요구사항이 많다고 느껴져서 카테고리 별로 분리하여 정리해보았습니다 :)

2023-08-26 09:00 UTC, sihoony approved these changes
피드백 잘 반영해 주셨습니다! 👍 
다음 미션을 위해서 Merge하겠습니다.
즐거운 주말되세요~! 😄

2023-08-26 09:01 UTC, merged