Step3 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #533
Opened 2023-08-29 13:35 UTC by ohgillwhan

잘 부탁드립니다.

2023-08-30 11:19 UTC, hyunssooo requested changes
안녕하세요. 길환님 🙂
테스트 코드도 잘 작성해 주셨어요! 
몇 가지 가벼운 코멘트 남겼는데 확인 부탁드립니다! 
다음 요청에는 머지하도록 하겠습니다.

2023-08-30 11:19 UTC, hyunssooo commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +import static kitchenpos.fixture.MenuProductFixture.createMenuProductWithDefaultId;
사용하지 않는 import는 제거해도 괜찮을 것 같아요!

2023-08-31 14:03 UTC, ohgillwhan commented on src/test/java/kitchenpos/domain/MenuGroupTest.java
> +    }
사실 2 가지의 이유가 있었습니다
1. 현재는 생성자가 무의미 하지만, 추후 리팩터링을 통해 생성자가 추가 되었을 때 파라미터로 넘겨진 생성자가 값이 잘 적용되어 있는지 체크하기 위함 (setter가 사라지겠네요.)
2. setter나 getter가 다른 개발자로 부터 오염되는것을 방지하기 위함.

1번의 경우 파라미터가 정상적으로 객체의 변수에 잘 담기면 좋겠지만, 어떠한 계산식을 통해 변경될 수도 있기 때문에 준비해봤습니다.

2023-08-31 14:10 UTC, ohgillwhan commented on src/test/java/kitchenpos/support/BaseServiceTest.java
> +}
재밌는 이야기라고 생각합니다.
BaseServiceTest는 모든 빈을 다 올리고 있는 부분에 대해서 우선 답변을 드리고자 합니다.
우선 스프링 테스트에서 빈을 한번 올리면, DirtyContexts나 MockBean등으로 오염되지 않는 이상 재사용 할 수 있기 때문에, 최초 실행시에만 속도적인 문제가 생기고, 추후에는 크게 문제가 되지 않기 때문에 모든 빈을 뛰우기로 했습니다.
그리고 충분히 fake(mock)을 통해 service의 dependency들을 다 만들어서 테스트도 가능하겠지만, 이렇게 하면 리팩터링에 대한 강성이 매우 낮아지기 때문에 추후 리팩터링에 대한 문제가 발생하기 때문입니다.

@Transactional을 통해 테스트를 작성하지 않는다면 repository의 모든 객체를 fake로 다 만들어줘야 하고, 잘못 만든 fake객체로 인해 테스트코드가 통과하게 된다면 프로덕션 코드까지 위험할 수 있기 때문에 실 DB와 데이터를 주고 받는것을 목표 했습니다.(이렇게 하면 DB특성을 포함하여 테스트가 가능하기에 1석 2조라고 생각했습니다.) 그리고 충분히 RDBMS는 Spring에서 @Transactional을 통해 관리할 수 있는 특징이 있기에 데이터 클린에 대한 이슈도 없었구요.

대신 저희가 컨트롤 하지 못하는 외부 의존성의 경우는 fake객체를 만들어서 테스트 용이하도록 했습니다.

2023-08-31 14:20 UTC, ohgillwhan commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        assertThat(foundMenu.getId()).isEqualTo(createdMenu.getId());
와 좋네요!!! 이런게 있는지 처음 알았습니다 👍 
해당 코드에서 사용 해보려 했는데 foundMenu 보단 menu(사실상 역할이 dto....)랑 비교해야해서 여러 제약조건이 걸려서 조금 어렵네요 😢 
회사에서 잘 사용해보겠습니다!! 오우 꿀팁 너무 감사해요

2023-09-01 12:34 UTC, hyunssooo approved these changes
안녕하세요.
이번 미션 진행하신다고 고생 많으셨습니다. :) 
남은 미션도 모두 잘 진행하시길 바랄게요!

2023-09-01 12:34 UTC, hyunssooo commented on src/test/java/kitchenpos/support/BaseServiceTest.java
> +}
`잘못 만든 fake객체로 인해 테스트코드가 통과하게 된다면 프로덕션 코드까지 위험` 
이 부분은 동의합니다 ㅎㅎ 
개인적으로는 길환님 테스트 의도는 통합 테스트에서 다뤄져도 괜찮을 것 같아요. service 테스트 작성자의 의도에 따라서 좀 다르겠지만 저는 service 테스트는 조금 더 가벼운 느낌으로 가도 괜찮을 것 같아서요. 그렇다면 framework, DB dependency 없이도 테스트가 가능할 것 같아서요 :) 
하지만 이 방법도 신경써야 할 부분은 분명 존재하고 두 의도 모두 장단이 있다고 생각합니다! ㅎㅎ
결국 뻔한 얘기지만 이런 부분들은 관점의 차이이고 상황에 따라서 다를 것 같습니다. 소중한 의견 감사합니다! 👍

2023-09-01 12:34 UTC, merged