Step3
next-step/ddd-legacy pull request #541
Opened 2023-09-01 02:19 UTC by mytechnic

리뷰 의견에 따라 문자열 덧셈 계산기 코드 및 요구 사항 정리의 문서를 업데이트하고,
'3단계 - 테스트를 통한 코드 보호' 테스트 코드를 작성 했습니다.

리뷰 요청 드립니다.

2023-09-02 01:41 UTC, hyunssooo requested changes
안녕하세요. 
전체적으로 테스트 잘 작성해 주셨어요!
junit의 기능들을 적절하게 잘 사용해 주신 부분이 인상 깊어요! 
몇 가지 코멘트 남겼는데요. 확인 부탁 드립니다. 
다음 요청에는 머지하도록 할게요. 🙂

2023-09-02 01:41 UTC, hyunssooo commented on README.md
> +    - [ ] 전시되거나 숨겨야 할 메뉴의 그룹 단위를 '메뉴 그룹' 이라고 한다.
`전시되거나 숨겨야 할` 이 설명은 빠져도 괜찮지 않을까요? 메뉴에 대한 설명이라서요.

2023-09-02 01:41 UTC, hyunssooo commented on README.md
> +        - 메뉴 가격이 상품의 가격과 수량을 곱한 가격과 같거나 높지 않은지 체크해야 한다.
`체크해야 한다.` 보다 `전시할 수 없다.` 는 어떨까요?

2023-09-02 01:41 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        @NullAndEmptySource
`@NullAndEmptySource` `@ParameterizedTest` 너무 좋습니다 :) 
다만 `메뉴 그룹의 이름이 없으면 예외 발생` 보다 요구 사항에 작성해주신 용어를 그대로 사용해 보는 것은 어떨까요? `메뉴 그룹의 이름이 없으면 등록할 수 없다.` 정도로도 작성 가능할 것 같아요.

2023-09-02 01:41 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private PurgomalumClient purgomalumClient;
`@Spy`, `@Mock` 을 적절하게 사용해 주셨네요. 
강의에서 가짜 객체에 대해서도 다룬 것으로 알고 있는데요. 이 부분도 적용해 보는 것은 어떨까요?

2023-09-02 01:41 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    class CreateTestGroup {
`@Nested` 👍

2023-09-02 01:41 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            final MenuProduct menuProduct = MenuProductFixture.createMenuProduct(product, 1);
이 부분은 클래스 내부의 모든 테스트가 사용하는데 중복을 제거할 수는 없을까요?

2023-09-02 01:41 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            assertThat(actual.isDisplayed()).isTrue();
단언문이 여러개라면 `Assertions#assertAll` 를 사용해 보는 것은 어떨까요? 
어떤 차이가 있을까요? 
```suggestion
            assertAll(
                () -> assertThat(actual).isNotNull(),
                () -> assertThat(actual.getPrice()).isEqualTo(request.getPrice())
            );
```

2023-09-02 01:41 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        void createTest4(OrderType type) {
`@EnumSource` 👍

2023-09-02 01:41 UTC, hyunssooo commented
남긴 코멘트는 해당 부분이 아닌 코드 전체적으로 봐주시면 좋을 것 같아요 :)

2023-09-04 08:15 UTC, mytechnic commented on README.md
> +    - [ ] 전시되거나 숨겨야 할 메뉴의 그룹 단위를 '메뉴 그룹' 이라고 한다.
> `전시되거나 숨겨야 할` 이 설명은 빠져도 괜찮지 않을까요? 메뉴에 대한 설명이라서요.

메뉴 그룹의 중요한 기능을 포함하는게 좋다고 생각했는데, 간결한 문장으로 표현하는것도 좋을 것 같네요.

2023-09-04 08:16 UTC, mytechnic commented on README.md
> +        - 메뉴 가격이 상품의 가격과 수량을 곱한 가격과 같거나 높지 않은지 체크해야 한다.
> `체크해야 한다.` 보다 `전시할 수 없다.` 는 어떨까요?

조금 더 표현이 부드러워 지는 것 같습니다.

2023-09-04 08:18 UTC, mytechnic commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +        @NullAndEmptySource
> `메뉴 그룹의 이름이 없으면 예외 발생` 보다 요구 사항에 작성해주신 용어를 그대로 사용해 보는 것은 어떨까요? `메뉴 그룹의 이름이 없으면 등록할 수 없다.` 정도로도 작성 가능할 것 같아요.

조금 더 표현이 자연스러워 지는 것 같습니다.

2023-09-04 08:28 UTC, mytechnic commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private PurgomalumClient purgomalumClient;
> `@Spy`, `@Mock` 을 적절하게 사용해 주셨네요. 강의에서 가짜 객체에 대해서도 다룬 것으로 알고 있는데요. 이 부분도 적용해 보는 것은 어떨까요?

가짜 객체의 기능이 아니면 테스트 할 수 save() 메소드의 기능과,
테스트의 목적에 편의성을 갖춘 Mock을 동시에 사용하기 위한 목적으로 @Spy를 사용 했다고 생각하는데요
더 효율적인 테스트를 위해 @Mock을 완전히 제거하는 것이 좋을까요?

2023-09-04 09:36 UTC, mytechnic commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            final MenuProduct menuProduct = MenuProductFixture.createMenuProduct(product, 1);
> 이 부분은 클래스 내부의 모든 테스트가 사용하는데 중복을 제거할 수는 없을까요?

UUID의 경우 테스트 관심사항이 아니라서 변수 할당을 생략하고,
Fixture 메소드의 경우에는 관심 파라미터를 제외하고 중복 제거할 수 있을 것 같네요.

2023-09-04 09:50 UTC, mytechnic commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +            assertThat(actual.isDisplayed()).isTrue();
> 단언문이 여러개라면 `Assertions#assertAll` 를 사용해 보는 것은 어떨까요?

비동기 스트림으로 평가를 동시에 진행한다는 측면에서 차이가 있는 것 같습니다.
다만, NotNull 을 먼저 체크를 하지 않고 사용 할 경우 NPE 이슈도 있는 것 같습니다.

2023-09-05 10:40 UTC, hyunssooo approved these changes
안녕하세요. 
이번 미션 진행하신다고 고생 많으셨습니다. :) 
남은 미션도 잘 진행하시길 바랄게요!

2023-09-05 10:40 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    private PurgomalumClient purgomalumClient;
`@mock을 완전히 제거하는 것이 좋을까요?`
좋다 나쁘다의 개념이 아닌 여러가지 테스트 방법을 경험해 보면 좋을 것 같아 남긴 코멘트였습니다!

2023-09-05 10:40 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        @Test
요구 사항과 테스트 설명이 동일해져서 다른 사람들이 이해하기 더 쉬울 거 같아요. 👍

2023-09-05 10:40 UTC, merged