test (calculator): 1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #594
Opened 2024-05-01 11:41 UTC by gutenLEE

2024-05-01 17:25 UTC, hyunssooo requested changes
안녕하세요. 🙂
몇 가지 코멘트 남겼어요. 
함께 고민해 보고 싶은 부분은 코멘트나 DM 으로 남겨주세요!
이전 pr에 남긴 코멘트도 확인해 보시면 좋을 것 같습니다.

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +        }
RuntimeException 보다 적절한 예외를 던져 주는 것은 어떨까요? 
그리고 적절한 예외 메세지를 작성해 주면 좋을 것 같습니다.
지금은 로컬이라 디버깅이 쉽지만 배포되어 있다면 디버깅이 쉽지 않을 것 같네요.

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +    }
`"[a-zA-Z]"` 이 부분은 상수화를 통해 가독성을 높여보면 좋을 것 같네요. 
전체적으로 확인해 보면 좋을 것 같습니다.

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +    }
Pattern 객체는 생성 비용이 비싼 객체인데요. 이 부분은 한번 생성하고 재사용 가능하지 않을까요? 
이펙티브 자바 아이템 6. 불필요한 객체 생성을 피하라 를 읽어보시면 좋을 것 같아요.

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +    }
전체적으로 배열을 많이 사용하고 계신데 이번 기회에 Collection과 Stream에 익숙해져 보는 것은 어떨까요? 사용하기 편한 api들을 많이 제공하고 있습니다.

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +    }
```suggestion
    private static int[] initArray(String[] values) {
        return new int[values.length];
    }
```

개행도 의미있게 사용하면 좋습니다. 또한 기본적인 스페이스 컨벤션은 지켜지면 좋을 것 같아요. :)

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/CalculatorTest.java
> +
https://edu.nextstep.camp/s/6ADuNPQG/ls/rCXncCoD

> 빈 문자열 또는 null을 입력할 경우 0을 반환해야 한다.

이 부분의 테스트는 작성이 필요해 보여요!

2024-05-01 17:25 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +import java.util.regex.Pattern;
사용하지 않는 import는 제거하면 좋을 것 같아요.

2024-05-01 17:27 UTC, hyunssooo commented
step1 브랜치는 rebase 하지 않으신 것 같은데 rebase 하시면 좋을 것 같아요. :) 
upstream 본인 브랜치 기준으로 진행하시면 될 것 같습니다.

2024-05-01 21:37 UTC, gutenLEE commented
피드백 반영했습니다!

2024-05-02 07:21 UTC, hyunssooo requested changes
안녕하세요. 🙂
가벼운 코멘트 하나 남겼습니다! 
확인 부탁드립니다!

2024-05-02 07:21 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +    }
지난 step에서 Position 처럼 원시값을 포장해 볼 수 있지 않을까요? 
작성한다면 해당 객체는 어떤 책임을 가질 수 있을까요? 

https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/
https://tecoble.techcourse.co.kr/post/2020-05-08-First-Class-Collection/ 

이 두 글이 도움이 되면 좋겠어요.

2024-05-02 12:40 UTC, gutenLEE commented on src/test/java/calculator/Numbers.java
Integer 리스트를 일급컬렉션으로 래핑하고 관련 행위들은 `Numbers`로 이동시켰습니다. 
`sum()` 도 `Numbers`로 옮겼는데 `sum()`을 `Calculator`에 둘지 `Numbers`에 둘지 고민이 되었습니다만, 
`Integer` 리스트 구조체를 잘 아는 `Numbers`에게 위임했습니다

2024-05-02 12:40 UTC, gutenLEE commented on src/test/java/calculator/Calculator.java
> +        return numbers.sum();
메서드도 추상화 레벨에 맞게 추출하라는 가르침을 받았었습니다. 
잘 된건지 궁금합니다 ㅎㅎ

2024-05-02 15:39 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 추가로 남겼습니다. 
확인 부탁드릴게요.

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/Numbers.java
> +
일급컬렉션 구현 좋습니다. 
다만 제가 의도한 부분은 일급컬렉션과 숫자 하나의 원시값 포장 두 가지 였는데요. 이 부분도 도전해 보시는 건 어떨까요? 
`숫자 하나` 를 의미하는 객체는 어떤 책임을 가질 수 있을까요?

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/Numbers.java
> +    }
static 메서드와 static이 아닌 메서드는 어떤 차이가 있을까요? 각각 어떤 경우에 사용해야할까요?

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/Numbers.java
> +
이 클래스는 테스트가 없네요 🤔

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/Numbers.java
넵 저도 합에 대한 역할은 일급컬렉션인 Numbers에 둘 것 같아요. 👍

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/CalculatorTest.java
> +    }
`@NullAndEmptySource`는 0 이 입력되나요?

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/CalculatorTest.java
> +    }
구분자는 `:` 도 있는데요. 이 부분도 테스트되면 좋을 것 같아요.

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +
```suggestion

    private static final int ZERO = 0;
    private static final Pattern DELIMITER_PATTERN = Pattern.compile("//(.)\n(.*)");
    private static final String ALPHABET_PATTERN = "[a-zA-Z]";

```

2024-05-02 15:39 UTC, hyunssooo commented on src/test/java/calculator/Calculator.java
> +        return numbers.sum();
좋은 가르침을 받으셨네요! 클린 코드 3장 함수에도 동일한 내용이 나옵니다! 읽어 보시면 도움이 될 것 같아요! 지금 코드는 좋은 것 같습니다!

2024-05-03 00:09 UTC, gutenLEE commented on src/test/java/calculator/Numbers.java
> +    }
static메서드와 static이 아닌 메서드의 차이는
클래스의 행위냐 인스턴스 행위냐로 구분할 수 있습니다!

static 메서드는 런타임 시에 결정되는 인스턴스 변수에 접근할 수 없기 때문에 
모든 객체에서 공통으로 사용하는 메서드용으로 사용합니다.

static이 아닌 메서드는 인스턴스 멤버기 때문에 인스턴스의 행위에 사용합니다.

2024-05-03 00:16 UTC, gutenLEE commented on src/test/java/calculator/Number.java
> +        }
음수에 대한 검증을 Calculator의 책임으로 둘지 Number에 둘지 고민이 됩니다...
`음수이면 예외를 반환한다`를 `Calculator`의 비즈니스 요구사항으로 본다면 
단순 원시값 wrapper 클래스인 `Number` 두는게 맞을까싶네요!

2024-05-03 00:16 UTC, gutenLEE commented on src/test/java/calculator/Number.java
> +        }
```java
  if (isNotNumber(number)) {
            throw new IllegalArgumentException("invalid number string: " + number);
        }

  this.number = toInt(number);

  if (isNegative()) {
      throw new IllegalArgumentException("not allow negative number: " + number);
  }
```
뭔가 선언 순서가 요상한데 
`검증, 인스턴스 변수 할당, 검증`... 순서가 어색한데 
`검증, 검증, 인스턴스 변수 할당`이 일반적인가요?

2024-05-03 00:17 UTC, gutenLEE reviewed
피드백 주신 VO 사용을 해보니 
VO 속성과 관련된 행위들이 VO로 모이게 되어 코드 응집력이 높아졌다고 느꼈습니다!

2024-05-03 07:57 UTC, hyunssooo approved these changes
안녕하세요 🙂
몇 가지 추가로 코멘트 남겼습니다. 
다음 step 진행하시면서 확인 부탁드려요!

2024-05-03 07:57 UTC, hyunssooo commented on src/test/java/calculator/Number.java
> +
https://github.com/next-step/ddd-legacy/pull/594/files#r1588545567

저라면 생성자와 정적 팩터리 메서드를 따로 제공할 것 같아요.

```java
    public Number(int number) {
        if (number < 0) {
            throw new IllegalArgumentException("not allow negative number: " + number);
        }
        this.number = number;
    }

    public static Number of(String number) {
        if (isNotNumber(number)) {
            throw new IllegalArgumentException("not allow non-number: " + number);
        }
        return new Number(Integer.parseInt(number));
    }
```

2024-05-03 07:57 UTC, hyunssooo commented on src/test/java/calculator/Number.java
> +    }
개인적으로는 조금 과한 것 같아요.

2024-05-03 07:57 UTC, hyunssooo commented on src/test/java/calculator/Number.java
> +    }
이것도 충분히 식만 보고 음수는 안된다는 것을 파악할 수 있지 않을까요?

2024-05-03 07:57 UTC, hyunssooo commented on src/test/java/calculator/NumberTest.java
> +}
파일 마지막은 new line으로 끝납니다. 인텔리제이 설정에 자동으로 추가하는 옵션이 있으니 찾아보고 적용해 보는 것은 어떨까요?

2024-05-03 07:57 UTC, hyunssooo commented on src/test/java/calculator/NumberTest.java
> +
음수에 대한 테스트도 작성해 보는 것은 어떨까요? 
0은 포함되나요? 테스트로 표현해 보면 좋겠습니다.

2024-05-03 07:57 UTC, hyunssooo commented on src/test/java/calculator/Numbers.java
> +
Number의 getter를 사용하지 않는 방법은 없을까요? 

예를 들어 

```java
    public Number plus(Number other) {
        return new Number(this.number + other.number);
    }

```

이런 메서드가 Number 클래스에 존재한다면 

```java
    public int sum() {
        return numbers.stream()
            .reduce(new Number(0), Number::plus)
            .value();
    }
```

이렇게도 가능하겠네요. 

해당 테스트를 통과하게 하는 방법은 무엇이 있을까요? 
```java
    @Test
    void name() {
        assertThat(new Number(1)).isEqualTo(new Number(1));
    }
```

2024-05-03 07:57 UTC, merged