2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #617
Opened 2024-05-04 06:27 UTC by doorisopen

안녕하세요 시훈님~!
2단계 - 요구 사항 정리 리뷰 요청드립니다.🙂

요구 사항 정리는 tdd 구현 미션 과정 안에서 가볍게 진행했었는데 하나의 미션으로 진행하니까 새로운 느낌이네요🔥
코드를 보고 요구사항을 정리 하려니 너무 구현 관점에서 정리되는 느낌이 있어서 API를 중점으로 정리해봤습니다!
이번 미션도 잘부탁드립니다😎

2024-05-05 06:19 UTC, sihoony requested changes
안녕하세요. 태웅님,
미션 잘 진행해주셨네요. 👍 
코멘트를 남겼으니 확인 부탁드려요.
즐거운 하루 되세요~! 😄

2024-05-05 06:19 UTC, sihoony commented on README.md
> +  * validation: 1), 2), 3)
메뉴 가격, 수량에 대한 조건은 없는지 확인해보면 좋을 것 같아요.

2024-05-05 06:19 UTC, sihoony commented on README.md
> +* 상품 가격을 변경할 수 있다.
메뉴에 속한 상품 가격에 대한 조건은 없을까요~!?

2024-05-05 06:19 UTC, sihoony commented on README.md
> +### 주문(Order)
주문과 주문 테이블을 나눈다면 명확해질 것 같네요~!

2024-05-05 06:19 UTC, sihoony commented on README.md
> +### 메뉴(Menu)
메뉴와 메뉴그룹으로 나눠보면 어떨까요?

2024-05-05 06:19 UTC, sihoony commented on README.md
>  ## 요구사항
validation으로 참조항목을 작성하는 방법과 인지하기 쉽게 항목마다 작성하는 방법 중에 어떤 방법이 읽기 편한지 고민해보면 좋을 것 같습니다. 😄

2024-05-05 07:22 UTC, doorisopen commented on README.md
>  ## 요구사항
개발자, 기획자 입장에서 생각했을 때 각기 다른 장단점을 가지고 있다고 생각이 들었습니다!

참조항목으로 작성하는 경우, validation 내용을 확인하기 위해서 화면 이동을 해야 하는 번거로움이 있지만 정책 변경으로 인한 수정 범위를 한 곳으로 집중 시킬 수 있을 듯합니다.
 
각 항목마다 작성하는 경우, 해당 기능에 대한 validation 내용을 한번에 파악하기 쉽다는 장점은 있지만 정책 변경으로 인한 수정 영향 범위가 커질 수 있고 누락되는 경우도 발생할 수 있을 듯 합니다. 그리고 누락으로 인해 도메인에 대한 지식의 불일치가 발생하여 이해관계자들 간에 오해하는 경우도 있을 듯하네요

개인적으론 참조 항목으로 작성된 것을 읽는 걸 선호하는 듯 합니다. 
약간의 번거로움은 있지만 도메인을 이해하고 있는 내용이 불일치할 수 있는 상황을 최소화해준다고 생각하고 불일치한 부분을 일치시키기 위해 드는 비용은 번거로움을 넘어선다고 생각이 드네요ㅎㅎ

2024-05-06 13:02 UTC, sihoony approved these changes
안녕하세요. 태웅님,
피드백 잘 반영해주셨고, 의견도 잘 들었습니다 👍 
다음 미션을 위해서 빠르게 머지 할께요~!
즐거운 하루 되세요! 😄

2024-05-06 13:02 UTC, merged