Step2 - 요구 사항 정리
next-step/ddd-legacy pull request #623
Opened 2024-05-04 13:06 UTC by jinyoonYang

step1과 별개로 작업이 가능한 것 같아 먼저 PR 올렸습니당 😊
참고 부탁드려요! 

Readme에 엔티티 관계도도 한번 그려서 넣어봤는데 JPA가 완전 익숙하진 않아서요 
제가 맞게 이해하고 있는게 맞는지 궁금합니다
함께 코멘트 부탁드릴게용

2024-05-06 14:34 UTC, Gomding requested changes
안녕하세요 진윤님!
2단계도 꼼꼼하게 진행해주셨네요~!
몇가지 코멘트 남겼으니 확인부탁드려요 🙏

2024-05-06 14:34 UTC, Gomding commented on src/test/java/stringCalculator/PositiveNumber.java
> +    private int number;
원시값 포장한 양수 객체 👍

2024-05-06 14:34 UTC, Gomding commented on src/test/java/stringCalculator/PositiveNumber.java
> +    public static PositiveNumber from(String numberString){
해당 팩터리 메서드는 `validateNumberFormatAndPositiveNumber` 메서드 위로 위치시키는게 가독성에서 좋을것같아요!

저는 보통 아래와 같이 순서를 지정해요!
- 상수
- 멤버 변수
- 생성자
- static 메서드 (정적 팩터리 메서드)
- static 메서드
- 멤버 메서드
- getter 
- equals & hashcode

2024-05-06 14:34 UTC, Gomding commented on src/test/java/stringCalculator/PositiveNumber.java
> +    private static void validateNumberFormatAndPositiveNumber(String numberString) {
해당 메서드는 2개의 검증을 하고있으니 분리하는것도 좋겠어요!

- validateNumberFormat
- validatePositiveNumber

각 메서드가 어떤 검증을 하는지 명확하니 
하나의 메서드에 있을 때는 어디가 `숫자 포맷 검사` 이고 `양수인지 검사` 인지 직접 나눠서 인지해야하는데
메서드로 명확하게 나눠주면 수정 범위를 바로 파악할 수 있겠죠 🤗

2024-05-06 14:34 UTC, Gomding commented on src/test/java/stringCalculator/CalculatorTest.java
> +    @DisplayName(value = "문자열 계산기에 숫자가 아닌 값을 전달할 경우 IllegalArgumentException 예외 처리를 한다.")
꼼꼼하게 테스트까지 추가해주셨군요 👍

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +* 간단한 포켓몬 게임을 구현한다.
해당 부분은 키친포스에 맞게 적절하게 변경해주시면 좋을것같아요! 👍

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 메뉴카테고리를 추가할 수 있다.
메뉴 카테고리 추가 시 이름은 1글자 미만일 수 있었을까요? 😉
자세한 요구사항이 함께 정리되면 좋겠어요!

> 메뉴 카테고리의 이름은 1글자 이상이어야 한다.

+) 전체적으로 적용되면 좋겠어요!

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +** [ ] 사용자는 매장주인이다.
메뉴 카테고리는 어떻게 구성됐는지도 적어보면 좋겠어요!

> 메뉴 카테고리는 이름을 가진다

+) 이것도 전체적으로 적용되면 좋겠어요 😳

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +*** 주문 유형: 먹고가기, 포장하기, 배달하기, 주문 아이템: 메뉴정보, 가격, 수량
주문 유형과 주문 아이템에 대한 정보는 라인을 분리하여 적어주는게 가독성에서 좋을것같아요!

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +*** 주문 유형: 먹고가기, 포장하기, 배달하기, 주문 아이템: 메뉴정보, 가격, 수량
주문 아이템은 무엇을 의미하는지 궁금해요!
고객이 주문한 하나의 메뉴일까요?

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +*** 배달인 경우 상태변경과 함께 라이더를 요청한다.
👍 👍 👍 👍

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +** [ ] 주문 상태는 각각의 단계에 맞게 변경되어야 한다. (이전 상태가 다를 경우 에러 발생)
상태에 맞는 단계 변경을 잘 파악해주셨군요👍 

어떤 상태들이 있는지 쭉 나열해주는것도 좋을것같아요!

>  - 주문 상태는 다음과 같다.
      - 대기 - WAITING
      - 수락 - ACCEPTED
      - 제공 - SERVED 
      - 배달 - DELIVERING
      - 배달완료 - DELIVERED
      - 주문 완료 - COMPLETED

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 등록한 메뉴의 가격을 변경할 수 있다.
메뉴 가격 변경시 아래와 같은 사항이 있었을 거에요!

```java
            if (price.compareTo(sum) > 0) {
                throw new IllegalArgumentException();
            }
```

해당 부분도 함께 명시해주시면 좋겠어요!

2024-05-06 14:34 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 음식 가격을 변경할 수 있다.
음식 가격 변경 시 메뉴의 노출여부에 대한 사항도 있었을거에요!

2024-05-07 11:10 UTC, jinyoonYang commented on README.adoc
> +*** 주문 유형: 먹고가기, 포장하기, 배달하기, 주문 아이템: 메뉴정보, 가격, 수량
넵 맞습니다~! 
좀더 상세하게 문구 수정했습니다.

2024-05-07 14:04 UTC, Gomding requested changes
안녕하세요 진윤님!
빠르게 반영해주셨군요 👍 
추가로 남긴 코멘트도 확인 부탁드려요 🙏

2024-05-07 14:04 UTC, Gomding commented on README.adoc
> +** [ ] 사용자는 매장주인이다.
해당 코멘트도 확인 부탁드려요!
혹시 반영하지 않는다면 이유도 알려주시면 좋을것같아요 🤗

2024-05-07 14:04 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 메뉴카테고리를 추가할 수 있다.
해당 코멘트도 확인 부탁드립니다! 🙏

2024-05-07 14:04 UTC, Gomding commented on README.adoc
> +* 음식
Product 와 음식은 이름에서 매칭이 잘 안되는것 같은데
음식이라 지어주신 배경이 궁금해요 🤗

2024-05-07 14:04 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 음식 이름과 가격을 정해서 상품을 등록할 수 있다.
여기는 상품이라 언급하셔서 위의 음식과 매칭되지 않고 있어요!

프로젝트 관계자 모두와 이름을 통해 소통하니 
항상 한가지로 통일시켜 말하는것이 중요해요 🤗

여기도 통일시켜보죠!

2024-05-07 14:04 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 특정 메뉴 카테고리에 음식을 조합해서 메뉴를 등록할 수 있다. (단, 조합된 음식의 가격이 단일 음식들의 총 금액보다 비쌀 수 없음)
메뉴 등록 시 메뉴 이름에 대한 정책도 존재하고 있어요 🧐
해당 부분도 함께 정리해보죠!

2024-05-07 14:04 UTC, Gomding commented on README.adoc
> +** [ ] 매장주인은 특정 메뉴 카테고리에 음식을 조합해서 메뉴를 등록할 수 있다. (단, 조합된 음식의 가격이 단일 음식들의 총 금액보다 비쌀 수 없음)
메뉴 등록 시 다양한 정보에 대해 검증하고 등록하는데
모든 프로젝트 관계자가 메뉴 등록 시 일어나는 과정에 대해 알 수 있도록 자세히 적어주시는게 중요합니다 :)
모든 검증 과정을 나열해보는것도 좋습니다 😉

- 메뉴의 가격은 양수여야한다.
- 메뉴는 하나 이상의 상품으로 구성된다
- 메뉴 내부의 상품은 개수를 가질 수 있다. ex) 두마리 후라이드 치킨메뉴 - (후라이드치킨 상품 2개로 구성)

2024-05-09 10:24 UTC, Gomding approved these changes
안녕하세요 진윤님!
꼼꼼하게 요구사항 정리해주셨군요 👍👍
충분히 정리하신것같아 이만 merge 하겠습니다.
추가로 남긴 코멘트는 다음 단계 진행하면서 함께 고민해주세요!

다음 단계 진행 시 [브랜치 생성 방법](https://nextstep-members.slack.com/archives/C070KNZT21H/p1714523934462129) 참고하여 진행해주세요! 🤗

2024-05-09 10:24 UTC, Gomding commented on README.adoc
> +** 데이터 구성 : 메뉴카테고리 이름
데이터는 개발자 관점의 키워드라고 느껴져요!

여러 이해관계자가 도메인 지식을 동일하게 이해하고 말할 수 있도록
개발자 중심의 키워드는 제거해보죠 😉
> 메뉴 카테고리는 이름을 가진다.

2024-05-09 10:24 UTC, Gomding commented on README.adoc
> +*** 조건 2) 이름에 비속어가 포함되어 있음 안된다.
비속어 검사도 파악해주셨군요! 👍

2024-05-09 10:24 UTC, Gomding commented on src/test/java/stringCalculator/PositiveNumber.java
> +public class PositiveNumber {
해당 코멘트는 반영 안하셔도 괜찮아요!

다음 미션에는 분리한 객체들에 대한 테스트도 작성해주시는게 좋아요 🤗

2024-05-09 10:25 UTC, merged