Step2
next-step/ddd-legacy pull request #625
Opened 2024-05-04 15:06 UTC by Whale0928

안녕하세요!  요구사항 정의 미션에 대해 작업 후 피드백 요청드립니다!

작성 하면서 의문점이 좀 있었는데.

>해당 요구사항 분석을 보는 입장을 어디까지 고려해야할까요
>작성 시 개발 입장에서만 요구 사항을 분석했는데 다른 팀원이 볼수도 있을까요?
이런 식의 요구사항 분석은 처음인대 여러모로 재밌는 경험인것 같습니다 😄

2024-05-05 02:42 UTC, Hyeon9mak requested changes
안녕하세요 현기님! 요구사항 분석문서 잘 작성해주셨습니다.

> 작성 시 개발 입장에서만 요구 사항을 분석했는데 다른 팀원이 볼수도 있을까요?

넵! 더 나아가 요구사항 분석문서는 개발직군 뿐만 아니라 비개발직군도 함께 볼 수 있어야한다고 생각해요.
떄문에 개발적인 내용은 최대한 덜어내고, 비개발직군도 함께 보고 크로스체크가 가능하도록
일반적인 상식을 이용해서 문서를 작성하는 것이 중요하다고 생각합니다. 😄 

이와 관련하여 몇 가지 코멘트 남겼습니다!
궁금하신 점 언제든지 질문주세요~

2024-05-05 02:42 UTC, Hyeon9mak commented on README.md
> +- 메뉴는 하나 이상의 메뉴로 구성될 수 있습니다.
`메뉴 그룹은 하나의 이상의 메뉴로 구성될 수 있습니다.` 일까요? 😉

2024-05-05 02:42 UTC, Hyeon9mak commented on README.md
> +    - `name` 필드는 고유한 값이어야 합니다.
말씀해주신대로 요구사항 문서는 동료가 볼 수 있죠!
그런데 이 동료에는 개발자 뿐만 아니라 기획자, Product owner 도 포함된다고 생각합니다.
그들에게 이런 내용은 불필요한 내용이 될 수도 있겠어요.
어느 누가 읽어도 상식으로 이해할 수 있도록, 아래와 같이 표현해보는 건 어떨까요?

```
메뉴 그룹 등록 요청을 통해 새로운 메뉴 그룹을 만들 수 있습니다.

- 메뉴 그룹은 식별자와 이름으로 구성되어 있습니다.
- 식별자는 랜덤한 값이 자동으로 할당되며, 이름은 필수로 입력되어야 합니다.
- 이름은 중복으로 이루어질 수 없고 고유해야합니다.
```

2024-05-05 02:42 UTC, Hyeon9mak commented on README.md
> +    - 예를 들어 `후라이드 치킨 세트` **메뉴**에는 `후라이드 치킨`과 `콜라`가 포함될 수 있습니다.
계속해서 예시를 들어주신 덕분에 무엇을 의미하는지 더욱 명확하게 이해할 수 있네요 👍 
이런 사소한 배려들이 팀원 전체의 생산성에 큰 기여를 한다고 생각합니다!! 💯

2024-05-05 02:42 UTC, Hyeon9mak commented on README.md
> +    - 복잡성을 줄이기 위해 `menu` 와 `product` 의 관계를 해소하는 `menu_product` 테이블을 사용합니다.
(물론 요즘은 비개발, 사업직군도 DB 를 어느정도 이해하고 SQL 문도 작성하는게 트렌드지만)
어떤 테이블로 어떻게 관리하는지 또한 비개발직군에게는 다소 어려운 개념일 수도 있겠어요!
그들에게 혼란을 초래할 수 있는 개념은 다소 덜어내고, 친절한 설명을 더해보는 건 어떨까요? 
요구사항 정리 문서를 그들이 읽어보고, "현기님 메뉴와 상품은 xxx 관계에요!" 라고 서로 크로스 체크가 가능하도록요 😄

2024-05-05 02:42 UTC, Hyeon9mak commented on README.md
> +      하나입니다.
각각의 상태에 대해 한글 명칭을 부여하고, 아래와 같이 상태전이를 정리해볼 수도 있겠어요 😄 

- 배달 주문시 최초 `주문` 상태에서 접수시 `주문 접수` 상태로 변경될 수 있습니다.
- `주문 접수` 상태에서 배달을 시작할 경우 `배달 시작` 상태로 변경될 수 있습니다.

2024-05-05 06:24 UTC, Whale0928 commented on README.md
> +    - `name` 필드는 고유한 값이어야 합니다.
아하 무슨 느낌인지 알것 같습니다!

2024-05-05 21:22 UTC, Whale0928 commented
말씀해주신 부분들을 참조해 수정해보았습니다!

2024-05-06 03:36 UTC, Hyeon9mak approved these changes
안녕하세요 현기님! 피드백 빠르게 잘 반영해주셨습니다 👍 👍 
간단한 코멘트를 추가로 남겼으니 다음 단계 진행에 참고해주세요!

2024-05-06 03:36 UTC, Hyeon9mak commented on README.md
> +- **메뉴 그룹**은 각각 고유한 걔념을 가질 수 있습니다.
**메뉴 그룹**, **메뉴** 등 키워드를 강조해주셨군요! 💯 
모든 구성원이 같은 용어를 다룰 수 있게 될 것이고, 이를 코드(클래스 파일, 멤버변수)로 다루기도 용이하겠네요!

2024-05-06 03:36 UTC, Hyeon9mak commented on README.md
> +- **메뉴 그룹**을 조회할 수 있습니다.
개발을 아예 모르는 중학생도 이해할 수 있겠는데요? 👍 👍

2024-05-06 03:36 UTC, Hyeon9mak commented on README.md
> +    - `메뉴그룹식별자`는 어느 메뉴그룹에 속하는지 확인하는 값입니다. **메뉴 그룹**의 식별자와 연결됩니다.
요렇게 상세 정책을 표현해주신 덕분에 기획자가 
"헉! 최대 금액은 1,000,000,000 원으로 제한해야겠네요." 라는 아이디어를 제시해줄 수도 있겠어요 🤣 👍

2024-05-06 03:36 UTC, Hyeon9mak commented on README.md
> +    - 요청 시 하나 이상의 `주문 항목`를 함께 등록해야합니다.
상태전이 정리 💯 

사실 이렇게 보면 타입별로 상태가 어떻게 전이되는지 눈에 잘 들어오지 않는데요,
이걸 코드로 표현해도 마찬가지로 복잡할거에요. (if 문 분기로 요리조리 움직이다보면...)

때문에 각 주문 타입별로 필요한 정보와 상태전이를 완전히 나누어 정리하고,
그걸 코드로 표현함으로서 복잡도가 크게 해소되는 경험을 하실거라 기대됩니다 💯 

```
[배달]
+ 배달 주소
대기중 > 접수됨 > 배달중 > 배달완료 > 완료됨

[포장]
대기중 > 접수됨 > 서빙됨 > 완료됨

[매장 식사]
+ 테이블
대기중 > 접수됨 > 서빙됨 > 완료됨
```

이렇게 보면 `포장`, `매장 식사` 관점에서는 `배달중`, `배달완료`, `배달주소` 3가지 정보가 불필요한 정보가 되죠!
반대로 `포장`, `배달` 입장에서는 `테이블` 정보가 불필요하구요!

현기님도 잘 아시겠지만, 각 타입의 주문을 서로 비슷한 종류의 주문으로 보지 않고 
완전히 다른 개념으로 바라보면서 정말 필요한 정보만 다루고 불필요한 정보는 완전히 배제시키는 것,
서로의 경계를 명확하게 나누는 것을 저희는 Bounded Context 라 부르는 것 같아요!!

요게 DDD 세레나데 강의의 핵심이라 생각됩니다 👍

2024-05-06 03:36 UTC, Hyeon9mak commented on README.md
> +```
오 머메이드를 잘쓰시는군요.. 👍 양질의 리뷰를 위해선 저도 빨리 연습해야겠네요 🥲 👍

2024-05-06 03:36 UTC, merged

2024-05-06 03:38 UTC, Hyeon9mak commented on README.md
> +    - 요청 시 하나 이상의 `주문 항목`를 함께 등록해야합니다.
때문에 여유가 되신다면 `주문` 이라는 큰 덩어리 대신 `매장 식사 주문`, `포장 주문`, `배달 주문` 이라는 3가지 덩어리로 나누어 정리해보는 것도 좋겠습니다 😄