1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #626
Opened 2024-05-04 15:47 UTC by tongnamuu

안녕하세요. 문자열덧셈계산기 구현했습니다.
문자열을 파싱하는 객체만 따로 분리를 했습니다.
 StringCalculatorParser 는 문자열에 대해 List<Integer> 형태로 결과를 반환해줍니다.

add 에서는 음수를 처리하지 않는 다는 요구조건은 add 함수에서 처리하게 했습니다.
만약 divide 라는게 생긴다면 제수(divisor)가 0이 인자로 있으면 안될거라 숫자 범위에 대한 처리는 StringCalculatorParser가 아닌 StringCalculator 메소드 내부에서 처리하는게 맞을 것 같습니다.

또한 
`빈 문자열 또는 null 값을 입력할 경우 0을 반환해야 한다.`
에 대해서는 
StringCalculator add 메서드에서 처리하게 하고
 StringCalculatorParser 에서는 IllegalArgumentException 을 반환하게 했습니다.
 만약 곱셈이 생긴다고 하면 그건 1을 반환해주는 것이 맞을 것 같습니다.
 
 리뷰 잘 부탁드립니다!

2024-05-05 15:30 UTC, HackSung requested changes
안녕하세요 태형님 😄 
1단계 미션 구현하시니라 고생하셨습니다.
몇가지 피드백을 남겨드렸는데 검토부탁드려요~

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/StringCalculator.java
> +        List<Integer> result = stringCalculatorParser.execute(text);
객체지향 프로그래밍 훈련 관점에서 List타입보다는 각 엘리먼트가 양수임을 보장하고 합계기능도 제공해주는 
일급 컬렉션을 사용하면 더욱 좋을 것 같습니다. 😄 
일급 컬렉션에 대한 내용은 아래 블로그글을 참조해 주세요.
- https://jojoldu.tistory.com/412

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/StringCalculator.java
> +            throw new RuntimeException("음수는 처리하지 않습니다");
명확한 에러메세지를 정의해 주신건 좋지만 RuntimeException을 직접 사용하기보다 표준 예외를 사용하시는건 어떨까요?
- https://velog.io/@chullll/72.-%ED%91%9C%EC%A4%80-%EC%98%88%EC%99%B8%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/StringCalculator.java
> +    private static final String DELIMITERS = "[,:]";
StringCalculatorParser에 이미 정의되어 있는 것 같습니다. 😄 
```suggestion
```

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/StringCalculatorParser.java
> +    private static final Pattern CUSTOM_DELIMITER_PATTERN = Pattern.compile(CUSTOM_DELIMITER_REGEX);
패턴 객체를 미리 생성해서 재사용 👍

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/test/StringCalculatorTest.java
> +    @ValueSource(strings = {"//;\n1;2;3", "//;\n//#\n1;2;3",  "//;\n//#\n1;2#3"})
만약 커스텀 구분자를 점으로 지정하면 테스트 결과가 어떻게 될까요? 🤔

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/test/StringCalculatorTest.java
> +class StringCalculatorTest {
모든 요구 사항에 대한 꼼꼼한 테스트 케이스 작성 💯 
테스트 클래스는 이미 src/test 아래에 있으니 굳이 test디렉토리를 또 만들어 넣지 않아도 될 것 같아요.
대신 관례대로 테스트 클래스를 제외한 나머지 메인 클래스들은 src/test가 아닌 src/main쪽으로 옮겨 관리하는 건 어떨까요?

2024-05-05 15:30 UTC, HackSung commented on src/test/java/stringcalculator/test/StringCalculatorParserTest.java
> +class StringCalculatorParserTest {
Parser클래스 전용 테스트 케이스 작성 👍 
여기에도 테스트코드 가독성을 위해 `@DisplayName`을 추가해 주시면 좋을 것 같아요.

2024-05-05 19:08 UTC, tongnamuu commented on src/test/java/stringcalculator/StringCalculator.java
> +    private static final String DELIMITERS = "[,:]";
제거했습니다!

2024-05-05 19:09 UTC, tongnamuu commented on src/test/java/stringcalculator/StringCalculator.java
> +            throw new RuntimeException("음수는 처리하지 않습니다");
IllegalArgumentException 으로 변경했습니다

2024-05-05 19:10 UTC, tongnamuu commented on src/test/java/stringcalculator/test/StringCalculatorParserTest.java
> +class StringCalculatorParserTest {
추가했습니다~

2024-05-05 19:10 UTC, tongnamuu commented on src/test/java/stringcalculator/test/StringCalculatorTest.java
> +class StringCalculatorTest {
main 으로 변경했습니다.

2024-05-05 19:10 UTC, tongnamuu commented on src/test/java/stringcalculator/test/StringCalculatorTest.java
> +    @ValueSource(strings = {"//;\n1;2;3", "//;\n//#\n1;2;3",  "//;\n//#\n1;2#3"})
. 구분자 테스트케이스 추가했습니다.

2024-05-05 19:21 UTC, tongnamuu commented on src/test/java/stringcalculator/StringCalculator.java
> +        List<Integer> result = stringCalculatorParser.execute(text);
기존에는 요구사항이 단순하여 굳이 분리하지 않았습니다.
하지만 특정한 책임을 갖는 클래스 객체를 만든다면 확장 가능성에 따라 클래스를 만드는 것이 좋을 것 같습니다.

저는 해당 미션에서 변경사항의 두 축이
숫자범위(음수처리), 덧셈에서 사칙연산으로의 확장으로 보여서 
숫자범위에 대한 것을 체크해주는 Validator 과 실제 계산을 담당하는 Calculator 로 나눴습니다.

곱셈이 추가된다면
기존 Validation + 신규 Multiplier 를 만들고
숫자범위가 음수가 포함이 된다면
새로운 Validation + 기존 Adder 로 생각했습니다.

2024-05-06 08:21 UTC, HackSung requested changes
피드백 잘 반영해 주셨습니다. 👏 
사소한 코멘트 몇개를 추가로 남겨드렸는데 확인부탁드립니다.
다시 Pull Request주시면 바로 머지하여 드리겠습니다. 😄

2024-05-06 08:21 UTC, HackSung commented on src/main/java/stringcalculator/calculator/IntegerAdder.java
> +        return parsedNumbers.getIntegers().stream().filter(Objects::nonNull).reduce(0, Integer::sum);
사소하지만 객체 지향 생활 체조 원칙을 지켜보도록 노력하는 건 어떠실까요?
`규칙 4: 한 줄에 점을 하나만 찍는다.`
가독성 측면에서도 좋아 질 것 같아요 😄

2024-05-06 08:21 UTC, HackSung commented on src/test/java/stringcalculator/StringCalculator.java
> +        List<Integer> result = stringCalculatorParser.execute(text);
이번 미션은 객체지향프로그래밍에 대해 훈련해보는 미션이라 요구사항에 비해 과도하게 느껴질 수도 있지만
말씀하신대로 하나의 책임을 가지는 클래스로 분리하여 구현해 보는게 목적입니다. 😄 

enum클래스로 계산기와 해당 Validation로직을 한 곳에서 관리하고 확장성을 높인것은 아주 좋아 보입니다. 👍👍
참고로 제가 생각했던 방향은 ParsedNumbers대신 PositiveNumbers같은 일급컬렉션 타입을 만들어서
생성자나 초기화 블럭에 양수 검증로직을 위치시켜 양수값을 보장하게 하고 양수간 합산기능도 제공하여
최대한 한곳에서 상태와 행위를 관리시켜 코드 응집성을 높여보자는 것이었습니다.
이 방법에 대해서 태형님은 어떻게 생각하시는지 의견을 들어보고 싶습니다. 😄

2024-05-06 08:21 UTC, HackSung commented on src/test/java/stringcalculator/StringCalculatorParserTest.java
> -import static org.assertj.core.api.AssertionsForClassTypes.assertThatExceptionOfType;
기존에 import static했던 Assertions클래스의 assertThat메서드를 제거하고
Assertions클래스를 매번 명시한 이유가 있으실까요?
import static을 사용한 기존 코드가 더 간결하고 가독성이 있지 않나해서요 🤔

2024-05-06 13:28 UTC, tongnamuu commented on src/main/java/stringcalculator/calculator/IntegerAdder.java
> +        return parsedNumbers.getIntegers().stream().filter(Objects::nonNull).reduce(0, Integer::sum);
수정했습니다

2024-05-06 13:28 UTC, tongnamuu commented on src/test/java/stringcalculator/StringCalculatorParserTest.java
> -import static org.assertj.core.api.AssertionsForClassTypes.assertThatExceptionOfType;
수정했습니다

2024-05-06 14:02 UTC, tongnamuu commented
> 참고로 제가 생각했던 방향은 ParsedNumbers대신 PositiveNumbers같은 일급컬렉션 타입을 만들어서
생성자나 초기화 블럭에 양수 검증로직을 위치시켜 양수값을 보장하게 하고 양수간 합산기능도 제공하여
최대한 한곳에서 상태와 행위를 관리시켜 코드 응집성을 높여보자는 것이었습니다.
이 방법에 대해서 태형님은 어떻게 생각하시는지 의견을 들어보고 싶습니다. 😄

파싱된 결과는 숫자범위에 대한 책임을 가지지 않는 것이 좋아보여서 파싱된 결과는 List<Integer> 혹은 List<Integer> 를 감싼 형태가 되야할 것 같습니다. 다른 사칙연산이 들어오더라도 파서는 그대로 사용할 수 있는게 좋을 것 같습니다. 
(만약 더 정교한 형태를 원한다면 수식트리를 만드는게 좋아보이긴 하지만 미션에서 시도할 만한 일은 아닌 것 같아서..)
 예를 들어 나눗셈이 추가된다고 했을 때, 말씀하신 PositiveNumbers 에는 음수만 처리되어있고 0에 대해서는 처리되지 않았기 때문에 divide 메서드를 추가할 수 없게 될 것 같습니다. 추가하더라도 divide 를 호출하기 전에 생성자의 validation 이 아닌 별도의 validation을 호출해야할 것 같습니다. 
PositiveNumbers 는 결국 현재 숫자범위에서 add 요구사항에만 맞는 유효한 클래스가 될 것 같습니다. 결국 사칙연산이 추가될 때마다 큰 리팩터링을 거치거나 사칙연산 추가에 따라 PositiveNumberAdder,   PositiveNumberMultiplier, PositiveNumberDivider.. 클래스가 늘어나게 되고, 0이상의 수가 아니라 전 범위의 수에 대해서도 가능하게 된다면 클래스의 validation 을 직접 다 수정하거나 validation 클래스로 만들게 되야해서 제가 작성한 enum 이랑 비슷하게 될 것 같고 
PositiveNumbers 는 현재 add는 잘 처리해주겠지만 Calculator 입장에서는 확장성이 낮아보입니다. 

제가 클래스로 안  만든 이유는 enum 에서 validator, calculator 를 갖고 있고 getResult 를 통해 무조건 validator 를 호출하고 그 결과를 calculator 로 넘기도록 강제할 수 있고, validator, calculator 조합을 파악하기 쉬워서 이렇게 했습니다.

2024-05-06 15:21 UTC, HackSung commented
네 좋은 의견 나눠주셔서 감사합니다. 🙏 
결국 어디까지 확장성을 염두에 두고 설계하느냐에 따라 구현은 달라질 수 밖에 없는 것이고
그 기준은 요구사항이나 상황에 따라 적절하게 선택하는게 개발자의 몫인 것 같습니다. 😄

2024-05-06 15:24 UTC, HackSung approved these changes
1단계 미션 잘 진행해 주셨습니다. 👍 
이제 2단계 미션으로 넘어가 볼까요? 🚀

2024-05-06 15:24 UTC, merged