🚀 2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #639
Opened 2024-05-06 11:35 UTC by gutenLEE

요구사항 정리할 때 도메인에 비즈니스 로직이 없어서  
service 레이어의 로직을 한글로 풀어썼습니다!

2024-05-06 17:11 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다.
함께 고민해 보고 싶은 부분은 코멘트나 DM 남겨주시면 좋을 것 같아요!

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +### 상품
요구 사항은 개발자가 아닌 모든 프로젝트 참여자가 읽는다고 생각해 주시면 좋을 것 같아요. :)

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +|---------|--------------|-----------------------|
용어 사전까지 작성해 주셨네요! 
이 부분은 다음 미션에서 진행할 예정입니다!

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +- 제품의 명칭은 욕설이 포함될 수 없다
명칭과 이름은 다른가요? 이 부분은 용어를 통일해 보는 것은 어떨까요? 
같은 의미를 가지는 여러 단어를 사용하면 헷갈릴 수 있을 것 같아요!

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +- 제품의 명칭은 욕설이 포함될 수 없다
```java
        if (Objects.isNull(name) || purgomalumClient.containsProfanity(name)) {
            throw new IllegalArgumentException();
        }
```

null 체크에 대한 부분이 요구 사항에 누락된 것 같아요.

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +
변경되면서 특정 조건에 따라서 Display 여부가 달라지는데요. 이 부분도 작성되어야 하지 않을까요?

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +
메뉴 상품에 대한 수량에 대한 제약 조건이 있는데 이 부분도 작성되어야 하지 않을까요?

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +- 메뉴는 하나의 메뉴그룹에 소속된다
이름, 가격 표시에 대한 조건들이 있는데 이 부분도 작성되어야 할 것 같아요.

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +    - 주문 타입은 null이 될 수 없다
요구 사항은 개발자만 읽는 것이 아니라고 생각해요. 그래서 모든 사람들이 이해할 수 있는 단어들이 사용 되어야 한다고 생각하는데요. `null`은 누구나 이해할 수 있는 개념일까요?

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +- 주문 테이블의 초기 상태는 인원 수는 0, 점유 false이다
`점유 여부를 false로 변경한다` 이 부분도 문장을 조금 다듬어 보는 것은 어떨까요?

2024-05-06 17:11 UTC, hyunssooo commented on README.md
> +  - 주문의 타입은 3가지가 있다 (DELIVERY, TAKEOUT, EAT_IN)
주문 타입 마다 변경될 수 있는 상태가 조금씩 차이가 있는데요. 
이를 명시해 보는 것은 어떨까요?

2024-05-08 13:39 UTC, hyunssooo approved these changes
안녕하세요. 
추가로 몇 가지 코멘트 남겼습니다.
다음 step 진행하시면서 확인 부탁드릴게요!

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +  - 상품의 이름은 욕설이 포함될 수 없다
상품과 메뉴 그룹은 이름 조건이 좀 다른데요. 상품은 빈 공백도 가능해 보이지 않나요?

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +  - 메뉴 상품의 상품 가격과 수량을 곱하면 메뉴의 가격이다
0개 이상 아닐까요? 
```java
            final long quantity = menuProductRequest.getQuantity();
            if (quantity < 0) {
                throw new IllegalArgumentException();
            }
```

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +  - 주문의 타입은 3가지가 있다 (DELIVERY, TAKEOUT, EAT_IN)
조금 더 자연스럽게 풀어낼 수 있을 것 같기도 해요. 

주문에는 `배달`, `주문 포장`, `매장 식사` 가 있다.

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +      - EAT_IN 주문은 추가로 SERVED 상태를 갖을 수 있다
조금 더 명확하게 타입마다 순서로 작성하는 것은 어떨까요?

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +    - 주문한 메뉴의 가격은 0보다 작을 수 없다
모든 주문은 배송지와 주문 테이블를 가지는 건 아닌 것 같은데 해당 문장은 모든 주문인 것 같아요.

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +
```suggestion
  - 주문 타입이 EAT_IN이면 주문 테이블의 인원 수는 0명, 테이블을 공석으로 변경한다

```

2024-05-08 13:39 UTC, hyunssooo commented on README.md
> +  - 인원수가 0명이라면 변경 불가능하다
`변경할 인원수` 라고 명시하는 것은 어떨까요? 0명인 경우에만 변경이 불가능한가요?

2024-05-08 13:39 UTC, hyunssooo commented on src/test/java/calculator/Number.java
>      }
💯

2024-05-08 13:39 UTC, merged

2024-05-08 15:49 UTC, gutenLEE commented on README.md
> +  - 메뉴 상품의 상품 가격과 수량을 곱하면 메뉴의 가격이다
아하 0보다 작으면이니까 이상이군요 ㅠ

2024-05-08 15:51 UTC, gutenLEE commented on README.md
> +  - 상품의 이름은 욕설이 포함될 수 없다
```java
    public static boolean isNull(Object obj) {
        return obj == null;
    }
```
아 null만 체크하는군요