Step2 - 요구사항 정리
next-step/ddd-legacy pull request #641
Opened 2024-05-06 13:36 UTC by sjhello

안녕하세요 리뷰어님.
이번 미션도 잘 부탁드립니다.

말씀하실게 있으시다면 편하게 말씀 부탁 드립니다!

2024-05-07 03:48 UTC, Hyeon9mak requested changes
안녕하세요 상진님! 요구사항 분석문서 잘 작성해주셨습니다.

요구사항 분석문서는 개발직군 뿐만 아니라 비개발직군도 함께 볼 수 있어야한다고 생각해요.
때문에 개발적인 내용은 최대한 덜어내고, 비개발직군도 함께 보고 크로스체크가 가능하도록
일반적인 상식을 이용해서 문서를 작성하는 것이 중요하다고 생각합니다. 😄

이와 관련하여 몇 가지 코멘트 남겼습니다!
궁금하신 점 언제든지 질문주세요~

2024-05-07 03:48 UTC, Hyeon9mak commented on README.md
> +        - [ ] 메뉴 그룹의 이름은 null 이거나 공백 일 수 없다.
요구사항 문서는 모든 동료, 팀원이 볼 수 있죠!
그런데 이 동료, 팀원에는 개발자 뿐만 아니라 기획자, Product owner 들도 포함된다고 생각합니다.
그들에게 이런 내용은 너무 어렵고 불친절한 내용으로 느껴질 것 같아요.

어느 누가 읽어도 일반적인 상식으로 이해할 수 있도록, 아래와 같이 표현해보는 건 어떨까요?

```
- 상품은 가격과 이름, 식별자로 이루어져 있다.
- 상품 이름에는 비속어가 포함되어선 안된다.
- 상품 가격은 0원 이상이다.
```

2024-05-07 03:48 UTC, Hyeon9mak commented on README.md
> +        - [ ] 메뉴에 등록 되는 상품을 메뉴 상품 이라고 하며 메뉴 상품은 하나 이상 등록 되어야 한다.
예시를 포함시켜주는 건 어떨까요?

```
예를 들어 `후라이드 치킨 세트` **메뉴**에는 `후라이드 치킨`과 `콜라`가 포함될 수 있다.
```

이런 예시를 추가한다면 팀원 전체의 생산성에 큰 기여를 하게 될 것 같아요 😄

2024-05-07 03:48 UTC, Hyeon9mak commented on README.md
> +        - [ ] 주문(배달)을 수락하면 키친 라이더에게 주문 id, 주문한 메뉴의 합계, 배달 주소를 전달한다.
각 타입의 주문을 서로 비슷한 종류의 주문으로 보지 않고 완전히 다른 개념으로 바라보면서
정말 필요한 정보만 다루고 불필요한 정보는 완전히 배제시켜주셨군요! 👍 👍 
요게 DDD 세레나데 강의의 핵심이라 생각됩니다 👍

요렇게 잘 분리된 요구사항 문서대로 클래스 파일을 나누면
각 주문이 서로 불필요한 정보를 인지하지 않고, 필요한 정보만 다루면서
복잡도를 획기적으로 낮출 수 있게 되겠네요 😄

2024-05-07 03:48 UTC, Hyeon9mak commented on http/orders.http
> +
분기된 주문만큼 http 요청을 더 세분화하여 추가해주셨군요~ 💯

2024-05-07 16:04 UTC, sjhello commented on README.md
> +        - [ ] 상품의 이름은 공백이 될 수 있다.
http로 테스트를 하다보니 이러한 동작도 가능하더라구요..

현실적으로 생각하였을때 상품의 이름이 공백이 될 수는 없을 거 같은데 이걸 요구사항으로 넣는게 맞는지 잘 모르겠네요 🤔

2024-05-07 16:08 UTC, sjhello commented on README.md
> +    - [ ] 손님의 식사가 완료된 경우가 아니라면 테이블을 비울 수 없다.
order_table의 속성중에 occupied 속성이 있더라구요. 
저는 이것을 `손님이 테이블에 앉아 식사하는 상태`, 혹은 `테이블에서 식사를 다 마친 상태`로 보았는데

리뷰어님의 생각이 궁금합니다 😃

2024-05-07 16:17 UTC, sjhello commented on README.md
> +        - [ ] 메뉴 그룹의 이름은 null 이거나 공백 일 수 없다.
세상에.... https://www.purgomalum.com 에서 어떤 값들을 검증하는지 자세히 보지 않았네요...
단순하게 Service 소스를 보고 외부 api에서 true가 리턴되는 것들은 이름으로 등록이 되면 안되는구나... 생각하고 너무 단순하게(개발자 마인드!!)로 작성하였네요 😂

이런 자세한 구현사항은 직접 저 api에 들어가서 확인하기 전까지는 http 파일을 이 케이스 저 케이스 테스트 하더라도 잡아내기 어려웠을거 같아요!

리뷰어님 말씀대로 팀원들이 읽었을때 거부감이 없는 말로 문서를 작성하는 것이 더 좋은 요구사항 정리가 될 거 같습니다😃

2024-05-07 16:18 UTC, sjhello commented on http/orders.http
> +
나중에 이러한 정보를 바탕으로 인수 테스트를 작성 해 볼수도 있을까요!?

2024-05-07 16:23 UTC, sjhello commented
안녕하세요 리뷰어님
피드백 주신 부분에 대해서 보충하여 추가 push 하였습니다!

step2를 진행하면서 나름대로 어떤 순서로 요구사항을 정리 하였는지 정리 해보았는데요.

1. http 파일을 확인하고 실행해본다.
2. 테이블에 데이터를 확인해본다.
3. Service 코드를 확인해본다.

2번을 제외하고는 뭔가 Controller - Service의 흐름대로 가면서 동작한대로 잘 흘러가는지 확인해본거 같아요.
`리뷰어님은 어떤 방식으로 진행하셨었는지`와 `레거시 코드의 요구사항을 파악할때 더 나은 방법이 있는지` 가 궁금합니다 :)

2024-05-08 03:34 UTC, Hyeon9mak approved these changes
안녕하세요 상진님! 요구사항 문서가 훨씬 읽기 쉬워졌네요 👍 👍 
다른 직군, 주변 친구에게 넘겨줘도 무슨 의미인지 바로 이해할 수 있겠어요.
바로 다음 단계로 넘어가시죠 😄 👍

2024-05-08 03:34 UTC, Hyeon9mak commented on README.md
> +        - [ ] 상품의 이름은 공백이 될 수 있다.
아주, 아주아주아주아주! 잘 짚어주셨습니다!!
DDD 세레나데 미션에서는 의도적으로 잘못 구현된 것들도 많이 포함되어 있습니다.
현실적으로 잘못된 동작을 '어.. 일단 요구사항이니까 구현하면 되겠지.' 라는 건 아쉽죠!
제품에 애정을 갖고 '이상한데? 공백이 말이 되나?' 의심하고 프로그램을 수정하시는 분들이 정말 프로라고 생각해요! 👍 👍

2024-05-08 03:34 UTC, Hyeon9mak commented on README.md
> +            - 예를 들어 `후라이드 1 + 1`의 가격은 19000원이고, `후라이드` 상품의 가격이 한 마리당 2000원으로 변경 되었을때 메뉴를 숨김 처리 한다.
😉 👍

2024-05-08 03:34 UTC, Hyeon9mak commented on README.md
> +            - [ ] `후라이드 세트` 메뉴에는 `후라이드`와 `콜라`가 포함 될 수 있다.
수량은 최소 몇개인지.. 요런 것도 궁금하네요 😄

2024-05-08 03:34 UTC, Hyeon9mak commented on README.md
> +    - [ ] 주문 테이블의 목록을 볼 수 있다.
👍 👍

2024-05-08 03:34 UTC, Hyeon9mak commented on README.md
> +    - [ ] 손님의 식사가 완료된 경우가 아니라면 테이블을 비울 수 없다.
굳이 직역하자면 `점유하다` 인데, 저도 상진님처럼 해석할거 같습니다 😄

2024-05-08 03:34 UTC, Hyeon9mak commented on http/orders.http
> +
물론입니다!!!!!!! 요렇게 해주신 덕분에 인수 테스트 작성도 훨씬 쉽죠!!

2024-05-08 03:34 UTC, merged