step2: 요구 사항 정리
next-step/ddd-legacy pull request #645
Opened 2024-05-07 11:49 UTC by wsdf25867

안녕하세요

요구 사항 정리 리뷰 요청드립니다!

2024-05-07 15:49 UTC, kyucumber requested changes
안녕하세요.

요구사항 정리 잘 해주셨습니다.

조금 더 구체적으로 정리될 필요가 있을 것 같습니다. 주문 도메인을 제외하고 코멘트를 남겨드렸으니 참고해서 주문쪽 요구사항도 조금 더 구체적으로 정리해보시면 좋을 것 같네요. 🙇

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 메뉴는 이름, 가격, 메뉴그룹 아이디, 보여줄지 여부, 메뉴상품목록을 갖는다
메뉴 이름에 비속어가 포함되면 안된다는 요구사항이 정의될 수 있을 것 같네요.

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 메뉴를 보여줄 수 있다
메뉴의 가격이 속한 상품 금액의 합보다 큰 경우도 메뉴를 노출할 수 있을까요?

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 메뉴 가격을 수정할 수 있다
현실 세계에서 보면 당연한 부분이긴 하지만, 도메인에 대한 요구사항을 정리할 때 가격 수정 시 -1이나 0과 같은 값으로도 수정할 수 있을지에 대한 부분까지도 정리해볼 수 있을 것 같네요!

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 손님의 수를 수정할 수 있다
빈 테이블도 손님 수를 변경할 수 있나요?

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 테이블을 비울 수 있다
완료되지 않은 주문이 있는 경우도 빈 테이블로 설정할 수 있나요?

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 상품의 가격을 수정할 수 있다
상품 가격 수정 시 메뉴가 영향받는 부분은 없을까요?

2024-05-07 15:49 UTC, kyucumber commented on README.md
> +  - [ ] 메뉴는 이름, 가격, 메뉴그룹 아이디, 보여줄지 여부, 메뉴상품목록을 갖는다
https://github.com/next-step/ddd-legacy/blob/433309950c06f58f9295039df8c940d7df142b54/src/main/java/kitchenpos/application/MenuService.java#L78

위 요구사항에 대해서도 정리할 수 있을까요?

2024-05-08 11:51 UTC, wsdf25867 commented
리뷰 내용 반영 및 요구사항 좀 더 구체적으로 정리해 봤습니다

`.http` 파일만 보고 작성했던거 같네요 좀 더 침착하고 자세하게 살펴봐야 했었습니다

요구사항 자세하게 안내해주셔서 감사합니다!!

2024-05-09 12:41 UTC, kyucumber approved these changes
요구사항 잘 정리해주셨습니다.

간단한 몇가지 코멘트 남겨두었으니 참고 부탁드려요.

이는 다음 단계에 반영해주시면 될 것 같습니다. 다음 단계 진행을 위해 머지할게요.

2024-05-09 12:41 UTC, kyucumber commented on README.md
> +- 주문
잘 정리해주셨는데, 각 주문 타입(배달, 매장, 포장)에 대한 주문 상태 흐름이 잘 보이지 않는 것 같아요.

요구사항을 보고 도메인을 한눈에 이해할 수 있도록 아래와 같은 흐름도 같이 추가하면 어떨까요?

- 배달
  - 수락 -> 배달 시작 -> 배달 완료

2024-05-09 12:41 UTC, kyucumber commented on README.md
> +  - [ ] 주문 배달을 시작할 수 있다
배달 주문이 접수되면 배달 대행사를 호출하는 부분도 요구사항에 포함되어야 할 것 같아요.

2024-05-09 12:41 UTC, kyucumber commented on README.md
> +- 주문
주문 항목의 수량을 검증하는 부분이 있었던 것 같은데요 그 부분도 요구사항에 추가하면 어떨까요~?

2024-05-09 12:41 UTC, merged