🚀 1단계 - 문자열 덧셈 계산기
next-step/ddd-legacy pull request #649
Opened 2024-05-08 04:37 UTC by NoJaeHyuk

# 1단계 - 문자열 덧셈 계산기

총 요구사항은 3가지로 구분하여 진행하였습니다. 
- 기본 구분자을 이용한 계산 
- 커스컨 구분자 추가 
- 숫자 이외의 값 또는 음수처리 

아직 객체지향적인 코드와 TDD 방식이 익숙하지 못해 
StringCalculator 클래스에 요구사항 테스트 코드를 작성하면서 add() 메서드에 우선 구현 후 
리펙토링을 통해 메서드 분리 및 클래스 분리를 하였습니다. 

0단계 때 커밋 메세지에 구분점을 명확하게 표현하는 연습을 하라고 하셔서 나름 구분했는데 현 커밋 메세지에서 보강해야될 점 
피드백  부탁드립니다. 

감사합니다.

2024-05-08 17:08 UTC, Hyeon9mak requested changes
안녕하세요 재혁님! 문자열 덧셈 계산기 잘 구현해주셨습니다.

> StringCalculator 클래스에 요구사항 테스트 코드를 작성하면서 add() 메서드에 우선 구현 후
리펙토링을 통해 메서드 분리 및 클래스 분리를 하였습니다.

💯 💯 💯 객체지향이 뭣이 중헙니까! 요렇게 차분히 구현해주시는 것이 중요하지요 😄 
결국 객체지향이라는 것은 유지보수를 위함이므로, 유지보수 하기 좋은 코드 작성을 위해 노력해주셨다면 그걸로 이미 충분하다 생각합니다!

커밋 단위도 굉장히 잘 분리해주신 것 같아요!
작업 단위를 잘 명세하고 작성해주신 덕분에 롤백 지점을 잡기 굉장히 용이할 것 같은데요? 😄 👍 

대신 미션 진행을 위해 rebase 하는 법에 대해 조금만 다듬어보면 좋을 것 같아요 😉 
https://github.com/next-step/nextstep-docs/blob/master/codereview/review-step3.md

그 외 간단한 코멘트들 남겼으니 확인해주세요!

2024-05-08 17:08 UTC, Hyeon9mak commented on src/test/java/springcalculator/Delimiter.java
> +    private static final String CUSTOM_DELIMITER_PATTERN = "//(.)\n(.*)";
구분자들을 상수로 만들어 이름을 부여해주셨군요 👍

2024-05-08 17:08 UTC, Hyeon9mak commented on src/test/java/springcalculator/Delimiter.java
> +        Matcher matcher = Pattern.compile(CUSTOM_DELIMITER_PATTERN).matcher(input);
매 연산마다 `Pattern` 인스턴스가 생성되는데요, `Pattern` 자체를 상수로 만들어 관리하는건 어떨까요? 😄

2024-05-08 17:08 UTC, Hyeon9mak commented on src/test/java/springcalculator/Delimiter.java
> +            input = matcher.group(2);
1, 2 가 어떤 의미를 갖는지 상수로 이름을 부여해보는 것도 좋겠어요!

2024-05-08 17:08 UTC, Hyeon9mak commented on src/test/java/springcalculator/StringCalculator.java
> +    }
stream API 의 sum 을 이용해봐도 좋겠네요 😄 👍 

```java
    public int add() {
        return numbers.stream()
                .mapToInt(Integer::intValue)
                .sum();
    }
```

2024-05-08 17:08 UTC, Hyeon9mak commented on src/test/java/springcalculator/StringCalculatorTest.java
> +    }
숫자가 아닌 나머지 값을 입력한 경우는 어떻게 될까요?

2024-05-09 03:44 UTC, NoJaeHyuk commented
rebase를 안하고 다음 미션 진행하면 이전 미션 커밋이 붙는군요. 
다음 미션 진행에 있어 주의하도록 하겠습니다. 

피드백 사항 적용하였습니다.

1. 의미를 파악하기 힘든 단어들(1,2) 상수 처리하여 읽기 쉬운 코드 정의 
2. 자주사용되는 코드 및 매 연산에 활용되는 변수 상수 처리하여 성능적 비효율 개선 및 재사용코드 안정성 확보 
3. 연산 로직 스트림으로 변경하여 간결성, 가독성, 성능 개선

2024-05-11 07:43 UTC, Hyeon9mak approved these changes
안녕하세요 재혁님! 리뷰가 많이 늦었습니다 😭 🙏 
피드백 잘 반영해주셨습니다!
rebase 도 잘 적용해주신 덕분에 이번 PR 에서 작업해주신 전체 내역을 더 쉽게 확인할 수 있게 되었네요!
바로 다음 단계로 넘어가시죠 😄 👍

2024-05-11 07:43 UTC, Hyeon9mak commented on src/test/java/springcalculator/Delimiter.java
> +            input = matcher.group(INPUT_GROUP_INDEX);
😉 더 명확하게 의도를 전달해주네요!

2024-05-11 07:43 UTC, Hyeon9mak commented on src/test/java/springcalculator/StringCalculatorTest.java
> +    }
😉 👍

2024-05-11 07:43 UTC, merged