🚀 2단계 - 요구 사항 정리
next-step/ddd-legacy pull request #654
Opened 2024-05-08 17:21 UTC by jiokim

안녕하세요 리뷰어님.

🚀 2단계 - 요구 사항 정리 리뷰 요청드립니다.

2024-05-09 10:26 UTC, hyunssooo requested changes
안녕하세요. 
요구 사항 정리 꼼꼼하게 잘 해주셨습니다! 
몇 가지 가벼운 코멘트 남겼는데요. 
확인 부탁드려요!

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +> #### kitchenpos 주문 서비스를 구현한다.
요구 사항은 개발자가 아닌 모든 프로젝트 참여자가 읽는다고 생각해 주시면 좋을 것 같아요. :)

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +- 주문완료(COMPLETED)
주문 종류 별로 가질 수 있는 주문 상태를 각각 나열해 보는 것은 어떨까요?

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +            - [ ] 주문타입이 테이크아웃이거나 배달이면 수량은 1개 이상이여야한다.
```java
for (final OrderLineItem orderLineItemRequest : orderLineItemRequests) {
    final long quantity = orderLineItemRequest.getQuantity();
    if (type != OrderType.EAT_IN) {
        if (quantity < 0) {
            throw new IllegalArgumentException();
        }
    }
```

`OrderLineItem` 의 수량을 의미하는 것이 맞다면 수량 부분은 다시 확인해 보면 좋을 것 같아요.

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +    - [ ] 주문상태가 대기중상태일경우 주문 접수가 가능하다.
모두가 읽는 문서이니 맞춤법은 조금 신경 써도 좋을 것 같습니다!

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +    - [ ] 주문상태를 주문완료 상태로 변경한다.
매장 식사 주문을 완료하는 경우 매장 테이블에 대한 변경이 있는데요. 이 부분을 명확히 작성해 보는 것은 어떨까요?

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +- 상품가격을 변경한다.
상품의 이름은 비어있는 경우도 가능하지 않나요?

2024-05-09 10:26 UTC, hyunssooo commented on README.md
> +
상품의 가격이 변경된다면 해당 상품이 속해있는 `메뉴`의 `표시 여부`가 변경되는데요. 이를 명확하게 작성해 보는 것은 어떨까요?

2024-05-10 19:12 UTC, jiokim commented on README.md
> +- 상품가격을 변경한다.
``` java
final String name = request.getName();
if (Objects.isNull(name) || purgomalumClient.containsProfanity(name)) {
    throw new IllegalArgumentException();
}
```
이름이 빈 경우는 예외처리한다고 확인했습니다.

2024-05-11 01:10 UTC, hyunssooo commented on README.md
> +- 상품가격을 변경한다.
아 요거 제가 설명이 부족했네요. `""` 이 경우를 말했어요!

2024-05-11 13:31 UTC, hyunssooo approved these changes
안녕하세요. 
요구 사항 정리 잘 진행해 주셨습니다! 
다음 step 진행 부탁드릴게요!

2024-05-11 13:32 UTC, merged

2024-05-11 13:33 UTC, hyunssooo commented on README.md
> +```
mermaid 👍