[step2] 요구 사항 정리
next-step/ddd-legacy pull request #656
Opened 2024-05-09 11:50 UTC by hoa0217

두번째 미션 완료하여 PR올립니다 리뷰어님!

고민이 되었던 부분은 사용자에 대한 정의가 없어서 임의로 업주, 손님을 가정하고 작성하였는데

작성하다보니 `손님은 display된 메뉴 목록만 볼 수 있다.`라는 요구사항이 필요해보이더라구요.

그래서 코드상에는 조회하는 User에 맞게 메뉴를 조회하는 API가 없지만 임의로 요구사항을 추가해보았습니다.

이번 미션도 잘부탁드립니다~

2024-05-10 08:24 UTC, sah3122 requested changes
요구사항 정리 잘해주셨네요 👍 
몇가지 고민거리를 남겨두었는데 확인부탁드려요 🙏

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 업주는 상품을 생성하고 가격을 수정할 수 있다.
두가지 이상의 요구사항을 한문장으로 나타내기 보단, 요구사항을 각각 정의하여 보는건 어떨까요 ? 
문장을 나누어 작성하다 보면 새로운 용어를 발견하거나 세분화된 요구사항을 정의할수 있을것 같습니다 😄

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 업주는 모든 상품 목록을 볼 수 있다.
`Actor`를 정의 해주셨는데, 상품에 대한 조회는 업주 뿐만이 아니라 손님도 가능하지 않을까요 ?

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 업주는 상품을 생성하고 가격을 수정할 수 있다.
상품 가격 변경에 대한 요구사항을 다시 한번 확인해보세요 !

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 메뉴는 카테고리(메뉴 그룹)으로 묶을 수 있다.
메뉴를 메뉴 그룹으로 묶는다는 표현보단 `메뉴는 메뉴 그룹에 속해야한다.`라는 문장으로 표현하는건 어떨까요 ?

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 메뉴는 손님들에게 `display`할 수도 있고 숨길 수 도 있다.
요구사항 문서는 용어사전을 정의하지 않았다고 가정하여, `display`와 같이 표현하기 보다는 일반적인 문장으로 표현해보세요 ! 
`display`와 같이 표현하는건 모델링 과정이 더 어울릴것 같습니다 😄

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 업주는 중간에 메뉴 가격을 수정할 수 있으나, 이 때도 총가격은 0보다 작을 수 없으며 `상품가격 * 상품갯수`의 총합을 넘을 수 없다.
```suggestion
  - [ ] 업주는 메뉴 가격을 수정할 수 있다. 
      - [ ] 가격은 0보다 작을 수 없으며 메뉴의 가격은 포함된 상품가격의 총합을 넘을 수 없다.
```
문장을 단순하게 나누는것도 좋을것 같아요 😄

2024-05-10 08:24 UTC, sah3122 commented on README.md
> +  - [ ] 서빙 또는 배달이 완료 된 경우 업주는 주문을 완료(`COMPLETED`) 시킨다.
요구사항을 나누어 정리해보세요 😄 
요구사항 문서를 기반으로 테스트코드 작성, 용어사전, 모델링 과정을 경험하게 될것입니다 !

2024-05-11 12:50 UTC, hoa0217 commented on README.md
> +  - [ ] 업주는 모든 상품 목록을 볼 수 있다.
이부분 제가 잘못파악했습니다! 애초에 포스기이기때문에, 손님은 사용할 수 없는 시스템인데 키오스크로 잘못이해하였습니다!!! 수정하겠습니다

2024-05-11 12:50 UTC, hoa0217 commented on README.md
> +  - [ ] 업주는 상품을 생성하고 가격을 수정할 수 있다.
넵 맞습니다 상품가격이 변경되면 메뉴에 대한 가격 Validation도 필요한데, 나눠서 정의하겠습니다!

2024-05-11 12:51 UTC, hoa0217 commented on README.md
> +  - [ ] 메뉴는 카테고리(메뉴 그룹)으로 묶을 수 있다.
1:N관계를 표현할 언어를 찾다보니 묶는다는 표현을 썼는데 수정하겠습니다 ㅎㅎ

2024-05-11 12:52 UTC, hoa0217 commented on README.md
> +  - [ ] 메뉴는 손님들에게 `display`할 수도 있고 숨길 수 도 있다.
넵 노출한다는 표현이 적당하겠네요~~

2024-05-11 12:56 UTC, hoa0217 commented on README.md
> +  - [ ] 업주는 중간에 메뉴 가격을 수정할 수 있으나, 이 때도 총가격은 0보다 작을 수 없으며 `상품가격 * 상품갯수`의 총합을 넘을 수 없다.
넵 분리해보겠습니다!!

2024-05-11 12:57 UTC, hoa0217 commented on README.md
> +  - [ ] 서빙 또는 배달이 완료 된 경우 업주는 주문을 완료(`COMPLETED`) 시킨다.
요구사항을 나누어 정리해보라는게 위에 처럼 문장을 분리해보라는 의미이겠죵? 테스트코드 작성요구사항이라고 생각하니 확 와닿네요~~~!! 수정해보겠습니다 😄

2024-05-11 15:01 UTC, hoa0217 commented
## 작업 내역
- [x] 상품 가격 변경 로직 확인 및 요구사항 수정
- [x] 손님 Actor 제거
- [x] 단어 변경: display ➡️ 노출, 묶는다 ➡️ 속한다.
- [x] 주문 타입에 따른 프로세스를 분리하여 주문 요구사항 재작성

2024-05-12 06:40 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
작성해주신 요구사항을 기반으로 테스트 코드를 작성해보세요 😄

2024-05-12 06:40 UTC, merged