Step1 문자열 덧셈 계산기
next-step/ddd-legacy pull request #657
Opened 2024-05-09 14:57 UTC by bkRyusim

안녕하세요 리뷰어님! Step 1인데 리뷰 요청이 너무 늦었습니다 ㅠㅠ😭
항상 리뷰해 주셔서 감사합니다!

2024-05-10 09:15 UTC, liquidjoo requested changes
안녕하세요 승윤님 :)
1단계 미션 잘 구현해주셨어요 👍 
몇 가지 코멘트 남겼는데요 확인하고 다시 요청 주세요 🙇

2024-05-10 09:15 UTC, liquidjoo commented on src/test/java/calculator/NonNegativeNumber.java
> +	public static NonNegativeNumber from(final String inputValue) {
정적팩토리 메서드 패턴을 사용한 이유를 알 수 있을까요?
언제 사용하면 좋을까요?

2024-05-10 09:15 UTC, liquidjoo commented on src/test/java/calculator/Numbers.java
> +	}
정적팩토리 메서드 패턴을 사용한 이유를 알 수 있을까요?

2024-05-10 09:15 UTC, liquidjoo commented on src/test/java/calculator/Splitter.java
> +		System.out.println(Strings.join(delimiters, '|'));
사용하지 않는 것은 제거해주면 좋을 것 같아요 :)

2024-05-10 09:15 UTC, liquidjoo commented on src/test/java/calculator/StringCalculatorTest.java
> +		assertThat(stringCalculator.calculate(null)).isEqualTo(0);
asssertAll 을 활용해보는 것도 좋을 것 같아요 :)

2024-05-10 10:13 UTC, bkRyusim commented on src/test/java/calculator/NonNegativeNumber.java
> +	public static NonNegativeNumber from(final String inputValue) {
객체 생성 시에 검증이 들어가거나, 값을 가공해야 하는 경우에 정적 팩토리 메서드를 사용해 생성시 추가적인 로직을 캡슐화하기 위해 사용했습니다. 조금 과한 결정이었을까요..?

2024-05-10 10:14 UTC, bkRyusim commented on src/test/java/calculator/StringCalculatorTest.java
> +		assertThat(stringCalculator.calculate(null)).isEqualTo(0);
감사합니다 적용해 보겠습니다!

2024-05-10 10:14 UTC, bkRyusim commented on src/test/java/calculator/Splitter.java
> +		System.out.println(Strings.join(delimiters, '|'));
앗 놓쳤습니다 ㅠㅠ 제거하겠습니다!

2024-05-10 10:28 UTC, bkRyusim commented
안녕하세요. 리뷰 받고 나서 정적 팩토리 메서드에 대해 조금 더 공부해 보았습니다.🔥

- 객체를 생성하는 행위가 이름을 가질 수 있어 가독성이 좋아지고 의미 파악이 쉬워집니다.
- 꼭 인스턴스를 새로 생성하지 않아도 됩니다. 예를 들어, 값 객체등을 생성할 때 반복적으로 자주 생성되는 객체를 미리 생성해 두고, 정적 팩토리 메서드로 반환하면 메모리를 절약할 수 있습니다.
- 꼭 해당 클래스 타입의 객체를 반환하지 않을 수 있습니다. 예를 들어, 객체의 하위 타입을 생성하거나, 파라미터에 따라 다른 타입의 인스턴스를 반환하는 등 생성자에 비해 유연하게 사용할 수 있습니다.

2024-05-11 14:06 UTC, liquidjoo approved these changes
안녕하세요 승윤님 
1단계 피드백 잘해주셨어요 👍 
코멘트로 답변을 남겨 놓았습니다~
다음 단계 진행해 주세요 🙇

2024-05-11 14:06 UTC, liquidjoo commented on src/test/java/calculator/NonNegativeNumber.java
> +	public static NonNegativeNumber from(final String inputValue) {
개인적인 의견일 수 있습니다만!
생성자 제어가 필요하고 여러 생성자를 오버로딩하게 되었을 때 비로소 필요하다고 생각이드네요 :)
물론 정적팩토리 메서드 패턴을 사용하게 될 경우 기본 생성자는 막아줘야 혼동이 없을 것이라고 생각이 듭니다

2024-05-11 14:06 UTC, merged