3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #665
Opened 2024-05-10 16:01 UTC by jinyoonYang

공유주신 슬랙 브랜치 생성 방법으로 다시 따서 진행해서 그런지 ;; step 1, step2에 반영한 파일도 변경이력으로 같이 올라갔는데 참고 부탁드립니다. (왜 diff에 걸리는지 모르겠네요 ㅠㅠ)

test 폴더로 최대한 모든 케이스에 대한 테스트 코드를 작성해보았습니다. 
컨트롤러 쪽 테스트 코드는 PR 피드백 받고 작성하려고 합니다🙇‍♀️

2024-05-11 14:41 UTC, Gomding requested changes
안녕하세요 진윤님!
3단계도 빠르게 진행해주셨네요 🤗
몇가지 코멘튼 남겼으니 확인부탁드려요 :)

궁금한 점 있으면 언제든 DM 남겨주세요~

2024-05-11 14:41 UTC, Gomding commented on README.adoc
> +** 데이터 구성 : 메뉴카테고리 이름
데이터는 개발자 관점의 키워드라고 느껴져요!

여러 이해관계자가 도메인 지식을 동일하게 이해하고 말할 수 있도록
개발자 중심의 키워드는 제거해보죠 😉

> 메뉴 카테고리는 이름을 가진다.

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +}
파일 끝에 개행이 없어서 github file-change 상에서 경고가 표시되는데
아래 글을 참고해서 개행이 자동으로 추가되도록 해보죠!

- [intellij 파일끝에 개행을 자동으로 추가하는 방법](https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95)

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/helper/MenuGroupTestHelper.java
> +public class MenuGroupTestHelper {
Helper 를 사용한 테스트 객체 생성 👍

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/fakeClient/FakePurgomalumClient.java
> +public class FakePurgomalumClient extends PurgomalumClient {
Fake 객체를 사용해주셨군요 👍 👍 👍 👍

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/config/MenuTestContextConfiguration.java
> +        return new FakePurgomalumClient(new RestTemplateBuilder());
PurgomalumClient 를 interface 로 만든다면 RestTemplateBuilder 를 주입받을 필요도 없을것같은데 어떻게 생각하시나요?

```java
interface 비속어검사Client {

}

class PurgomalumClient implements 비속어검사Client {

}
```

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/config/MenuTestContextConfiguration.java
> +    public PurgomalumClient purgomalumClient(){
PurgomalumClient 는 어떤 뜻을 가지고 있을까요?

+) 진윤님이 정리하신 도메인 모델의 이름과 일치하고 있을까요?

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/SetupTest.java
> +@SpringBootTest
`@SpringBootTest` 를 사용한 통합테스트는 실제 환경과 비슷하게 테스트를 실행할 수 있지만
테스트 개수가 많아질수록 속도가 오래걸린다는 단점이 있죠!

속도가 빠른 가짜 객체를 활용한 테스트도 있을텐데
통합테스트를 진행하신 이유가 궁금해요!

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        추천메뉴 = MenuGroupTestHelper.메뉴카테고리_생성("추천메뉴");
한글 이름으로 작성해주셔서 읽기가 더 좋네요 👍 👍 👍 👍

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("특정 메뉴카테고리에 음식메뉴를 조합한 신규 메뉴를 추가한다.")
테스트 이름을 정리해주신 요구사항과 통일시켜보는건 어떻게 생각하시나요?

```suggestion
    @DisplayName("매장주인은 특정 메뉴 카테고리에 음식을 조합해서 메뉴를 등록할 수 있다.")
```

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("등록하려는 메뉴 이름에 비속어가 있는 경우 IllegalArgumentException 예외가 발생한다.")
👍 👍 👍 👍

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("특정 메뉴의 가격을 변경한다.")
`@Nested` 애너테이션을 활용해서 [계층 구조의 테스트](https://johngrib.github.io/wiki/junit5-nested/)를 작성해볼 수도 있어요!

2024-05-11 14:41 UTC, Gomding commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +        //given && when
BDD 패턴으로 작성해주셨군요 👍

2024-05-14 12:31 UTC, jinyoonYang commented on src/test/java/kitchenpos/config/MenuTestContextConfiguration.java
> +        return new FakePurgomalumClient(new RestTemplateBuilder());
수정해보았습니다~! 

dbRepository도 인터페이스로 리팩토링해서 가짜 객체를 가져다 테스트하도록 개선해보고도 싶었으나 리팩토링을 작업하는 과정에서 
기존 실제데이터를 기준으로 테스트가 성공하는 통합테스트를 인수테스트로 작성해두고 리팩토링 진행하면서 단위테스트로 나누는게 좋을 것 같다는 판단이 들어 로직 유지해두었습니다.

2024-05-14 12:37 UTC, jinyoonYang commented on src/test/java/kitchenpos/config/MenuTestContextConfiguration.java
> +    public PurgomalumClient purgomalumClient(){
아항 메인 소스의 클래스 명을 그대로 따라갔는데 수정하는게 더 의미가 있겠네용 ! 
profanityClient으로 변경했습니당

2024-05-14 12:38 UTC, jinyoonYang commented on src/test/java/kitchenpos/application/SetupTest.java
> +@SpringBootTest
https://github.com/next-step/ddd-legacy/pull/665/#discussion_r1599946408

이런 생각이 들어 리팩토링을 진행하기 전에 보호막으로써 작업하는 테스트 코드라 통합테스트가 더 안전할 것 같단 생각으로 진행하게 되었습니당 ~!

2024-05-14 12:44 UTC, jinyoonYang commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("특정 메뉴카테고리에 음식메뉴를 조합한 신규 메뉴를 추가한다.")
추가 대신 등록으로 표현하는게 맞겠네용 
수정했습니다!

2024-05-14 14:42 UTC, jinyoonYang commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    @DisplayName("특정 메뉴의 가격을 변경한다.")
어느 정도까지 계층구조로 작성해야 될지 기준이나 예시가 있다면 함께 공유 부탁드립니당 ㅠㅠ 
일단 예외케이스로 1개이상의 테스트 케이스를 작성한 경우 @Nested로 묶어서 표현해보았습니당

2024-05-15 13:07 UTC, Gomding commented on src/main/java/kitchenpos/infra/PurgomalumClient.java
> +public interface PurgomalumClient {
`Purgomalum` 은 어떤 의미를 가지고 있을까요!
진윤님이 의도한것은 비속어 검사를 하는 주체라고 생각하는데
메서드 이름처럼 `ProfanityClient` 또는 `ProfanityChecker` 라는 이름으로도 표현 가능할 것 같아서요!
(Purgomalum 은 비속어 검사해주는 서비스 이름이 아닐까요..! 😃 )

2024-05-15 13:07 UTC, Gomding commented on src/test/java/kitchenpos/config/MenuTestContextConfiguration.java
> +        return new FakePurgomalumClient(new RestTemplateBuilder());
말씀하시는 인수 테스트가 API 를 호출하는 시나리오 테스트가 맞을까요?🧐

2024-05-15 13:12 UTC, Gomding commented on src/test/java/kitchenpos/config/MenuTestContextConfiguration.java
> +    public PurgomalumClient purgomalumClient(){
해당 부분 관련해서 코멘트 남겼으니 확인 부탁드려요! 🤗

2024-05-15 13:16 UTC, Gomding approved these changes
안녕하세요 진윤님!
이번 미션 진행하느라 고생하셨어요 🤗
충분히 진행하신것 같아 이만 merge 하겠습니다!
마지막으로 코멘트 남겼으니 확인해주세요~

관련해서 궁금한 점 있으면 언제든 편하게 DM 보내주세요!!

2024-05-15 13:16 UTC, merged