🚀 3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #669
Opened 2024-05-11 15:11 UTC by gutenLEE

- 도메인에 비즈니스 로직이 없어 도메인에 대한 단위테스트는 작성하지 않았습니다. 
서비스 통합테스트만 작성했습니다!

2024-05-11 15:16 UTC, gutenLEE commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
Order 테스트를 위해 필요한 픽스처들이 MenuGroup, OrderLineItem, OrderTable, Menu 등 많다보니 Order의 세부 비즈니스 로직을 테스트를 작성하기가 어려웠습니다. 

예를 들면 create() 메서드에는 menu 검증, 수량 검증, 전시 상태 검증 등등 여러 관련 도메인의 로직이 섞여있는데요, 
통합테스트에서는 이 관련 도메인의 로직도 OrderService에 작성하는게 적절한가 의문이 들었습니다. 

```markdown
  - 주문은 여러 개의 주문한 메뉴를 갖는다
    - 주문은 메뉴를 최소 1개 갖는다
    - 주문한 메뉴는 등록되어 있는 메뉴여야 한다
    - 감추기된 메뉴가 주문될 수 없다
    - 주문한 메뉴의 가격은 0보다 작을 수 없다
```

2024-05-12 13:54 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 확인 부탁드려요.

2024-05-12 13:54 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
메뉴 생성에는 여러가지 조건이 있는데 이를 테스트로 작성해야 하지 않을까요? 
성공하는 케이스 실패하는 케이스 모두 작성되면 좋을 것 같아요. 
메뉴뿐 아니라 전체적으로 확인이 필요해 보여요. 
`@Nested` 를 통해 depth로 표현해 보아도 좋을 것 같아요. 

```md
- 주문을 등록할 수 있다. 
  - 배달 주문인 경우 주소 정보가 없으면 등록할 수 없다. 
```

레거시 코드에 대한 테스트를 통해 비즈니스를 좀 더 깊게 파악할 수 있는 기회라고 생각해요. :) 

> 모든 Business Object에 대한 테스트 코드를 작성한다.

2024-05-12 13:54 UTC, hyunssooo commented on src/main/java/kitchenpos/domain/Order.java
> +    }
entity는 동등성을 위해 전체 필드를 모두 비교해도 괜찮을까요? 이 부분은 어떻게 생각하시나요?

2024-05-12 13:54 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
테스트를 실행해 보셨을까요?

2024-05-12 13:54 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    void createEatInOrderFailWhenOrderTableTest() {
문맥이 통일되어도 좋을 것 같아요. 
`예외가 발생한다.` 이 부분은 요구 사항 보다는 개발에 가까운 용어로 느껴지네요. 
테스트이지만 모든 사람이 이해할 수 있으면 더 좋지 않을까요? 

아래에 `"매장 식사 주문은 주문 테이블 정보가 있어야 한다"`
는 위 테스트와 다르게 예외를 체크하고 있지만 테스트 설명은 조금 다른 것 같아서요. 

`매장 식사 주문은 주문 테이블 정보가 없는 경우 주문이 불가능하다.` 이런 식으로 변경해 보는 것은 어떨까요?

2024-05-12 13:54 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +    }
상태가 더 늘어나면 점점 코드는 늘어나지 않을까요? 각각의 테스트에 맞는 Order를 한번만 생성해 보는 것은 어떨까요?

2024-05-15 09:16 UTC, gutenLEE reviewed
통합테스트에서 테스트 픽스처를 만들때 sql 스크립트, 영속성 레포지토리 객체를 사용할지 고민이 많이 되었습니다. 
리뷰어님께서는 실무에서 주로 어떤 방식을 사용하시는지 궁금합니다!

뭐든지 트레이드오프가 발생하는데 다른 회사의 개발팀에서는 어떤 장점을 취하고자 선택하는지 궁금합니다ㅎㅎ!

제가 생각한 장,단점은 아래와 같습니다
- sql스트립트
  - 데이터 생성이 편리하다
  - 스크립트 관리 비용이 발생한다
- 영속성 계층 레포지토리
  - 프로그래밍으로 다양한 상태의 테스트 픽스처를 생성할 수 있다
  - 코드 유지보수 비용이 발생한다

2024-05-15 09:16 UTC, gutenLEE commented on src/main/java/kitchenpos/domain/Order.java
앞선 PR에서 질문주신 동등성 비교 시 사용될 필드에 대해서 고민해봤습니다. 

객체의 식별자값이 동일하다면 다른 속성의 내용도 동일해야 하므로 
루트 객체와 연관 객체들의 식별자만 비교하는게 불필요한 equals() 연산을 줄일 수 있을 것 같습니다!

한 번도 고민해본적이 없는 부분이라 고민이 많이 되는 질문입니다!

2024-05-16 12:02 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 추가로 코멘트 남겼습니다.
확인 부탁드려요!

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/fixtures/OrderSteps.java
> +
Step들을 나눠주셨군요. 👍

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +
강의에서 가짜 객체에 대해서 다뤘을 것 같은데요. 이 부분도 적용해 보는 것은 어떨까요? 
테스트 전부 변경하기는 너무 많으니 일부라도 경험해 보시면 좋을 것 같습니다. :)
가짜 객체를 이용하면 테스트를 위한 의존성들이 많이 줄어들고 테스트 실행 시간도 많이 줄어들 거에요.

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
이 부분은 step으로 나눠 주신 부분이랑 비슷하긴 한 것 같은데요.

개인적으로 service를 3번이나 호출해야 하나 싶기도 해요. 
menuRepository를 통해서 숨겨져있는 Menu를 저장하고 `menuService#display` 한 번만 사용해도 괜찮지 않을까해서요! 
혹은 재사용성을 위해 OrderSteps 처럼 메서드 분리를 해도 좋을 것 같아요. 

`menuService#display` 하지 못하는 조건이 있는데 이 부분도 테스트 되면 좋을 것 같아요.

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +        }
`@EnumSource` 👍 

`@NullSource` 를 통해 실패하는 케이스도 테스트 하는 것은 어떨까요?

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/fixtures/OrderSteps.java
> +    }
이 부분들은 order에 대한 step들이 아닌 것 같은데 분리하거나 클래스 명을 바꿔보는 것은 어떨까요? 
분리한다면 step은 하나뿐이네요. 🤔

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/fixtures/OrderTableBuilder.java
> +    }
두 메서드는 어떤 차이인가요? 
emptyTable은 fixture로 OrderTable 객체가 제공되어도 괜찮을 것 같아요!

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuGroupServiceTest.java
> +import org.springframework.boot.test.context.SpringBootTest;
사용하지 않는 import는 제거하는 것이 어떨까요? 
사용하지도 않는데 큰 의미가 없다고 생각하실 수 있지만 저는 의존성 관리 측면에서 import 관리는 중요하다고 생각해요.

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderServiceTest.java
> +            menuRepository.save(menu);
이런 부분은 메뉴 생성 step에서 파라미터로 받아도 괜찮지 않을까요? 
혹은 사용자 입장(같이 개발하는 동료들)에서 사용하기 편하려면 여러가지 메서드들을 제공할 수 있을 것 같아요!

```java
    public Menu 숨겨진_메뉴를_생성한다() {
        final MenuGroup menuGroup = 메뉴그룹_생성한다();
        return 숨겨진_메뉴를_생성한다(menuGroup);
    }

    public Menu 숨겨진_메뉴를_생성한다(MenuGroup menuGroup) {
        return 메뉴를_생성한다("치킨", 10_000, menuGroup, false);
    }

    public Menu 노출된_메뉴를_생성한다() {
        final MenuGroup menuGroup = 메뉴그룹_생성한다();
        return 노출된_메뉴를_생성한다(menuGroup);
    }

    public Menu 노출된_메뉴를_생성한다(MenuGroup menuGroup) {
        return 메뉴를_생성한다("치킨", 10_000, menuGroup, true);
    }

    public Menu 메뉴를_생성한다(
        String name,
        int price,
        MenuGroup menuGroup,
        boolean displayed
    ) {
        return menuRepository.save(
            new MenuBuilder()
                .withMenuGroup(menuGroup)
                .withDisplayed(displayed)
                .with(name, BigDecimal.valueOf(price))
                .build()
        );
    }
```

2024-05-16 12:02 UTC, hyunssooo commented on src/test/java/fixtures/OrderSteps.java
> +
결국 이 메서드는 `WAITING` 상태로만 사용하고 있는데 파라미터로 받는 의미가 있을까요?

2024-05-16 12:04 UTC, hyunssooo commented
저희는 테스트마다 필요한 데이터들을 해당 테스트 내에서 코드로 생성하고 있습니다. :) 
이유는 별거 없는데요. 처음 작성할 때 그렇게 작성했기 때문이에요. sql 스크립트의 장점도 사실 크게 느끼지 못하고 있기 때문이에요.

2024-05-19 13:28 UTC, gutenLEE commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    void menuDisplayFailTest() {
요 테스트를 추가하면서 이전처럼 service를 여러번 호출했더니 
`display()`와 관련없는 메서드에서 테스트가 터졌네요..
검증할 메서드 이외에는 다른 메서드를 호출하면 검증할 메서드를 제대로 검증하지 못할 수 있음을 배웠네요. 
감사합니다!

2024-05-19 13:28 UTC, gutenLEE commented on src/test/java/kitchenpos/domain/FakeOrderRepository.java
> +    }
가짜객체를 만들때 이렇게 로직이 복잡해지면 이것또한 버그를 만들 수 있겠다는 생각을 했습니다!
이럴때는 현수님은 Mockito를 사용하시나요?!

2024-05-20 11:11 UTC, hyunssooo approved these changes
안녕하세요. 🙂
미션 진행하신다고 고생 많으셨습니다.
몇 가지 코멘트 남겼어요. 시간 되실 때 확인 부탁드려요.
궁금하신 부분 있으면 DM이나 코멘트 남겨주세요!

2024-05-20 11:11 UTC, hyunssooo commented on src/test/java/kitchenpos/application/MenuServiceTest.java
> +    }
```java
MenuGroup menuGroup = menuProductSteps.메뉴그룹_생성한다();
MenuProduct menuProduct = menuProductSteps.메뉴상품을_생성한다();
```
이 부분은 내부 테스트 마다 비슷하게 반복되니 `@BeforeEach` 통해 중복을 제거할 수 있을 것 같아요. 

`menuService#create` 로 넘기는 Menu 객체는 한줄로 작성해 너무 길고 가독성도 안좋습니다. 
이 부분의 변수로 분리해 가독성을 높여 보는 것은 어떨까요? 적절한 줄 바꿈도 포함되면 좋을 것 같아요.

2024-05-20 11:11 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderTableServiceTest.java
> +        assertThat(createdOrderTable.isOccupied()).isFalse();
`Assertions#assertAll` 를 사용하면 어떤 장점이 있을까요? 

```java
        assertAll(
            () -> assertThat(createdOrderTable).isNotNull(),
            () -> assertThat(createdOrderTable.getId()).isNotNull(),
            () -> assertThat(createdOrderTable.getName()).isEqualTo("1번"),
            () -> assertThat(createdOrderTable.getNumberOfGuests()).isEqualTo(0),
            () -> assertThat(createdOrderTable.isOccupied()).isFalse()
        );
```

2024-05-20 11:11 UTC, hyunssooo commented on src/test/java/kitchenpos/application/OrderTableServiceTest.java
> +    }
여기 indent가 조금 이상하네요. 🙂

2024-05-20 11:11 UTC, hyunssooo commented on src/test/java/kitchenpos/domain/FakeOrderRepository.java
> +    }
오 맞습니다. 가짜 객체에서도 로직은 충분히 실수할 수 있습니다. 저도 그런 경험이 있습니다. 그렇기 때문에 정확하게 만드는 것이 중요해요. 

mockito를 사용하거나 가짜 객체를 사용하는 것은 관점의 차이이고 상황에 따라서 다를 것 같은데요. 
개인적으로는 이 정도 복잡도는 아직은 괜찮다 입니다. 좀 더 복잡한 경우라면 저도 mockito를 사용할 것 같긴하네요.

2024-05-20 11:11 UTC, hyunssooo commented on src/test/java/fixtures/TestContainers.java
> +}
전부 묶어 주셨군요. 개인적으로는 필드가 모두 public 이니 사용하는 곳에서만 fake 객체를 선언해 사용해도 괜찮을 것 같긴해요. :) 참고만 부탁드려요.

2024-05-20 11:12 UTC, merged