3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #678
Opened 2024-05-12 10:50 UTC by wooddy-kim

### 작업 내역
- 정리된 요구사항을 토대로 테스트 코드 작성

### 기타
- Fake 객체 생성시 불필요한 코드를 제거하기 위해 서비스 코드 일부를 수정했습니다.
    -  JpaRepository -> Repository
- 주문/메뉴 데이터 생성시 연관된 데이터가 많아 가독성을 높이기 위해 DSL 을 작성했습니다.

2024-05-13 14:31 UTC, kyucumber requested changes
기존 코드를 보호하기 위한 테스트 코드를 잘 작성해주셨네요.

간단한 코멘트 몇개 남겨두었으니 참고 부탁드립니다. 잘 작성해주셔서 다음 요청시 머지하도록 할게요.

2024-05-13 14:31 UTC, kyucumber commented on src/main/java/kitchenpos/domain/MenuGroupRepository.java
>  }
도메인 내에서 이 인터페이스를 활용하게 되면 JpaRepository와 연관관계가 생기게 되는데요, 도메인적으로 활용할 목적으로 인터페이스를 만드시려면 아래와 같이 만드는것도 고려해보실 수 있을 것 같네요.

```java
public interface MenuRepository {
    Menu save(Menu menu);
    List<Menu> findAll();
}

public interface JpaMenuRepository extends MenuRepository, JpaRepository<Menu, UUID> {
    List<Menu> findAll();
}
```

지금처럼 단순한 경우 BaseRepository를 통해 테스트도 간단하게 작성할 수 있으므로 JPA와 의존이 없다는 점을 제외하면 당장 큰 이점은 없을 것 같네요. 그냥 참고차 말씀드린 부분이라 적용하지 않으셔도 됩니다!

2024-05-13 14:31 UTC, kyucumber commented on src/test/java/kitchenpos/application/OrderTableServiceTest.kt
> +    given("주문 테이블에 손님이 않을 떄") {
중요한 부분은 아니나 오타가 있네요!

```suggestion
    given("주문 테이블에 손님이 앉을 때") {
```

2024-05-13 14:31 UTC, kyucumber commented on src/test/java/kitchenpos/application/MenuGroupServiceMockTest.kt
> +class MenuGroupServiceMockTest : BehaviorSpec({
혹시 다른 테스트와 다르게 MenuGroupService만 왜 Mock 테스트인 이유가 있을까요?

2024-05-13 14:31 UTC, kyucumber commented on src/test/java/kitchenpos/application/ProductServiceTest.kt
> +    given("가격을 변경할 떄") {
> 상품의 가격이 변경될 때 메뉴의 가격이 메뉴에 속한 상품 금액의 합보다 크면 메뉴가 숨겨진다.

위의 요구사항에 대해서도 테스트를 작성하면 어떨까요?

2024-05-14 01:21 UTC, wooddy-kim commented on src/test/java/kitchenpos/application/MenuGroupServiceMockTest.kt
> +class MenuGroupServiceMockTest : BehaviorSpec({
초반에 mock 으로 작성하다가 fake 객체로 변경했는데 누락된 것 같습니다! 감사합니다.

2024-05-14 01:27 UTC, wooddy-kim commented on src/main/java/kitchenpos/domain/MenuGroupRepository.java
>  }
@kyucumber 
오 좋은 방법인 것 같습니다! 언급하신 것처럼 '단순한 경우 당장 큰 이점이 없다' 는 부분에 공감하는데요.
그렇다면 이점을 가지는 순간이 언제일까요? JPA 를 실무에서 사용하지 않다 보니 어떤 상황에서 이점을 발휘할지 잘 떠오르지 않습니다.

2024-05-14 01:47 UTC, wooddy-kim commented
@kyucumber 꼼꼼하게 리뷰해주셔서 감사합니다. 코멘트 남긴 부분 반영했습니다!

2024-05-14 02:39 UTC, kyucumber commented on src/main/java/kitchenpos/domain/MenuGroupRepository.java
>  }
현재는 Repository -> BaseRepository -> MenuRepository와 같은 다소 복잡한 상속 구조를 가지고 있습니다. 도메인에서 순수한 MenuRepository 인터페이스만 참조하므로 구조가 비교적 단순해지겠네요.

그리고 JPA나 여타 다른 기술에 아무런 의존성을 가지지 않을 수 있는 장점이 있을 것 같네요. 현재 BaseRepository 내부에서 `@NoRepositoryBean`과 같은 어노테이션을 사용하고 있는데 이는 순수하게 언어적 레벨에서 제공해주는 범위를 넘어서고 있어요. 이렇기 때문에 추후에 JPA가 아닌 다른 기술이나 다른 데이터 저장소를(외부 API)를 사용할 가능성이 생겨도 쉽게 교체할 수 있겠죠.

2024-05-14 02:40 UTC, kyucumber commented on src/main/java/kitchenpos/domain/MenuGroupRepository.java
>  }
그리고 지금 Repository 인터페이스를 사용해주셨는데, 단순한 테스트만 작성하면 되는 부분이라 별도로 말씀을 안 드렸지만 거의 사용하지 않는 인터페이스일거에요. 일반적으로 JpaRepository를 많이 사용할 것 같습니다. 내부 인터페이스 구조는 한번 별도로 학습해보시면 좋을 것 같네요.

- JpaRepository
- PagingAndSortingRepository
- CrudRepository

등 다양한 인터페이스가 있습니다만 최상위인 Repository를 사용하는 경우는 잘 없습니다.

2024-05-14 02:41 UTC, kyucumber approved these changes
https://github.com/next-step/ddd-legacy/pull/678#discussion_r1599303437
https://github.com/next-step/ddd-legacy/pull/678#discussion_r1599304184

남겨두신 질문에 답변 남겨두었습니다. 답변이 부족하다면 DM을 주셔도 될 것 같아요. 마지막까지 수고 많으셨습니다.

2024-05-14 02:41 UTC, merged