Step3 : 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #692
Opened 2024-05-15 23:25 UTC by wsdf25867

안녕하세요 

step3 테스트를 통한 코드 보호 리뷰 요청드립니다!

`Mockito`를 사용한 테스트코드 작성이 익숙하지 않아 잘 작성한건지 모르곘네요 ㅎㅎ

2024-05-16 15:22 UTC, kyucumber requested changes
미션에서 요구하는 요구사항들에 대한 테스트 코드 작성을 빠짐없이 잘 해주신 것 같네요!

바로 머지할 수 있으나 간단한 코멘트 남겨두었으니 한번 확인 부탁드려요.

다시 한번 요청주시면 바로 머지하도록 하겠습니다.

2024-05-16 15:22 UTC, kyucumber commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("없는 상품")
상품 수정시라는걸 명확하게 나타내면 좋을 것 같아요!

동일하게 수정에 대한 테스트를 여러개 작성할 때 테스트를 한눈에 보려면 Nested와 같은 어노테이션을 이용해 계층 구조로 테스트를 구현할수도 있습니다.

아래 문서 한번 참고해보셔도 좋을 것 같네요.

https://velog.io/@songs4805/%EA%B3%84%EC%B8%B5-%EA%B5%AC%EC%A1%B0%EC%9D%98-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%BD%94%EB%93%9C-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0

2024-05-16 15:22 UTC, kyucumber commented on src/test/java/kitchenpos/application/ProductServiceTest.java
> +    @DisplayName("가격 정상 수정 메뉴 비노출")
가격은 정상적으로 수정되었으나 요구사항에 정의한 메뉴 가격이 상품 금액의 합보다 커서 메뉴가 숨겨진 부분이 테스트 DisplayName을 통해 명확히 드러나면 좋을 것 같아요.

지금은 정상 수정 이후 요구사항에 의해 메뉴의 노출 여부가 변경된건지 아닌지 한눈에 알기 어려워보여요.

2024-05-16 22:34 UTC, wsdf25867 commented
리뷰 감사합니다

Nested 는 몰랐네요! 확실히 한 메서드에 여러 테스트가 있을때는 메서드 단위로 묶어서 보기도 편할것 같아요! 

저는 테스트대상 코드의 메서드 단위로 커밋 단위를 잡았는데 혹시 리뷰어님은 테스트 코드에서 커밋 단위는 어떻게 가져가시나요??

2024-05-17 14:19 UTC, kyucumber commented
> Nested 는 몰랐네요! 확실히 한 메서드에 여러 테스트가 있을때는 메서드 단위로 묶어서 보기도 편할것 같아요!

네 저도 가독성 측면에서 장점이 있다고 생각해요. 자바를 사용할 때 Nested를 쓰다가 현재는 kotlin에서 DescribeSpec을 사용해 테스트를 작성하고 있습니다.

> 저는 테스트대상 코드의 메서드 단위로 커밋 단위를 잡았는데 혹시 리뷰어님은 테스트 코드에서 커밋 단위는 어떻게 가져가시나요??

커밋을 명확하게 구동되는 단위로 관리하기 힘들어서 막 커밋해둔 다음에 한 클래스나 기능이 완료되면 reset 후 하나의 커밋으로 가져가는 경우가 많은 것 같아요. 단순히 테스트만 작성하면 되는 상황이라면 해당 클래스에 해당하는 테스트를 다 짠 다음에 해당 테스트 클래스를 커밋할 것 같네요. 테스트 메서드 하나 단위로 커밋을 작서앟면 커밋이 너무 많아질 것 같아요.

2024-05-17 14:20 UTC, kyucumber approved these changes
https://github.com/next-step/ddd-legacy/pull/692#issuecomment-2117718152

질문 남겨두신 부분에 코멘트 남겨두었으니 확인 부탁드려요. 🙇 

마지막까지 고생 많으셨습니다.

2024-05-17 14:20 UTC, merged