🚀 3단계 - 테스트를 통한 코드 보호
next-step/ddd-legacy pull request #704
Opened 2024-05-26 09:28 UTC by Snotra-p

리뷰 잘부탁드립니다.

2024-05-27 06:36 UTC, sah3122 requested changes
Fake 객체와 Fixture를 활용하여 테스트 코드작성 잘해주셨네요 👍 
몇가지 생각거리를 남겨두었는데 확인 부탁드립니다 !

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/MenuGroupServiceIntegrationTest.java
> +@ExtendWith(MockitoExtension.class)
Fake 객체를 활용하여 테스트 코드를 작성해주셨는데 MockitoExtension 정의가 필요할까요 ?

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/MenuServiceIntegrationTest.java
> +    private PurgomalumClient purgomalumClient;
InMemory Repository를 선언해주신것과 동일하게 Fake Client를 구현해보는건 어떨까요 ?

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/MenuServiceIntegrationTest.java
> +        Product product = ProductFixture.create("후라이드치킨", BigDecimal.valueOf(16000L));
Fixture Method를 통해 테스트 객체를 생성하는것도 좋지만 자주 사용되거나 의미를 가지는 테스트 객체는 Fixture 클래스가 객체로 전달 해주는것도 테스트 코드의 가독성이 올라갈수 있습니다 😄 
```suggestion
        Product 후라이드치킨_16000원 = ProductFixture.후라이드치킨_16000원();
```

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +        }
테스트 코드에는 검증 코드만 존재하고 비즈니스 로직이 들어가면 안된다고 생각합니다. 
주문 유형에 따라 테스트 코드를 분리해보세요 😄

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +        }
ExceptionTest에 포함되지 않는 케이스 인것 같습니다 😄

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +            order.getOrderLineItems().get(0).setPrice(BigDecimal.valueOf(9999));
TestFixture를 활용하여 테스트에 필요한 객체를 제공받고, 재사용할수 있는 구조로 변경해보는건 어떨까요 ?

2024-05-27 06:36 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +    class TakeOutOrders {
Nested 테스트 작성 👍

2024-05-28 15:16 UTC, Snotra-p commented on src/test/java/kitchenpos/integrationTest/MenuGroupServiceIntegrationTest.java
> +@ExtendWith(MockitoExtension.class)
일단은 외부 의존성이라고 가정해서  Mock을 사용해봤습니다~
동일하게 호출해도 exception이 나는 상황이 있을것 같아서요.

2024-05-28 15:16 UTC, Snotra-p commented on src/test/java/kitchenpos/integrationTest/MenuServiceIntegrationTest.java
> +    private PurgomalumClient purgomalumClient;
위에서 설명한 이유로 Mock으로 만들어봤습니다~

2024-05-28 15:20 UTC, Snotra-p commented
일단 수정해 보았는데요 코멘트중 일부가 이해를 못한부분은 수정하지 못했습니다.
조금 자세히 코멘트를 주시면 반영하도록 하겠습니다.
Mock을 사용한 이유는 위에 적긴했는데 혹시 다른 Fake를 사용해야 하는 이유가 있다면 알려주시면 감사합니다~

2024-05-29 13:38 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/MenuGroupServiceIntegrationTest.java
> +@ExtendWith(MockitoExtension.class)
Fake 객체를 사용하는 이유중 하나는 제어하지 못하는 외부 의존성을 제어하기 위함으로 볼수 있을것 같아요 😄 
MenuGroupServiceIntegrationTest 는 외부 의존성이 없는 상태니 개인적으로는 Mockito 의존성을 제거해도 될것 같습니다 !

2024-05-29 14:03 UTC, sah3122 requested changes
몇가지 생각거리와 남겨주신 질문에 대해 코멘트 추가해두었는데 확인 부탁드립니다 😄

2024-05-29 14:03 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/MenuServiceIntegrationTest.java
> +    private PurgomalumClient purgomalumClient;
이번 미션을 통해 Fake 객체를 활용한 테스트 코드 작성 방식을 더 경험하기 위해 남겨둔 코멘트라고 봐주시면 될것 같습니다 😄

2024-05-29 14:03 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/MenuServiceIntegrationTest.java
> +        Product product = ProductFixture.create("후라이드치킨", BigDecimal.valueOf(16000L));
현재 TestFixture를 단순 팩토리 역할로만 사용하고 계신것 같습니다. 
남겨드린 코멘트처럼 자주 사용되거나, 의미를 가지는 테스트 객체를 Fixture 클래스에 정의하고, 테스트 코드에서는 정의된 Fixture를 가져다 사용하여 가독성을 높이고 테스트 코드 작성 리소스를 줄일수 있는 경험을 해보세요 😄

2024-05-29 14:03 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +        }
`CommonExceptionTests`는 실패하는 케이스를 모아둔 클래스가 아닌것일까요 ? 
@Nested 클래스도 DisplayName을 사용할수 있습니다. 
DisplayName을 통해 테스트의 의도를 명확하게 나타내보세요 👍

2024-05-29 14:03 UTC, sah3122 commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +        }
검증하고자 하는 단언문이 많다면 `assertAll()`을 활용하는것도 좋을것 같아요 😄 
단언문을 나열하는것과 assertAll()을 사용하는것에 대한 차이점을 학습해보세요.

2024-05-29 14:45 UTC, Snotra-p commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +        }
앗...실수인것 같습니다. 원래 의도는 CommonOrderTest라고 주문 타입 상관없이 검증해야되는 테스트를 모은것이었습니다.

2024-05-29 14:53 UTC, Snotra-p commented on src/test/java/kitchenpos/integrationTest/OrderServiceIntegrationTest.java
> +        }
알아보니 중간에 단언문이 실패해도 중단하지않고 모든 assertion을 다 실행해서 보여주는것 같네요! 감사합니다~!

2024-05-29 15:09 UTC, Snotra-p commented
말씀하신 부분들 반영했습니다.
계속해서 피드백 더 많이 주셔도 괜찮습니다~ 편하게 부탁드립니다~

2024-05-30 07:49 UTC, sah3122 commented on src/test/java/kitchenpos/fixtures/MenuGroupFixture.java
>  }
파일의 마지막은 new line 으로 끝나는것을 권장 드립니다 😄 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
intellij 를 사용하고 계시다면 아래 문서를 확인해보세요 ! 
https://velog.io/@d-h-k/intellij-%ED%8C%8C%EC%9D%BC%EB%81%9D%EC%97%90-%EA%B0%9C%ED%96%89%EC%9D%84-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

2024-05-30 07:51 UTC, sah3122 commented on src/test/java/kitchenpos/fixtures/OrderLineItemFixture.java
> +    }
자주 사용되는 Fixture 객체 정의 👍 
Fixture를 꾸준히 관리하다보면 새로운 테스트에 필요한 데이터를 생성하지 않고 Fixture에서 꺼내어 사용할수 있게되어 테스트 코드 작성이 더욱 편리해지는 경험을 하실수 있을거에요 😄

2024-05-30 07:51 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
이번 미션은 여기서 마무리 짓도록 할게요 ! 
적지않은 피드백 반영해주신다고 고생많으셨습니다 😄

2024-05-30 07:51 UTC, merged